spring.profiles: default,prod

webConstant:
  singleCommonJs: 
   org.shaolin.vogerp.ecommercial.page.OrderManagement:
    - /js/controls/countdown/jquery.ba-throttle-debounce.min.js
    - /js/controls/countdown/jquery.knob.min.js
    - /js/controls/countdown/jquery.redcountdown.js
   org.shaolin.vogerp.ecommercial.page.OnlineOrderList:
    - /js/controls/countdown/jquery.ba-throttle-debounce.min.js
    - /js/controls/countdown/jquery.knob.min.js
    - /js/controls/countdown/jquery.redcountdown.js
    - /js/org/shaolin/vogerp/ecommercial/form/GoldenOrderOverView.js
    - /js/org/shaolin/vogerp/ecommercial/form/RentOrderOverView.js
   
  singleCommonAppJs:
    org.shaolin.vogerp.ecommercial.page.OnlineOrderList_mob:
    - /js/controls/countdown/jquery.ba-throttle-debounce.min.js
    - /js/controls/countdown/jquery.knob.min.js
    - /js/controls/countdown/jquery.redcountdown.js
    - /js/org/shaolin/vogerp/ecommercial/form/GoldenOrderOverView_mob.js
    - /js/org/shaolin/vogerp/ecommercial/form/RentOrderOverView_mob.js