#---------------------------------------
-- Drop SQL Generated         --
--                                    --
-- Please DO NOT modify !!            --
-- Generated on 2015-07-11 10:49:49   --
#---------------------------------------

USE <database name>;

DROP TABLE ORDER_SALEORDER CASCADE;

DROP TABLE ORDER_PURCHASEORDER CASCADE;

DROP TABLE ORDER_PRODUCTORDER CASCADE;

DROP TABLE ORDER_ORDERITEM CASCADE;

DROP TABLE ORDER_ORDERHANDLINGINFO CASCADE;

DROP TABLE ORDER_DELIVERYINFO CASCADE;

DROP TABLE ORDER_SALEORDER_ORDERITEM_JT CASCADE;

DROP TABLE ORDER_PURCHASEORDER_ORDERITEM_JT CASCADE;

DROP TABLE ORDER_PRODUCTORDER_ORDERITEM_JT CASCADE;

