#---------------------------------------
-- Create SQL Generated               --
--                                    --
-- Please DO NOT modify !!            --
-- Generated on 2015-07-11 10:49:49   --
#---------------------------------------

USE <database name>;

-- ORDER_SALEORDER
CREATE TABLE ORDER_SALEORDER
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 PARENTID BIGINT(38),
 SERIALNUMBER VARCHAR(255),
 DESCRIPTION VARCHAR(255),
 CREATEDATE DATETIME,
 DELIVERYDATE DATETIME,
 DISCOUNT DECIMAL,
 STATUS INT(2),
 CUSTOMERID BIGINT(38),
 DELIVERYINFOID BIGINT(38),
 PURCHASEDORDERID BIGINT(38),
 _enable INT(2) DEFAULT 1,
 PRIMARY KEY(ID)
);

-- ORDER_PURCHASEORDER
CREATE TABLE ORDER_PURCHASEORDER
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 PARENTID BIGINT(38),
 SERIALNUMBER VARCHAR(255),
 DESCRIPTION VARCHAR(255),
 CREATEDATE DATETIME,
 STARTCREATEDATE DATETIME,
 ENDCREATEDATE DATETIME,
 DISCOUNT DECIMAL,
 STATUS INT(2),
 SUPPLIERID BIGINT(38),
 _enable INT(2) DEFAULT 1,
 PRIMARY KEY(ID)
);

-- ORDER_PRODUCTORDER
CREATE TABLE ORDER_PRODUCTORDER
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 PARENTID BIGINT(38),
 SERIALNUMBER VARCHAR(255),
 DESCRIPTION VARCHAR(255),
 CREATEDATE DATETIME,
 STARTCREATEDATE DATETIME,
 ENDCREATEDATE DATETIME,
 DISCOUNT DECIMAL,
 STATUS INT(2),
 _enable INT(2) DEFAULT 1,
 PRIMARY KEY(ID)
);

-- ORDER_ORDERITEM
CREATE TABLE ORDER_ORDERITEM
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 PRODUCTID BIGINT(38),
 PRICEID BIGINT(38),
 AMOUNT INT(10),
 UNITPRICE DECIMAL,
 AJUSTPRICETYPE INT(2),
 AJUSTPRICE DECIMAL,
 COMMENT VARCHAR(255),
 TERMS INT(2),
 _index INT(4),
 _enable INT(2) DEFAULT 1,
 _version INT(2) DEFAULT 0,
 _starttime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 _endtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 _optuserid BIGINT(38) DEFAULT 0,
 PRIMARY KEY(ID)
);

-- ORDER_ORDERHANDLINGINFO
CREATE TABLE ORDER_ORDERHANDLINGINFO
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 PARTYID BIGINT(38),
 HANLDINGSTATE VARCHAR(255),
 PERCENTAGE DECIMAL,
 COMMENT VARCHAR(255),
 _index INT(4),
 _enable INT(2) DEFAULT 1,
 _version INT(2) DEFAULT 0,
 _starttime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 _endtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 _optuserid BIGINT(38) DEFAULT 0,
 PRIMARY KEY(ID)
);

-- ORDER_DELIVERYINFO
CREATE TABLE ORDER_DELIVERYINFO
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 ADDRESSID BIGINT(38),
 CONTACTID BIGINT(38),
 id BIGINT(38),
 COMMENT VARCHAR(255),
 _enable INT(2) DEFAULT 1,
 _version INT(2) DEFAULT 0,
 _starttime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 _endtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 _optuserid BIGINT(38) DEFAULT 0,
 PRIMARY KEY(ID)
);

-- Join table ORDER_SALEORDER_ORDERITEM_JT
CREATE TABLE ORDER_SALEORDER_ORDERITEM_JT
(ID BIGINT(38),
 ELT BIGINT(38),
 _index INT(5));

-- Join table ORDER_PURCHASEORDER_ORDERITEM_JT
CREATE TABLE ORDER_PURCHASEORDER_ORDERITEM_JT
(ID BIGINT(38),
 ELT BIGINT(38),
 _index INT(5));

-- Join table ORDER_PRODUCTORDER_ORDERITEM_JT
CREATE TABLE ORDER_PRODUCTORDER_ORDERITEM_JT
(ID BIGINT(38),
 ELT BIGINT(38),
 _index INT(5));

