/*
 *
 * This file is automatically generated on Sat Jul 11 22:49:45 CST 2015
 */

    
package org.shaolin.vogerp.order.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;



/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public class DeliveryInfoImpl  implements org.shaolin.vogerp.order.be.IDeliveryInfo
{
    private static final long serialVersionUID = 0x90B1123CE87B50FFL;

    private final IConstantService ceService = AppContext.get().getConstantService();

    protected String getBusinessEntityName()
    {
        return "org.shaolin.vogerp.order.be.DeliveryInfo";
    }

    public DeliveryInfoImpl()
    {
        
        _extField = new BEExtensionInfo();
        
    }
    
    
        /**
     * Enable record
     */
    private boolean _enable = true;


    /**
     * History version
     */
    protected int _version = 0;

    /**
     * History starttime
     */
    private java.util.Date _starttime = new java.util.Date();

    /**
     * History endtime
     */
    private java.util.Date _endtime = null;

    /**
     * History _optuserid
     */
    private long _optuserid = 0L;


    /**
     *  BEExtension _extType
     */
    protected String _extType;

    /**
     *  BEExtension _extField
     */
    protected BEExtensionInfo _extField;
        
   /**
     *  help is not available
     */    
    protected long id;
    
   /**
     *  help is not available
     */    
    protected long addressId;
    
   /**
     *  help is not available
     */    
    protected org.shaolin.vogerp.commonmodel.be.AddressInfoImpl address;
    
   /**
     *  help is not available
     */    
    protected long contactId;
    
   /**
     *  help is not available
     */    
    protected org.shaolin.vogerp.commonmodel.be.ContactInfoImpl contact;
    
   /**
     *  help is not available
     */    
    protected java.lang.String comment;
    
        /**
     *  Is enable
     *
     *  @return boolean
     */
    public boolean isEnabled() {
        return _enable;
    }
            /**
     *  Is enable
     *
     *  @return boolean
     */
    private boolean get_enable() {
        return _enable;
    }
        
    /**
     *  get version
     *
     *  @return version
     */
    public int getVersion() {
        return _version;
    }

    private int get_version() {
        return _version;
    }

    /**
     *  get operator user id
     *
     *  @return user id
     */
    public long getOptUserId() {
        return _optuserid;
    }

    /**
     *  get operator user id
     *
     *  @return user id
     */
    private long get_optuserid() {
        return _optuserid;
    }

    /**
     *  get start time
     *
     *  @return start time
     */
    public java.util.Date getStarttime() {
        return _starttime;
    }

    private java.util.Date get_starttime() {
        return _starttime;
    }

    /**
     *  get endtime
     *
     *  @return endtime
     */
    public java.util.Date getEndtime() {
        return _endtime;
    }

    private java.util.Date get_endtime() {
        return _endtime;
    }


    /**
     *  get _extType
     *
     *  @return _extType
     */
    public String get_extType() {
        return _extType;
    }

    /**
     *  get _extField
     *
     *  @return _extField
     */
    public BEExtensionInfo get_extField() {
        return _extField;
    }
        
    /**
     *  get id
     *
     *  @return id
     */
    public long getId() {
        return id;
    }

    /**
     *  get addressId
     *
     *  @return addressId
     */
    public long getAddressId() {
        return addressId;
    }

    /**
     *  get address
     *
     *  @return address
     */
    public org.shaolin.vogerp.commonmodel.be.AddressInfoImpl getAddress() {
        return address;
    }

    /**
     *  get contactId
     *
     *  @return contactId
     */
    public long getContactId() {
        return contactId;
    }

    /**
     *  get contact
     *
     *  @return contact
     */
    public org.shaolin.vogerp.commonmodel.be.ContactInfoImpl getContact() {
        return contact;
    }

    /**
     *  get comment
     *
     *  @return comment
     */
    public java.lang.String getComment() {
        return comment;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    public void setEnabled(boolean enable) {
        _enable = enable;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    private void set_enable(boolean enable) {
        _enable = enable;
    }

    
    /**
     *  set version
     */
    public void setVersion(int version) {
        _version = version;
    }

    private void set_version(int version) {
        _version = version;
    }

    /**
     *  set operator user id
     *  @parameter user id.
     */
    public void setOptUserId(long optUserId) {
        _optuserid = optUserId;
    }

    /**
     *  set operator user id
     *  @parameter user id.
     */
    private void set_optuserid(long optUserId) {
        _optuserid = optUserId;
    }

    /**
     *  set start time
     *  @parameter start time which is the start time of object.
     */
    public void setStarttime(java.util.Date starttime) {
        _starttime = starttime;
    }

    private void set_starttime(java.util.Date starttime) {
        _starttime = starttime;
    }

    /**
     *  set endtime
     *  @parameter endtime which is the end time of object.
     */
    public void setEndtime(java.util.Date endtime) {
        _endtime = endtime;
    }

    private void set_endtime(java.util.Date endtime) {
        _endtime = endtime;
    }

/**
     *  set _extType
     *  @param _extType which is the extension type of be object.
     */
    public void set_extType(java.lang.String _extType) {
        this._extType = _extType;
    }
        
    /**
     *  set id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     *  set addressId
     */
    public void setAddressId(long addressId) {
        this.addressId = addressId;
    }

    /**
     *  set address
     */
    public void setAddress(org.shaolin.vogerp.commonmodel.be.AddressInfoImpl address) {
        this.address = address;
    }

    /**
     *  set contactId
     */
    public void setContactId(long contactId) {
        this.contactId = contactId;
    }

    /**
     *  set contact
     */
    public void setContact(org.shaolin.vogerp.commonmodel.be.ContactInfoImpl contact) {
        this.contact = contact;
    }

    /**
     *  set comment
     */
    public void setComment(java.lang.String comment) {
        this.comment = comment;
    }

    
    /**
     * Check different according to primary key.
     */
    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof org.shaolin.vogerp.order.be.DeliveryInfoImpl))
            return false;
        org.shaolin.vogerp.order.be.DeliveryInfoImpl o = (org.shaolin.vogerp.order.be.DeliveryInfoImpl)obj;
        
        boolean result = super.equals(obj);

        boolean eq = true;
        
        return result;
    }

    /**
     * Generate hashCode according to primary key.
     */
    public int hashCode() {
        
        int result = super.hashCode();

        return result;
    }
        
    
     /**
     * Gets the String format of the business entity.
     *
     * @return String the business entity in String format.
     */
    public  String  toString() {
        StringBuffer aBuf = new StringBuffer();
        aBuf.append("org.shaolin.vogerp.order.be.DeliveryInfo");
    
        aBuf.append(" : ");
        
        aBuf.append("enable=").append(_enable).append(", ");
        
        aBuf.append("id");
        aBuf.append("=");
        aBuf.append(id);
        aBuf.append(", ");
        
        aBuf.append("addressId");
        aBuf.append("=");
        aBuf.append(addressId);
        aBuf.append(", ");
        
        aBuf.append("address");
        aBuf.append("=");
        aBuf.append(address==null? "" : address.toString());
        aBuf.append(", ");
        
        aBuf.append("contactId");
        aBuf.append("=");
        aBuf.append(contactId);
        aBuf.append(", ");
        
        aBuf.append("contact");
        aBuf.append("=");
        aBuf.append(contact==null? "" : contact.toString());
        aBuf.append(", ");
        
        aBuf.append("comment");
        aBuf.append("=");
        aBuf.append(comment);
        aBuf.append(", ");
        
        return aBuf.toString();
    }
    
    
     /**
     * Gets list of MemberType.
     *
     * @return List     the list of MemberType.
     */
    public List<MemberType> getMemberList() {
        List<MemberType> memberTypeList = new ArrayList<MemberType>();
        
        MemberType member = null;
        
        org.shaolin.bmdp.datamodel.bediagram.LongType idBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for id
        member = new MemberType();
        member.setName("id");
        member.setDescription("null");
        member.setType(idBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.LongType addressIdBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for addressId
        member = new MemberType();
        member.setName("addressId");
        member.setDescription("null");
        member.setType(addressIdBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.BEObjRefType addressBEType = new org.shaolin.bmdp.datamodel.bediagram.BEObjRefType();
    
        TargetEntityType addressTargetEntity = new TargetEntityType();
        addressTargetEntity.setEntityName("org.shaolin.vogerp.commonmodel.be.AddressInfo");
        addressBEType.setTargetEntity(addressTargetEntity);
            
        //MemberType Define for address
        member = new MemberType();
        member.setName("address");
        member.setDescription("null");
        member.setType(addressBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.LongType contactIdBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for contactId
        member = new MemberType();
        member.setName("contactId");
        member.setDescription("null");
        member.setType(contactIdBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.BEObjRefType contactBEType = new org.shaolin.bmdp.datamodel.bediagram.BEObjRefType();
    
        TargetEntityType contactTargetEntity = new TargetEntityType();
        contactTargetEntity.setEntityName("org.shaolin.vogerp.commonmodel.be.ContactInfo");
        contactBEType.setTargetEntity(contactTargetEntity);
            
        //MemberType Define for contact
        member = new MemberType();
        member.setName("contact");
        member.setDescription("null");
        member.setType(contactBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType commentBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for comment
        member = new MemberType();
        member.setName("comment");
        member.setDescription("null");
        member.setType(commentBEType);
        memberTypeList.add(member);
            
        return memberTypeList;
    }
    
    public IDeliveryInfo createEntity ()
    {
        return new DeliveryInfoImpl();
    }
    
}

        

