/*
 *
 * This file is automatically generated on Sat Jul 11 22:49:45 CST 2015
 */

    
package org.shaolin.vogerp.order.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;



/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public interface IDeliveryInfo 
    extends IPersistentEntity, IExtensibleEntity
{
    public final static String ENTITY_NAME = "org.shaolin.vogerp.order.be.DeliveryInfo";
    
 
    /**
     *  get id
     *
     *  @return id
     */
    public long getId();

    /**
     *  get addressId
     *
     *  @return addressId
     */
    public long getAddressId();

    /**
     *  get address
     *
     *  @return address
     */
    public org.shaolin.vogerp.commonmodel.be.AddressInfoImpl getAddress();

    /**
     *  get contactId
     *
     *  @return contactId
     */
    public long getContactId();

    /**
     *  get contact
     *
     *  @return contact
     */
    public org.shaolin.vogerp.commonmodel.be.ContactInfoImpl getContact();

    /**
     *  get comment
     *
     *  @return comment
     */
    public java.lang.String getComment();

    /**
     *  set id
     */
    public void setId(long id);

    /**
     *  set addressId
     */
    public void setAddressId(long addressId);

    /**
     *  set address
     */
    public void setAddress(org.shaolin.vogerp.commonmodel.be.AddressInfoImpl address);

    /**
     *  set contactId
     */
    public void setContactId(long contactId);

    /**
     *  set contact
     */
    public void setContact(org.shaolin.vogerp.commonmodel.be.ContactInfoImpl contact);

    /**
     *  set comment
     */
    public void setComment(java.lang.String comment);


}

        