/*
 *
 * This file is automatically generated on Sat Jul 11 22:49:45 CST 2015
 */

    
package org.shaolin.vogerp.order.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;

import org.shaolin.vogerp.order.ce.*;


/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public interface IOrderItem 
    extends IPersistentEntity, IExtensibleEntity
{
    public final static String ENTITY_NAME = "org.shaolin.vogerp.order.be.OrderItem";
    
 
    /**
     *  get id
     *
     *  @return id
     */
    public long getId();

    /**
     *  get productId
     *
     *  @return productId
     */
    public long getProductId();

    /**
     *  get product
     *
     *  @return product
     */
    public org.shaolin.vogerp.productmodel.be.ProductImpl getProduct();

    /**
     *  get priceId
     *
     *  @return priceId
     */
    public long getPriceId();

    /**
     *  get pricePackage
     *
     *  @return pricePackage
     */
    public org.shaolin.vogerp.productmodel.be.ProductPriceImpl getPricePackage();

    /**
     *  get amount
     *
     *  @return amount
     */
    public int getAmount();

    /**
     *  get unitPrice
     *
     *  @return unitPrice
     */
    public double getUnitPrice();

    /**
     *  get ajustPriceType
     *
     *  @return ajustPriceType
     */
    public AjustPriceType getAjustPriceType();

    /**
     *  get ajustPrice
     *
     *  @return ajustPrice
     */
    public double getAjustPrice();

    /**
     *  get comment
     *
     *  @return comment
     */
    public java.lang.String getComment();

    /**
     *  get terms
     *
     *  @return terms
     */
    public OrderTermsType getTerms();

    /**
     *  set id
     */
    public void setId(long id);

    /**
     *  set productId
     */
    public void setProductId(long productId);

    /**
     *  set product
     */
    public void setProduct(org.shaolin.vogerp.productmodel.be.ProductImpl product);

    /**
     *  set priceId
     */
    public void setPriceId(long priceId);

    /**
     *  set pricePackage
     */
    public void setPricePackage(org.shaolin.vogerp.productmodel.be.ProductPriceImpl pricePackage);

    /**
     *  set amount
     */
    public void setAmount(int amount);

    /**
     *  set unitPrice
     */
    public void setUnitPrice(double unitPrice);

    /**
     *  set ajustPriceType
     */
    public void setAjustPriceType(AjustPriceType ajustPriceType);

    /**
     *  set ajustPrice
     */
    public void setAjustPrice(double ajustPrice);

    /**
     *  set comment
     */
    public void setComment(java.lang.String comment);

    /**
     *  set terms
     */
    public void setTerms(OrderTermsType terms);


}

        