/*
 *
 * This file is automatically generated on Sat Jul 11 22:49:45 CST 2015
 */

    
package org.shaolin.vogerp.order.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;

import org.shaolin.vogerp.order.ce.*;


/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public class OrderItemImpl  implements org.shaolin.vogerp.order.be.IOrderItem
{
    private static final long serialVersionUID = 0x90B1123CE87B50FFL;

    private final IConstantService ceService = AppContext.get().getConstantService();

    protected String getBusinessEntityName()
    {
        return "org.shaolin.vogerp.order.be.OrderItem";
    }

    public OrderItemImpl()
    {
        
        _extField = new BEExtensionInfo();
        
    }
    
    
        /**
     * Enable record
     */
    private boolean _enable = true;


    /**
     * History version
     */
    protected int _version = 0;

    /**
     * History starttime
     */
    private java.util.Date _starttime = new java.util.Date();

    /**
     * History endtime
     */
    private java.util.Date _endtime = null;

    /**
     * History _optuserid
     */
    private long _optuserid = 0L;


    /**
     *  BEExtension _extType
     */
    protected String _extType;

    /**
     *  BEExtension _extField
     */
    protected BEExtensionInfo _extField;
        
   /**
     *  help is not available
     */    
    protected long id;
    
   /**
     *  help is not available
     */    
    protected long productId;
    
   /**
     *  help is not available
     */    
    protected org.shaolin.vogerp.productmodel.be.ProductImpl product;
    
   /**
     *  help is not available
     */    
    protected long priceId;
    
   /**
     *  help is not available
     */    
    protected org.shaolin.vogerp.productmodel.be.ProductPriceImpl pricePackage;
    
   /**
     *  help is not available
     */    
    protected int amount;
    
   /**
     *  help is not available
     */    
    protected double unitPrice;
    
   /**
     *  help is not available
     */    
    protected AjustPriceType ajustPriceType = AjustPriceType.NOT_SPECIFIED;
    
    protected int ajustPriceTypeInt = AjustPriceType.NOT_SPECIFIED.getIntValue();
    
   /**
     *  help is not available
     */    
    protected double ajustPrice;
    
   /**
     *  help is not available
     */    
    protected java.lang.String comment;
    
   /**
     *  help is not available
     */    
    protected OrderTermsType terms = OrderTermsType.NOT_SPECIFIED;
    
    protected int termsInt = OrderTermsType.NOT_SPECIFIED.getIntValue();
    
        /**
     *  Is enable
     *
     *  @return boolean
     */
    public boolean isEnabled() {
        return _enable;
    }
            /**
     *  Is enable
     *
     *  @return boolean
     */
    private boolean get_enable() {
        return _enable;
    }
        
    /**
     *  get version
     *
     *  @return version
     */
    public int getVersion() {
        return _version;
    }

    private int get_version() {
        return _version;
    }

    /**
     *  get operator user id
     *
     *  @return user id
     */
    public long getOptUserId() {
        return _optuserid;
    }

    /**
     *  get operator user id
     *
     *  @return user id
     */
    private long get_optuserid() {
        return _optuserid;
    }

    /**
     *  get start time
     *
     *  @return start time
     */
    public java.util.Date getStarttime() {
        return _starttime;
    }

    private java.util.Date get_starttime() {
        return _starttime;
    }

    /**
     *  get endtime
     *
     *  @return endtime
     */
    public java.util.Date getEndtime() {
        return _endtime;
    }

    private java.util.Date get_endtime() {
        return _endtime;
    }


    /**
     *  get _extType
     *
     *  @return _extType
     */
    public String get_extType() {
        return _extType;
    }

    /**
     *  get _extField
     *
     *  @return _extField
     */
    public BEExtensionInfo get_extField() {
        return _extField;
    }
        
    /**
     *  get id
     *
     *  @return id
     */
    public long getId() {
        return id;
    }

    /**
     *  get productId
     *
     *  @return productId
     */
    public long getProductId() {
        return productId;
    }

    /**
     *  get product
     *
     *  @return product
     */
    public org.shaolin.vogerp.productmodel.be.ProductImpl getProduct() {
        return product;
    }

    /**
     *  get priceId
     *
     *  @return priceId
     */
    public long getPriceId() {
        return priceId;
    }

    /**
     *  get pricePackage
     *
     *  @return pricePackage
     */
    public org.shaolin.vogerp.productmodel.be.ProductPriceImpl getPricePackage() {
        return pricePackage;
    }

    /**
     *  get amount
     *
     *  @return amount
     */
    public int getAmount() {
        return amount;
    }

    /**
     *  get unitPrice
     *
     *  @return unitPrice
     */
    public double getUnitPrice() {
        return unitPrice;
    }

    /**
     *  get ajustPriceType
     *
     *  @return ajustPriceType
     */
    public AjustPriceType getAjustPriceType() {
        return ajustPriceType;
    }

    /**
     *  get ajustPriceTypeInt
     *
     *  @return ajustPriceTypeInt
     */
    private int getAjustPriceTypeInt() {
        return ajustPriceTypeInt;
    }

    /**
     *  get ajustPrice
     *
     *  @return ajustPrice
     */
    public double getAjustPrice() {
        return ajustPrice;
    }

    /**
     *  get comment
     *
     *  @return comment
     */
    public java.lang.String getComment() {
        return comment;
    }

    /**
     *  get terms
     *
     *  @return terms
     */
    public OrderTermsType getTerms() {
        return terms;
    }

    /**
     *  get termsInt
     *
     *  @return termsInt
     */
    private int getTermsInt() {
        return termsInt;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    public void setEnabled(boolean enable) {
        _enable = enable;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    private void set_enable(boolean enable) {
        _enable = enable;
    }

    
    /**
     *  set version
     */
    public void setVersion(int version) {
        _version = version;
    }

    private void set_version(int version) {
        _version = version;
    }

    /**
     *  set operator user id
     *  @parameter user id.
     */
    public void setOptUserId(long optUserId) {
        _optuserid = optUserId;
    }

    /**
     *  set operator user id
     *  @parameter user id.
     */
    private void set_optuserid(long optUserId) {
        _optuserid = optUserId;
    }

    /**
     *  set start time
     *  @parameter start time which is the start time of object.
     */
    public void setStarttime(java.util.Date starttime) {
        _starttime = starttime;
    }

    private void set_starttime(java.util.Date starttime) {
        _starttime = starttime;
    }

    /**
     *  set endtime
     *  @parameter endtime which is the end time of object.
     */
    public void setEndtime(java.util.Date endtime) {
        _endtime = endtime;
    }

    private void set_endtime(java.util.Date endtime) {
        _endtime = endtime;
    }

/**
     *  set _extType
     *  @param _extType which is the extension type of be object.
     */
    public void set_extType(java.lang.String _extType) {
        this._extType = _extType;
    }
        
    /**
     *  set id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     *  set productId
     */
    public void setProductId(long productId) {
        this.productId = productId;
    }

    /**
     *  set product
     */
    public void setProduct(org.shaolin.vogerp.productmodel.be.ProductImpl product) {
        this.product = product;
    }

    /**
     *  set priceId
     */
    public void setPriceId(long priceId) {
        this.priceId = priceId;
    }

    /**
     *  set pricePackage
     */
    public void setPricePackage(org.shaolin.vogerp.productmodel.be.ProductPriceImpl pricePackage) {
        this.pricePackage = pricePackage;
    }

    /**
     *  set amount
     */
    public void setAmount(int amount) {
        this.amount = amount;
    }

    /**
     *  set unitPrice
     */
    public void setUnitPrice(double unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     *  set ajustPriceType
     */
    public void setAjustPriceType(AjustPriceType ajustPriceType) {
        this.ajustPriceType = ajustPriceType;
    if (ajustPriceTypeInt != ajustPriceType.getIntValue()) {
            ajustPriceTypeInt = ajustPriceType.getIntValue();
        }
    }

    /**
     *  set int ajustPriceType
     */
    private void setAjustPriceTypeInt(int intValue) {
        this.ajustPriceTypeInt = intValue;
        if (ajustPriceTypeInt != ajustPriceType.getIntValue()) {
            ajustPriceType = (AjustPriceType)ceService.getConstantEntity(AjustPriceType.ENTITY_NAME).getByIntValue(ajustPriceTypeInt);
        }
    }

    /**
     *  set ajustPrice
     */
    public void setAjustPrice(double ajustPrice) {
        this.ajustPrice = ajustPrice;
    }

    /**
     *  set comment
     */
    public void setComment(java.lang.String comment) {
        this.comment = comment;
    }

    /**
     *  set terms
     */
    public void setTerms(OrderTermsType terms) {
        this.terms = terms;
    if (termsInt != terms.getIntValue()) {
            termsInt = terms.getIntValue();
        }
    }

    /**
     *  set int terms
     */
    private void setTermsInt(int intValue) {
        this.termsInt = intValue;
        if (termsInt != terms.getIntValue()) {
            terms = (OrderTermsType)ceService.getConstantEntity(OrderTermsType.ENTITY_NAME).getByIntValue(termsInt);
        }
    }

    
    /**
     * Check different according to primary key.
     */
    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof org.shaolin.vogerp.order.be.OrderItemImpl))
            return false;
        org.shaolin.vogerp.order.be.OrderItemImpl o = (org.shaolin.vogerp.order.be.OrderItemImpl)obj;
        
        boolean result = super.equals(obj);

        boolean eq = true;
        
        return result;
    }

    /**
     * Generate hashCode according to primary key.
     */
    public int hashCode() {
        
        int result = super.hashCode();

        return result;
    }
        
    
     /**
     * Gets the String format of the business entity.
     *
     * @return String the business entity in String format.
     */
    public  String  toString() {
        StringBuffer aBuf = new StringBuffer();
        aBuf.append("org.shaolin.vogerp.order.be.OrderItem");
    
        aBuf.append(" : ");
        
        aBuf.append("enable=").append(_enable).append(", ");
        
        aBuf.append("id");
        aBuf.append("=");
        aBuf.append(id);
        aBuf.append(", ");
        
        aBuf.append("productId");
        aBuf.append("=");
        aBuf.append(productId);
        aBuf.append(", ");
        
        aBuf.append("product");
        aBuf.append("=");
        aBuf.append(product==null? "" : product.toString());
        aBuf.append(", ");
        
        aBuf.append("priceId");
        aBuf.append("=");
        aBuf.append(priceId);
        aBuf.append(", ");
        
        aBuf.append("pricePackage");
        aBuf.append("=");
        aBuf.append(pricePackage==null? "" : pricePackage.toString());
        aBuf.append(", ");
        
        aBuf.append("amount");
        aBuf.append("=");
        aBuf.append(amount);
        aBuf.append(", ");
        
        aBuf.append("unitPrice");
        aBuf.append("=");
        aBuf.append(unitPrice);
        aBuf.append(", ");
        
        aBuf.append("ajustPriceType");
        aBuf.append("=");
        aBuf.append(ajustPriceType);
        aBuf.append(", ");
        
        aBuf.append("ajustPrice");
        aBuf.append("=");
        aBuf.append(ajustPrice);
        aBuf.append(", ");
        
        aBuf.append("comment");
        aBuf.append("=");
        aBuf.append(comment);
        aBuf.append(", ");
        
        aBuf.append("terms");
        aBuf.append("=");
        aBuf.append(terms);
        aBuf.append(", ");
        
        return aBuf.toString();
    }
    
    
     /**
     * Gets list of MemberType.
     *
     * @return List     the list of MemberType.
     */
    public List<MemberType> getMemberList() {
        List<MemberType> memberTypeList = new ArrayList<MemberType>();
        
        MemberType member = null;
        
        org.shaolin.bmdp.datamodel.bediagram.LongType idBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for id
        member = new MemberType();
        member.setName("id");
        member.setDescription("null");
        member.setType(idBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.LongType productIdBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for productId
        member = new MemberType();
        member.setName("productId");
        member.setDescription("null");
        member.setType(productIdBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.BEObjRefType productBEType = new org.shaolin.bmdp.datamodel.bediagram.BEObjRefType();
    
        TargetEntityType productTargetEntity = new TargetEntityType();
        productTargetEntity.setEntityName("org.shaolin.vogerp.productmodel.be.Product");
        productBEType.setTargetEntity(productTargetEntity);
            
        //MemberType Define for product
        member = new MemberType();
        member.setName("product");
        member.setDescription("null");
        member.setType(productBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.LongType priceIdBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for priceId
        member = new MemberType();
        member.setName("priceId");
        member.setDescription("null");
        member.setType(priceIdBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.BEObjRefType pricePackageBEType = new org.shaolin.bmdp.datamodel.bediagram.BEObjRefType();
    
        TargetEntityType pricePackageTargetEntity = new TargetEntityType();
        pricePackageTargetEntity.setEntityName("org.shaolin.vogerp.productmodel.be.ProductPrice");
        pricePackageBEType.setTargetEntity(pricePackageTargetEntity);
            
        //MemberType Define for pricePackage
        member = new MemberType();
        member.setName("pricePackage");
        member.setDescription("null");
        member.setType(pricePackageBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.IntType amountBEType = new org.shaolin.bmdp.datamodel.bediagram.IntType();
    
        //MemberType Define for amount
        member = new MemberType();
        member.setName("amount");
        member.setDescription("null");
        member.setType(amountBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.DoubleType unitPriceBEType = new org.shaolin.bmdp.datamodel.bediagram.DoubleType();
    
        //MemberType Define for unitPrice
        member = new MemberType();
        member.setName("unitPrice");
        member.setDescription("null");
        member.setType(unitPriceBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.CEObjRefType ajustPriceTypeBEType = new org.shaolin.bmdp.datamodel.bediagram.CEObjRefType();
    
        TargetEntityType ajustPriceTypeTargetEntity = new TargetEntityType();
        ajustPriceTypeBEType.setTargetEntity(ajustPriceTypeTargetEntity);
        ajustPriceTypeTargetEntity.setEntityName("org.shaolin.vogerp.order.ce.AjustPriceType");
            
        //MemberType Define for ajustPriceType
        member = new MemberType();
        member.setName("ajustPriceType");
        member.setDescription("null");
        member.setType(ajustPriceTypeBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.DoubleType ajustPriceBEType = new org.shaolin.bmdp.datamodel.bediagram.DoubleType();
    
        //MemberType Define for ajustPrice
        member = new MemberType();
        member.setName("ajustPrice");
        member.setDescription("null");
        member.setType(ajustPriceBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType commentBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for comment
        member = new MemberType();
        member.setName("comment");
        member.setDescription("null");
        member.setType(commentBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.CEObjRefType termsBEType = new org.shaolin.bmdp.datamodel.bediagram.CEObjRefType();
    
        TargetEntityType termsTargetEntity = new TargetEntityType();
        termsBEType.setTargetEntity(termsTargetEntity);
        termsTargetEntity.setEntityName("org.shaolin.vogerp.order.ce.OrderTermsType");
            
        //MemberType Define for terms
        member = new MemberType();
        member.setName("terms");
        member.setDescription("null");
        member.setType(termsBEType);
        memberTypeList.add(member);
            
        return memberTypeList;
    }
    
    public IOrderItem createEntity ()
    {
        return new OrderItemImpl();
    }
    
}

        

