/*
 *
 * This file is automatically generated on Thu Jul 23 13:15:09 CST 2015
 */

    
package org.shaolin.vogerp.commonmodel.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;



/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public class AddressInfoImpl  implements org.shaolin.vogerp.commonmodel.be.IAddressInfo
{
    private static final long serialVersionUID = 0x90B1123CE87B50FFL;

    private final IConstantService ceService = AppContext.get().getConstantService();

    protected String getBusinessEntityName()
    {
        return "org.shaolin.vogerp.commonmodel.be.AddressInfo";
    }

    public AddressInfoImpl()
    {
        
        _extField = new BEExtensionInfo();
        
    }
    
    
        /**
     * Enable record
     */
    private boolean _enable = true;


    /**
     *  BEExtension _extType
     */
    protected String _extType;

    /**
     *  BEExtension _extField
     */
    protected BEExtensionInfo _extField;
        
   /**
     *  help is not available
     */    
    protected long id;
    
   /**
     *  help is not available
     */    
    protected java.lang.String country;
    
   /**
     *  help is not available
     */    
    protected java.lang.String city;
    
   /**
     *  help is not available
     */    
    protected java.lang.String street;
    
   /**
     *  help is not available
     */    
    protected java.lang.String block;
    
   /**
     *  help is not available
     */    
    protected java.lang.String zipcode;
    
   /**
     *  help is not available
     */    
    protected java.lang.String description;
    
        /**
     *  Is enable
     *
     *  @return boolean
     */
    public boolean isEnabled() {
        return _enable;
    }
            /**
     *  Is enable
     *
     *  @return boolean
     */
    private boolean get_enable() {
        return _enable;
    }
        
    /**
     *  get _extType
     *
     *  @return _extType
     */
    public String get_extType() {
        return _extType;
    }

    /**
     *  get _extField
     *
     *  @return _extField
     */
    public BEExtensionInfo get_extField() {
        return _extField;
    }
        
    /**
     *  get id
     *
     *  @return id
     */
    public long getId() {
        return id;
    }

    /**
     *  get country
     *
     *  @return country
     */
    public java.lang.String getCountry() {
        return country;
    }

    /**
     *  get city
     *
     *  @return city
     */
    public java.lang.String getCity() {
        return city;
    }

    /**
     *  get street
     *
     *  @return street
     */
    public java.lang.String getStreet() {
        return street;
    }

    /**
     *  get block
     *
     *  @return block
     */
    public java.lang.String getBlock() {
        return block;
    }

    /**
     *  get zipcode
     *
     *  @return zipcode
     */
    public java.lang.String getZipcode() {
        return zipcode;
    }

    /**
     *  get description
     *
     *  @return description
     */
    public java.lang.String getDescription() {
        return description;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    public void setEnabled(boolean enable) {
        _enable = enable;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    private void set_enable(boolean enable) {
        _enable = enable;
    }

    /**
     *  set _extType
     *  @param _extType which is the extension type of be object.
     */
    public void set_extType(java.lang.String _extType) {
        this._extType = _extType;
    }
        
    /**
     *  set id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     *  set country
     */
    public void setCountry(java.lang.String country) {
        this.country = country;
    }

    /**
     *  set city
     */
    public void setCity(java.lang.String city) {
        this.city = city;
    }

    /**
     *  set street
     */
    public void setStreet(java.lang.String street) {
        this.street = street;
    }

    /**
     *  set block
     */
    public void setBlock(java.lang.String block) {
        this.block = block;
    }

    /**
     *  set zipcode
     */
    public void setZipcode(java.lang.String zipcode) {
        this.zipcode = zipcode;
    }

    /**
     *  set description
     */
    public void setDescription(java.lang.String description) {
        this.description = description;
    }

    
    /**
     * Check different according to primary key.
     */
    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof org.shaolin.vogerp.commonmodel.be.AddressInfoImpl))
            return false;
        org.shaolin.vogerp.commonmodel.be.AddressInfoImpl o = (org.shaolin.vogerp.commonmodel.be.AddressInfoImpl)obj;
        
        boolean result = super.equals(obj);

        boolean eq = true;
        
        return result;
    }

    /**
     * Generate hashCode according to primary key.
     */
    public int hashCode() {
        
        int result = super.hashCode();

        return result;
    }
        
    
     /**
     * Gets the String format of the business entity.
     *
     * @return String the business entity in String format.
     */
    public  String  toString() {
        StringBuffer aBuf = new StringBuffer();
        aBuf.append("org.shaolin.vogerp.commonmodel.be.AddressInfo");
    
        aBuf.append(" : ");
        
        aBuf.append("enable=").append(_enable).append(", ");
        
        aBuf.append("id");
        aBuf.append("=");
        aBuf.append(id);
        aBuf.append(", ");
        
        aBuf.append("country");
        aBuf.append("=");
        aBuf.append(country);
        aBuf.append(", ");
        
        aBuf.append("city");
        aBuf.append("=");
        aBuf.append(city);
        aBuf.append(", ");
        
        aBuf.append("street");
        aBuf.append("=");
        aBuf.append(street);
        aBuf.append(", ");
        
        aBuf.append("block");
        aBuf.append("=");
        aBuf.append(block);
        aBuf.append(", ");
        
        aBuf.append("zipcode");
        aBuf.append("=");
        aBuf.append(zipcode);
        aBuf.append(", ");
        
        aBuf.append("description");
        aBuf.append("=");
        aBuf.append(description);
        aBuf.append(", ");
        
        return aBuf.toString();
    }
    
    
     /**
     * Gets list of MemberType.
     *
     * @return List     the list of MemberType.
     */
    public List<MemberType> getMemberList() {
        List<MemberType> memberTypeList = new ArrayList<MemberType>();
        
        MemberType member = null;
        
        org.shaolin.bmdp.datamodel.bediagram.LongType idBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for id
        member = new MemberType();
        member.setName("id");
        member.setDescription("null");
        member.setType(idBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType countryBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for country
        member = new MemberType();
        member.setName("country");
        member.setDescription("null");
        member.setType(countryBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType cityBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for city
        member = new MemberType();
        member.setName("city");
        member.setDescription("null");
        member.setType(cityBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType streetBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for street
        member = new MemberType();
        member.setName("street");
        member.setDescription("null");
        member.setType(streetBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType blockBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for block
        member = new MemberType();
        member.setName("block");
        member.setDescription("null");
        member.setType(blockBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType zipcodeBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for zipcode
        member = new MemberType();
        member.setName("zipcode");
        member.setDescription("null");
        member.setType(zipcodeBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType descriptionBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for description
        member = new MemberType();
        member.setName("description");
        member.setDescription("null");
        member.setType(descriptionBEType);
        memberTypeList.add(member);
            
        return memberTypeList;
    }
    
    public IAddressInfo createEntity ()
    {
        return new AddressInfoImpl();
    }
    
}

        

