/*
 *
 * This file is automatically generated on Fri May 08 18:48:41 CST 2015
 */

    
package org.shaolin.vogerp.commonmodel.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;



/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public class AdminConsoleHeadInfoImpl  implements org.shaolin.vogerp.commonmodel.be.IAdminConsoleHeadInfo
{
    private static final long serialVersionUID = 0x90B1123CE87B50FFL;

    private final IConstantService ceService = AppContext.get().getConstantService();

    protected String getBusinessEntityName()
    {
        return "org.shaolin.vogerp.commonmodel.be.AdminConsoleHeadInfo";
    }

    public AdminConsoleHeadInfoImpl()
    {
        
        _extField = new BEExtensionInfo();
        
    }
    
    
    
    /**
     *  BEExtension _extType
     */
    protected String _extType;

    /**
     *  BEExtension _extField
     */
    protected BEExtensionInfo _extField;
        
   /**
     *  help is not available
     */    
    protected long userId;
    
   /**
     *  help is not available
     */    
    protected long userName;
    
   /**
     *  help is not available
     */    
    protected java.lang.String userLanguage;
    
   /**
     *  help is not available
     */    
    protected java.util.Date roleName;
    
   /**
     *  help is not available
     */    
    protected java.util.Date loginTime;
    
    
    /**
     *  get _extType
     *
     *  @return _extType
     */
    public String get_extType() {
        return _extType;
    }

    /**
     *  get _extField
     *
     *  @return _extField
     */
    public BEExtensionInfo get_extField() {
        return _extField;
    }
        
    /**
     *  get userId
     *
     *  @return userId
     */
    public long getUserId() {
        return userId;
    }

    /**
     *  get userName
     *
     *  @return userName
     */
    public long getUserName() {
        return userName;
    }

    /**
     *  get userLanguage
     *
     *  @return userLanguage
     */
    public java.lang.String getUserLanguage() {
        return userLanguage;
    }

    /**
     *  get roleName
     *
     *  @return roleName
     */
    public java.util.Date getRoleName() {
        return roleName;
    }

    /**
     *  get loginTime
     *
     *  @return loginTime
     */
    public java.util.Date getLoginTime() {
        return loginTime;
    }

    /**
     *  set _extType
     *  @param _extType which is the extension type of be object.
     */
    public void set_extType(java.lang.String _extType) {
        this._extType = _extType;
    }
        
    /**
     *  set userId
     */
    public void setUserId(long userId) {
        this.userId = userId;
    }

    /**
     *  set userName
     */
    public void setUserName(long userName) {
        this.userName = userName;
    }

    /**
     *  set userLanguage
     */
    public void setUserLanguage(java.lang.String userLanguage) {
        this.userLanguage = userLanguage;
    }

    /**
     *  set roleName
     */
    public void setRoleName(java.util.Date roleName) {
        this.roleName = roleName;
    }

    /**
     *  set loginTime
     */
    public void setLoginTime(java.util.Date loginTime) {
        this.loginTime = loginTime;
    }

    
    /**
     * Check different according to primary key.
     */
    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof org.shaolin.vogerp.commonmodel.be.AdminConsoleHeadInfoImpl))
            return false;
        org.shaolin.vogerp.commonmodel.be.AdminConsoleHeadInfoImpl o = (org.shaolin.vogerp.commonmodel.be.AdminConsoleHeadInfoImpl)obj;
        
        boolean result = super.equals(obj);

        boolean eq = true;
        
        return result;
    }

    /**
     * Generate hashCode according to primary key.
     */
    public int hashCode() {
        
        int result = super.hashCode();

        return result;
    }
        
    
     /**
     * Gets the String format of the business entity.
     *
     * @return String the business entity in String format.
     */
    public  String  toString() {
        StringBuffer aBuf = new StringBuffer();
        aBuf.append("org.shaolin.vogerp.commonmodel.be.AdminConsoleHeadInfo");
    
        aBuf.append(" : ");
        
        aBuf.append("userId");
        aBuf.append("=");
        aBuf.append(userId);
        aBuf.append(", ");
        
        aBuf.append("userName");
        aBuf.append("=");
        aBuf.append(userName);
        aBuf.append(", ");
        
        aBuf.append("userLanguage");
        aBuf.append("=");
        aBuf.append(userLanguage);
        aBuf.append(", ");
        
        aBuf.append("roleName");
        aBuf.append("=");
        aBuf.append(roleName);
        aBuf.append(", ");
        
        aBuf.append("loginTime");
        aBuf.append("=");
        aBuf.append(loginTime);
        aBuf.append(", ");
        
        return aBuf.toString();
    }
    
    
     /**
     * Gets list of MemberType.
     *
     * @return List     the list of MemberType.
     */
    public List<MemberType> getMemberList() {
        List<MemberType> memberTypeList = new ArrayList<MemberType>();
        
        MemberType member = null;
        
        org.shaolin.bmdp.datamodel.bediagram.LongType userIdBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for userId
        member = new MemberType();
        member.setName("userId");
        member.setDescription("null");
        member.setType(userIdBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.LongType userNameBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for userName
        member = new MemberType();
        member.setName("userName");
        member.setDescription("null");
        member.setType(userNameBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType userLanguageBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for userLanguage
        member = new MemberType();
        member.setName("userLanguage");
        member.setDescription("null");
        member.setType(userLanguageBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.DateTimeType roleNameBEType = new org.shaolin.bmdp.datamodel.bediagram.DateTimeType();
    
        //MemberType Define for roleName
        member = new MemberType();
        member.setName("roleName");
        member.setDescription("null");
        member.setType(roleNameBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.DateTimeType loginTimeBEType = new org.shaolin.bmdp.datamodel.bediagram.DateTimeType();
    
        //MemberType Define for loginTime
        member = new MemberType();
        member.setName("loginTime");
        member.setDescription("null");
        member.setType(loginTimeBEType);
        memberTypeList.add(member);
            
        return memberTypeList;
    }
    
    public IAdminConsoleHeadInfo createEntity ()
    {
        return new AdminConsoleHeadInfoImpl();
    }
    
}

        

