/*
 *
 * This file is automatically generated on Thu Jul 23 13:15:09 CST 2015
 */

    
package org.shaolin.vogerp.commonmodel.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;



/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public class BEPermissionImpl 
    extends PartyPermissionImpl
         implements org.shaolin.vogerp.commonmodel.be.IBEPermission
{
    private static final long serialVersionUID = 0x90B1123CE87B50FFL;

    private final IConstantService ceService = AppContext.get().getConstantService();

    protected String getBusinessEntityName()
    {
        return "org.shaolin.vogerp.commonmodel.be.BEPermission";
    }

    public BEPermissionImpl()
    {
        
        _extField = new BEExtensionInfo();
        
    }
    
    
        /**
     * Enable record
     */
    private boolean _enable = true;


    /**
     *  BEExtension _extType
     */
    protected String _extType;

    /**
     *  BEExtension _extField
     */
    protected BEExtensionInfo _extField;
        
   /**
     *  help is not available
     */    
    protected java.lang.String beName;
    
   /**
     *  help is not available
     */    
    protected java.lang.String field;
    
        /**
     *  Is enable
     *
     *  @return boolean
     */
    public boolean isEnabled() {
        return _enable;
    }
            /**
     *  Is enable
     *
     *  @return boolean
     */
    private boolean get_enable() {
        return _enable;
    }
        
    /**
     *  get _extType
     *
     *  @return _extType
     */
    public String get_extType() {
        return _extType;
    }

    /**
     *  get _extField
     *
     *  @return _extField
     */
    public BEExtensionInfo get_extField() {
        return _extField;
    }
        
    /**
     *  get beName
     *
     *  @return beName
     */
    public java.lang.String getBeName() {
        return beName;
    }

    /**
     *  get field
     *
     *  @return field
     */
    public java.lang.String getField() {
        return field;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    public void setEnabled(boolean enable) {
        _enable = enable;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    private void set_enable(boolean enable) {
        _enable = enable;
    }

    /**
     *  set _extType
     *  @param _extType which is the extension type of be object.
     */
    public void set_extType(java.lang.String _extType) {
        this._extType = _extType;
    }
        
    /**
     *  set beName
     */
    public void setBeName(java.lang.String beName) {
        this.beName = beName;
    }

    /**
     *  set field
     */
    public void setField(java.lang.String field) {
        this.field = field;
    }

    
    /**
     * Check different according to primary key.
     */
    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof org.shaolin.vogerp.commonmodel.be.BEPermissionImpl))
            return false;
        org.shaolin.vogerp.commonmodel.be.BEPermissionImpl o = (org.shaolin.vogerp.commonmodel.be.BEPermissionImpl)obj;
        
        boolean result = super.equals(obj);

        boolean eq = true;
        
        return result;
    }

    /**
     * Generate hashCode according to primary key.
     */
    public int hashCode() {
        
        int result = super.hashCode();

        return result;
    }
        
    
     /**
     * Gets the String format of the business entity.
     *
     * @return String the business entity in String format.
     */
    public  String  toString() {
        StringBuffer aBuf = new StringBuffer();
        aBuf.append("org.shaolin.vogerp.commonmodel.be.BEPermission");
    
        aBuf.append(" extends ");
        aBuf.append(super.toString());
        
        aBuf.append("enable=").append(_enable).append(", ");
        
        aBuf.append("beName");
        aBuf.append("=");
        aBuf.append(beName);
        aBuf.append(", ");
        
        aBuf.append("field");
        aBuf.append("=");
        aBuf.append(field);
        aBuf.append(", ");
        
        return aBuf.toString();
    }
    
    
     /**
     * Gets list of MemberType.
     *
     * @return List     the list of MemberType.
     */
    public List<MemberType> getMemberList() {
        List<MemberType> memberTypeList = new ArrayList<MemberType>();
        
        List<MemberType> parentList = super.getMemberList();
        for(int i=0, n=parentList.size(); i<n; i++)
            memberTypeList.add(parentList.get(i));
            
        MemberType member = null;
        
        org.shaolin.bmdp.datamodel.bediagram.StringType beNameBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for beName
        member = new MemberType();
        member.setName("beName");
        member.setDescription("null");
        member.setType(beNameBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType fieldBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for field
        member = new MemberType();
        member.setName("field");
        member.setDescription("null");
        member.setType(fieldBEType);
        memberTypeList.add(member);
            
        return memberTypeList;
    }
    
    public IBEPermission createEntity ()
    {
        return new BEPermissionImpl();
    }
    
}

        

