/*
 *
 * This file is automatically generated on Fri May 08 18:48:41 CST 2015
 */

    
package org.shaolin.vogerp.commonmodel.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;



/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public interface IAdminConsoleHeadInfo 
    extends IBusinessEntity, IExtensibleEntity
{
    public final static String ENTITY_NAME = "org.shaolin.vogerp.commonmodel.be.AdminConsoleHeadInfo";
    
 
    /**
     *  get userId
     *
     *  @return userId
     */
    public long getUserId();

    /**
     *  get userName
     *
     *  @return userName
     */
    public long getUserName();

    /**
     *  get userLanguage
     *
     *  @return userLanguage
     */
    public java.lang.String getUserLanguage();

    /**
     *  get roleName
     *
     *  @return roleName
     */
    public java.util.Date getRoleName();

    /**
     *  get loginTime
     *
     *  @return loginTime
     */
    public java.util.Date getLoginTime();

    /**
     *  set userId
     */
    public void setUserId(long userId);

    /**
     *  set userName
     */
    public void setUserName(long userName);

    /**
     *  set userLanguage
     */
    public void setUserLanguage(java.lang.String userLanguage);

    /**
     *  set roleName
     */
    public void setRoleName(java.util.Date roleName);

    /**
     *  set loginTime
     */
    public void setLoginTime(java.util.Date loginTime);


}

        