/*
 *
 * This file is automatically generated on Thu Jul 23 13:15:10 CST 2015
 */

    
package org.shaolin.vogerp.commonmodel.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;



/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public interface ICEEntityInfo 
    extends IPersistentEntity, IExtensibleEntity
{
    public final static String ENTITY_NAME = "org.shaolin.vogerp.commonmodel.be.CEEntityInfo";
    
 
    /**
     *  get id
     *
     *  @return id
     */
    public long getId();

    /**
     *  get ceName
     *
     *  @return ceName
     */
    public java.lang.String getCeName();

    /**
     *  get i18nKey
     *
     *  @return i18nKey
     */
    public java.lang.String getI18nKey();

    /**
     *  get description
     *
     *  @return description
     */
    public java.lang.String getDescription();

    /**
     *  get icon
     *
     *  @return icon
     */
    public java.lang.String getIcon();

    /**
     *  set id
     */
    public void setId(long id);

    /**
     *  set ceName
     */
    public void setCeName(java.lang.String ceName);

    /**
     *  set i18nKey
     */
    public void setI18nKey(java.lang.String i18nKey);

    /**
     *  set description
     */
    public void setDescription(java.lang.String description);

    /**
     *  set icon
     */
    public void setIcon(java.lang.String icon);


}

        