/*
 *
 * This file is automatically generated on Thu Jul 23 13:15:09 CST 2015
 */

    
package org.shaolin.vogerp.commonmodel.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;



/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public interface IContactInfo 
    extends IPersistentEntity, IExtensibleEntity
{
    public final static String ENTITY_NAME = "org.shaolin.vogerp.commonmodel.be.ContactInfo";
    
 
    /**
     *  get id
     *
     *  @return id
     */
    public long getId();

    /**
     *  get telephone
     *
     *  @return telephone
     */
    public java.lang.String getTelephone();

    /**
     *  get mobile
     *
     *  @return mobile
     */
    public java.lang.String getMobile();

    /**
     *  get email
     *
     *  @return email
     */
    public java.lang.String getEmail();

    /**
     *  get homepage
     *
     *  @return homepage
     */
    public java.lang.String getHomepage();

    /**
     *  get remark
     *
     *  @return remark
     */
    public java.lang.String getRemark();

    /**
     *  set id
     */
    public void setId(long id);

    /**
     *  set telephone
     */
    public void setTelephone(java.lang.String telephone);

    /**
     *  set mobile
     */
    public void setMobile(java.lang.String mobile);

    /**
     *  set email
     */
    public void setEmail(java.lang.String email);

    /**
     *  set homepage
     */
    public void setHomepage(java.lang.String homepage);

    /**
     *  set remark
     */
    public void setRemark(java.lang.String remark);


}

        