/*
 *
 * This file is automatically generated on Thu Jul 23 13:15:10 CST 2015
 */

    
package org.shaolin.vogerp.commonmodel.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;



/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public interface IModuleGroup 
    extends IPersistentEntity, IExtensibleEntity
{
    public final static String ENTITY_NAME = "org.shaolin.vogerp.commonmodel.be.ModuleGroup";
    
 
    /**
     *  get groupId
     *
     *  @return groupId
     */
    public long getGroupId();

    /**
     *  get parentId
     *
     *  @return parentId
     */
    public long getParentId();

    /**
     *  get name
     *
     *  @return name
     */
    public java.lang.String getName();

    /**
     *  get description
     *
     *  @return description
     */
    public java.lang.String getDescription();

    /**
     *  get smallIcon
     *
     *  @return smallIcon
     */
    public java.lang.String getSmallIcon();

    /**
     *  get bigIcon
     *
     *  @return bigIcon
     */
    public java.lang.String getBigIcon();

    /**
     *  get accessURL
     *
     *  @return accessURL
     */
    public java.lang.String getAccessURL();

    /**
     *  set groupId
     */
    public void setGroupId(long groupId);

    /**
     *  set parentId
     */
    public void setParentId(long parentId);

    /**
     *  set name
     */
    public void setName(java.lang.String name);

    /**
     *  set description
     */
    public void setDescription(java.lang.String description);

    /**
     *  set smallIcon
     */
    public void setSmallIcon(java.lang.String smallIcon);

    /**
     *  set bigIcon
     */
    public void setBigIcon(java.lang.String bigIcon);

    /**
     *  set accessURL
     */
    public void setAccessURL(java.lang.String accessURL);


}

        