/*
 *
 * This file is automatically generated on Thu Jul 23 13:15:09 CST 2015
 */

    
package org.shaolin.vogerp.commonmodel.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;

import org.shaolin.vogerp.commonmodel.ce.*;


/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public interface IOrganizationContract 
    extends IPersistentEntity, IExtensibleEntity
{
    public final static String ENTITY_NAME = "org.shaolin.vogerp.commonmodel.be.OrganizationContract";
    
 
    /**
     *  get id
     *
     *  @return id
     */
    public long getId();

    /**
     *  get orgId
     *
     *  @return orgId
     */
    public long getOrgId();

    /**
     *  get type
     *
     *  @return type
     */
    public ContractType getType();

    /**
     *  get terms
     *
     *  @return terms
     */
    public java.lang.String getTerms();

    /**
     *  get expirationDate
     *
     *  @return expirationDate
     */
    public java.util.Date getExpirationDate();

    /**
     *  set id
     */
    public void setId(long id);

    /**
     *  set orgId
     */
    public void setOrgId(long orgId);

    /**
     *  set type
     */
    public void setType(ContractType type);

    /**
     *  set terms
     */
    public void setTerms(java.lang.String terms);

    /**
     *  set expirationDate
     */
    public void setExpirationDate(java.util.Date expirationDate);


}

        