/*
 *
 * This file is automatically generated on Thu Jul 23 13:15:09 CST 2015
 */

    
package org.shaolin.vogerp.commonmodel.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;

import org.shaolin.vogerp.commonmodel.ce.*;


/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public interface IPartyPermission 
    extends IBusinessEntity, IExtensibleEntity
{
    public final static String ENTITY_NAME = "org.shaolin.vogerp.commonmodel.be.PartyPermission";
    
 
    /**
     *  get id
     *
     *  @return id
     */
    public long getId();

    /**
     *  get partyType
     *
     *  @return partyType
     */
    public java.lang.String getPartyType();

    /**
     *  get type
     *
     *  @return type
     */
    public PermissionType getType();

    /**
     *  set id
     */
    public void setId(long id);

    /**
     *  set partyType
     */
    public void setPartyType(java.lang.String partyType);

    /**
     *  set type
     */
    public void setType(PermissionType type);


}

        