/*
 *
 * This file is automatically generated on Thu Jul 23 13:15:09 CST 2015
 */

    
package org.shaolin.vogerp.commonmodel.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;

import org.shaolin.vogerp.commonmodel.ce.*;


/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public interface IPartyEvent 
    extends IPersistentEntity, IExtensibleEntity
{
    public final static String ENTITY_NAME = "org.shaolin.vogerp.commonmodel.be.PartyEvent";
    
 
    /**
     *  get id
     *
     *  @return id
     */
    public long getId();

    /**
     *  get srcPartyId
     *
     *  @return srcPartyId
     */
    public long getSrcPartyId();

    /**
     *  get tarPartyId
     *
     *  @return tarPartyId
     */
    public long getTarPartyId();

    /**
     *  get pageInfo
     *
     *  @return pageInfo
     */
    public java.lang.String getPageInfo();

    /**
     *  get eventRecord
     *
     *  @return eventRecord
     */
    public java.lang.String getEventRecord();

    /**
     *  get eventType
     *
     *  @return eventType
     */
    public PartyEventType getEventType();

    /**
     *  get eventState
     *
     *  @return eventState
     */
    public PartyEventStatusType getEventState();

    /**
     *  set id
     */
    public void setId(long id);

    /**
     *  set srcPartyId
     */
    public void setSrcPartyId(long srcPartyId);

    /**
     *  set tarPartyId
     */
    public void setTarPartyId(long tarPartyId);

    /**
     *  set pageInfo
     */
    public void setPageInfo(java.lang.String pageInfo);

    /**
     *  set eventRecord
     */
    public void setEventRecord(java.lang.String eventRecord);

    /**
     *  set eventType
     */
    public void setEventType(PartyEventType eventType);

    /**
     *  set eventState
     */
    public void setEventState(PartyEventStatusType eventState);


}

        