/*
 *
 * This file is automatically generated on Thu Jul 23 13:15:09 CST 2015
 */

    
package org.shaolin.vogerp.commonmodel.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;

import org.shaolin.vogerp.commonmodel.ce.*;


/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public interface IPersonalInfo 
    extends IPersistentEntity, org.shaolin.vogerp.commonmodel.be.IParty, IExtensibleEntity
{
    public final static String ENTITY_NAME = "org.shaolin.vogerp.commonmodel.be.PersonalInfo";
    
 
    /**
     *  get firstName
     *
     *  @return firstName
     */
    public java.lang.String getFirstName();

    /**
     *  get lastName
     *
     *  @return lastName
     */
    public java.lang.String getLastName();

    /**
     *  get gender
     *
     *  @return gender
     */
    public Gender getGender();

    /**
     *  get married
     *
     *  @return married
     */
    public boolean getMarried();

    /**
     *  get identityCardId
     *
     *  @return identityCardId
     */
    public java.lang.String getIdentityCardId();

    /**
     *  get discription
     *
     *  @return discription
     */
    public java.lang.String getDiscription();

    /**
     *  get birthday
     *
     *  @return birthday
     */
    public java.util.Date getBirthday();

    /**
     *  get birthdayStart
     *
     *  @return birthdayStart
     */
    public java.util.Date getBirthdayStart();

    /**
     *  get birthdayEnd
     *
     *  @return birthdayEnd
     */
    public java.util.Date getBirthdayEnd();

    /**
     *  get language
     *
     *  @return language
     */
    public LanguageType getLanguage();

    /**
     *  get education
     *
     *  @return education
     */
    public EducationLevel getEducation();

    /**
     *  get major
     *
     *  @return major
     */
    public java.lang.String getMajor();

    /**
     *  get addresses
     *
     *  @return addresses
     */
    public java.util.List<IAddressInfo> getAddresses();

    /**
     *  get contacts
     *
     *  @return contacts
     */
    public java.util.List<IContactInfo> getContacts();

    /**
     *  get comment
     *
     *  @return comment
     */
    public java.lang.String getComment();

    /**
     *  set firstName
     */
    public void setFirstName(java.lang.String firstName);

    /**
     *  set lastName
     */
    public void setLastName(java.lang.String lastName);

    /**
     *  set gender
     */
    public void setGender(Gender gender);

    /**
     *  set married
     */
    public void setMarried(boolean married);

    /**
     *  set identityCardId
     */
    public void setIdentityCardId(java.lang.String identityCardId);

    /**
     *  set discription
     */
    public void setDiscription(java.lang.String discription);

    /**
     *  set birthday
     */
    public void setBirthday(java.util.Date birthday);

    /**
     *  set birthdayStart
     */
    public void setBirthdayStart(java.util.Date birthdayStart);

    /**
     *  set birthdayEnd
     */
    public void setBirthdayEnd(java.util.Date birthdayEnd);

    /**
     *  set language
     */
    public void setLanguage(LanguageType language);

    /**
     *  set education
     */
    public void setEducation(EducationLevel education);

    /**
     *  set major
     */
    public void setMajor(java.lang.String major);

    /**
     *  set addresses
     */
    public void setAddresses(java.util.List<IAddressInfo> addresses);

    /**
     *  set contacts
     */
    public void setContacts(java.util.List<IContactInfo> contacts);

    /**
     *  set comment
     */
    public void setComment(java.lang.String comment);


}

        