/*
 *
 * This file is automatically generated on Thu Jul 23 13:15:10 CST 2015
 */

    
package org.shaolin.vogerp.commonmodel.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;



/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public interface IUIDyanimcPageLink 
    extends IPersistentEntity, IExtensibleEntity
{
    public final static String ENTITY_NAME = "org.shaolin.vogerp.commonmodel.be.UIDyanimcPageLink";
    
 
    /**
     *  get id
     *
     *  @return id
     */
    public long getId();

    /**
     *  get srcUIName
     *
     *  @return srcUIName
     */
    public java.lang.String getSrcUIName();

    /**
     *  get srcUIPanel
     *
     *  @return srcUIPanel
     */
    public java.lang.String getSrcUIPanel();

    /**
     *  get srcUIWidget
     *
     *  @return srcUIWidget
     */
    public java.lang.String getSrcUIWidget();

    /**
     *  get linkComment
     *
     *  @return linkComment
     */
    public java.lang.String getLinkComment();

    /**
     *  get tarUIName
     *
     *  @return tarUIName
     */
    public java.lang.String getTarUIName();

    /**
     *  get tarUITab
     *
     *  @return tarUITab
     */
    public java.lang.String getTarUITab();

    /**
     *  get tarUIArchor
     *
     *  @return tarUIArchor
     */
    public java.lang.String getTarUIArchor();

    /**
     *  set id
     */
    public void setId(long id);

    /**
     *  set srcUIName
     */
    public void setSrcUIName(java.lang.String srcUIName);

    /**
     *  set srcUIPanel
     */
    public void setSrcUIPanel(java.lang.String srcUIPanel);

    /**
     *  set srcUIWidget
     */
    public void setSrcUIWidget(java.lang.String srcUIWidget);

    /**
     *  set linkComment
     */
    public void setLinkComment(java.lang.String linkComment);

    /**
     *  set tarUIName
     */
    public void setTarUIName(java.lang.String tarUIName);

    /**
     *  set tarUITab
     */
    public void setTarUITab(java.lang.String tarUITab);

    /**
     *  set tarUIArchor
     */
    public void setTarUIArchor(java.lang.String tarUIArchor);


}

        