/*
 *
 * This file is automatically generated on Thu Jul 23 13:15:09 CST 2015
 */

    
package org.shaolin.vogerp.commonmodel.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;

import org.shaolin.vogerp.commonmodel.ce.*;


/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public class PartyEventImpl  implements org.shaolin.vogerp.commonmodel.be.IPartyEvent
{
    private static final long serialVersionUID = 0x90B1123CE87B50FFL;

    private final IConstantService ceService = AppContext.get().getConstantService();

    protected String getBusinessEntityName()
    {
        return "org.shaolin.vogerp.commonmodel.be.PartyEvent";
    }

    public PartyEventImpl()
    {
        
        _extField = new BEExtensionInfo();
        
    }
    
    
        /**
     * Enable record
     */
    private boolean _enable = true;


    /**
     * History version
     */
    protected int _version = 0;

    /**
     * History starttime
     */
    private java.util.Date _starttime = new java.util.Date();

    /**
     * History endtime
     */
    private java.util.Date _endtime = null;

    /**
     * History _optuserid
     */
    private long _optuserid = 0L;


    /**
     *  BEExtension _extType
     */
    protected String _extType;

    /**
     *  BEExtension _extField
     */
    protected BEExtensionInfo _extField;
        
   /**
     *  help is not available
     */    
    protected long id;
    
   /**
     *  help is not available
     */    
    protected long srcPartyId;
    
   /**
     *  help is not available
     */    
    protected long tarPartyId;
    
   /**
     *  help is not available
     */    
    protected java.lang.String pageInfo;
    
   /**
     *  help is not available
     */    
    protected java.lang.String eventRecord;
    
   /**
     *  help is not available
     */    
    protected PartyEventType eventType = PartyEventType.NOT_SPECIFIED;
    
    protected int eventTypeInt = PartyEventType.NOT_SPECIFIED.getIntValue();
    
   /**
     *  help is not available
     */    
    protected PartyEventStatusType eventState = PartyEventStatusType.NOT_SPECIFIED;
    
    protected int eventStateInt = PartyEventStatusType.NOT_SPECIFIED.getIntValue();
    
        /**
     *  Is enable
     *
     *  @return boolean
     */
    public boolean isEnabled() {
        return _enable;
    }
            /**
     *  Is enable
     *
     *  @return boolean
     */
    private boolean get_enable() {
        return _enable;
    }
        
    /**
     *  get version
     *
     *  @return version
     */
    public int getVersion() {
        return _version;
    }

    private int get_version() {
        return _version;
    }

    /**
     *  get operator user id
     *
     *  @return user id
     */
    public long getOptUserId() {
        return _optuserid;
    }

    /**
     *  get operator user id
     *
     *  @return user id
     */
    private long get_optuserid() {
        return _optuserid;
    }

    /**
     *  get start time
     *
     *  @return start time
     */
    public java.util.Date getStarttime() {
        return _starttime;
    }

    private java.util.Date get_starttime() {
        return _starttime;
    }

    /**
     *  get endtime
     *
     *  @return endtime
     */
    public java.util.Date getEndtime() {
        return _endtime;
    }

    private java.util.Date get_endtime() {
        return _endtime;
    }


    /**
     *  get _extType
     *
     *  @return _extType
     */
    public String get_extType() {
        return _extType;
    }

    /**
     *  get _extField
     *
     *  @return _extField
     */
    public BEExtensionInfo get_extField() {
        return _extField;
    }
        
    /**
     *  get id
     *
     *  @return id
     */
    public long getId() {
        return id;
    }

    /**
     *  get srcPartyId
     *
     *  @return srcPartyId
     */
    public long getSrcPartyId() {
        return srcPartyId;
    }

    /**
     *  get tarPartyId
     *
     *  @return tarPartyId
     */
    public long getTarPartyId() {
        return tarPartyId;
    }

    /**
     *  get pageInfo
     *
     *  @return pageInfo
     */
    public java.lang.String getPageInfo() {
        return pageInfo;
    }

    /**
     *  get eventRecord
     *
     *  @return eventRecord
     */
    public java.lang.String getEventRecord() {
        return eventRecord;
    }

    /**
     *  get eventType
     *
     *  @return eventType
     */
    public PartyEventType getEventType() {
        return eventType;
    }

    /**
     *  get eventTypeInt
     *
     *  @return eventTypeInt
     */
    private int getEventTypeInt() {
        return eventTypeInt;
    }

    /**
     *  get eventState
     *
     *  @return eventState
     */
    public PartyEventStatusType getEventState() {
        return eventState;
    }

    /**
     *  get eventStateInt
     *
     *  @return eventStateInt
     */
    private int getEventStateInt() {
        return eventStateInt;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    public void setEnabled(boolean enable) {
        _enable = enable;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    private void set_enable(boolean enable) {
        _enable = enable;
    }

    
    /**
     *  set version
     */
    public void setVersion(int version) {
        _version = version;
    }

    private void set_version(int version) {
        _version = version;
    }

    /**
     *  set operator user id
     *  @parameter user id.
     */
    public void setOptUserId(long optUserId) {
        _optuserid = optUserId;
    }

    /**
     *  set operator user id
     *  @parameter user id.
     */
    private void set_optuserid(long optUserId) {
        _optuserid = optUserId;
    }

    /**
     *  set start time
     *  @parameter start time which is the start time of object.
     */
    public void setStarttime(java.util.Date starttime) {
        _starttime = starttime;
    }

    private void set_starttime(java.util.Date starttime) {
        _starttime = starttime;
    }

    /**
     *  set endtime
     *  @parameter endtime which is the end time of object.
     */
    public void setEndtime(java.util.Date endtime) {
        _endtime = endtime;
    }

    private void set_endtime(java.util.Date endtime) {
        _endtime = endtime;
    }

/**
     *  set _extType
     *  @param _extType which is the extension type of be object.
     */
    public void set_extType(java.lang.String _extType) {
        this._extType = _extType;
    }
        
    /**
     *  set id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     *  set srcPartyId
     */
    public void setSrcPartyId(long srcPartyId) {
        this.srcPartyId = srcPartyId;
    }

    /**
     *  set tarPartyId
     */
    public void setTarPartyId(long tarPartyId) {
        this.tarPartyId = tarPartyId;
    }

    /**
     *  set pageInfo
     */
    public void setPageInfo(java.lang.String pageInfo) {
        this.pageInfo = pageInfo;
    }

    /**
     *  set eventRecord
     */
    public void setEventRecord(java.lang.String eventRecord) {
        this.eventRecord = eventRecord;
    }

    /**
     *  set eventType
     */
    public void setEventType(PartyEventType eventType) {
        this.eventType = eventType;
    if (eventTypeInt != eventType.getIntValue()) {
            eventTypeInt = eventType.getIntValue();
        }
    }

    /**
     *  set int eventType
     */
    private void setEventTypeInt(int intValue) {
        this.eventTypeInt = intValue;
        if (eventTypeInt != eventType.getIntValue()) {
            eventType = (PartyEventType)ceService.getConstantEntity(PartyEventType.ENTITY_NAME).getByIntValue(eventTypeInt);
        }
    }

    /**
     *  set eventState
     */
    public void setEventState(PartyEventStatusType eventState) {
        this.eventState = eventState;
    if (eventStateInt != eventState.getIntValue()) {
            eventStateInt = eventState.getIntValue();
        }
    }

    /**
     *  set int eventState
     */
    private void setEventStateInt(int intValue) {
        this.eventStateInt = intValue;
        if (eventStateInt != eventState.getIntValue()) {
            eventState = (PartyEventStatusType)ceService.getConstantEntity(PartyEventStatusType.ENTITY_NAME).getByIntValue(eventStateInt);
        }
    }

    
    /**
     * Check different according to primary key.
     */
    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof org.shaolin.vogerp.commonmodel.be.PartyEventImpl))
            return false;
        org.shaolin.vogerp.commonmodel.be.PartyEventImpl o = (org.shaolin.vogerp.commonmodel.be.PartyEventImpl)obj;
        
        boolean result = super.equals(obj);

        boolean eq = true;
        
        return result;
    }

    /**
     * Generate hashCode according to primary key.
     */
    public int hashCode() {
        
        int result = super.hashCode();

        return result;
    }
        
    
     /**
     * Gets the String format of the business entity.
     *
     * @return String the business entity in String format.
     */
    public  String  toString() {
        StringBuffer aBuf = new StringBuffer();
        aBuf.append("org.shaolin.vogerp.commonmodel.be.PartyEvent");
    
        aBuf.append(" : ");
        
        aBuf.append("enable=").append(_enable).append(", ");
        
        aBuf.append("id");
        aBuf.append("=");
        aBuf.append(id);
        aBuf.append(", ");
        
        aBuf.append("srcPartyId");
        aBuf.append("=");
        aBuf.append(srcPartyId);
        aBuf.append(", ");
        
        aBuf.append("tarPartyId");
        aBuf.append("=");
        aBuf.append(tarPartyId);
        aBuf.append(", ");
        
        aBuf.append("pageInfo");
        aBuf.append("=");
        aBuf.append(pageInfo);
        aBuf.append(", ");
        
        aBuf.append("eventRecord");
        aBuf.append("=");
        aBuf.append(eventRecord);
        aBuf.append(", ");
        
        aBuf.append("eventType");
        aBuf.append("=");
        aBuf.append(eventType);
        aBuf.append(", ");
        
        aBuf.append("eventState");
        aBuf.append("=");
        aBuf.append(eventState);
        aBuf.append(", ");
        
        return aBuf.toString();
    }
    
    
     /**
     * Gets list of MemberType.
     *
     * @return List     the list of MemberType.
     */
    public List<MemberType> getMemberList() {
        List<MemberType> memberTypeList = new ArrayList<MemberType>();
        
        MemberType member = null;
        
        org.shaolin.bmdp.datamodel.bediagram.LongType idBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for id
        member = new MemberType();
        member.setName("id");
        member.setDescription("null");
        member.setType(idBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.LongType srcPartyIdBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for srcPartyId
        member = new MemberType();
        member.setName("srcPartyId");
        member.setDescription("null");
        member.setType(srcPartyIdBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.LongType tarPartyIdBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for tarPartyId
        member = new MemberType();
        member.setName("tarPartyId");
        member.setDescription("null");
        member.setType(tarPartyIdBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType pageInfoBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for pageInfo
        member = new MemberType();
        member.setName("pageInfo");
        member.setDescription("null");
        member.setType(pageInfoBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType eventRecordBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for eventRecord
        member = new MemberType();
        member.setName("eventRecord");
        member.setDescription("null");
        member.setType(eventRecordBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.CEObjRefType eventTypeBEType = new org.shaolin.bmdp.datamodel.bediagram.CEObjRefType();
    
        TargetEntityType eventTypeTargetEntity = new TargetEntityType();
        eventTypeBEType.setTargetEntity(eventTypeTargetEntity);
        eventTypeTargetEntity.setEntityName("org.shaolin.vogerp.commonmodel.ce.PartyEventType");
            
        //MemberType Define for eventType
        member = new MemberType();
        member.setName("eventType");
        member.setDescription("null");
        member.setType(eventTypeBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.CEObjRefType eventStateBEType = new org.shaolin.bmdp.datamodel.bediagram.CEObjRefType();
    
        TargetEntityType eventStateTargetEntity = new TargetEntityType();
        eventStateBEType.setTargetEntity(eventStateTargetEntity);
        eventStateTargetEntity.setEntityName("org.shaolin.vogerp.commonmodel.ce.PartyEventStatusType");
            
        //MemberType Define for eventState
        member = new MemberType();
        member.setName("eventState");
        member.setDescription("null");
        member.setType(eventStateBEType);
        memberTypeList.add(member);
            
        return memberTypeList;
    }
    
    public IPartyEvent createEntity ()
    {
        return new PartyEventImpl();
    }
    
}

        

