/*
 *
 * This file is automatically generated on Thu Jul 23 13:15:09 CST 2015
 */

    
package org.shaolin.vogerp.commonmodel.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;



/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public class PersonalAccountImpl  implements org.shaolin.vogerp.commonmodel.be.IPersonalAccount
{
    private static final long serialVersionUID = 0x90B1123CE87B50FFL;

    private final IConstantService ceService = AppContext.get().getConstantService();

    protected String getBusinessEntityName()
    {
        return "org.shaolin.vogerp.commonmodel.be.PersonalAccount";
    }

    public PersonalAccountImpl()
    {
        
        _extField = new BEExtensionInfo();
        
    }
    
    
        /**
     * Enable record
     */
    private boolean _enable = true;


    /**
     * History version
     */
    protected int _version = 0;

    /**
     * History starttime
     */
    private java.util.Date _starttime = new java.util.Date();

    /**
     * History endtime
     */
    private java.util.Date _endtime = null;

    /**
     * History _optuserid
     */
    private long _optuserid = 0L;


    /**
     *  BEExtension _extType
     */
    protected String _extType;

    /**
     *  BEExtension _extField
     */
    protected BEExtensionInfo _extField;
        
   /**
     *  help is not available
     */    
    protected long id;
    
   /**
     *  help is not available
     */    
    protected java.lang.String userName;
    
   /**
     *  help is not available
     */    
    protected java.lang.String password;
    
   /**
     *  help is not available
     */    
    protected long personalId;
    
   /**
     *  help is not available
     */    
    protected PersonalInfoImpl info;
    
   /**
     *  help is not available
     */    
    protected java.lang.String locale;
    
   /**
     *  help is not available
     */    
    protected int attempt;
    
   /**
     *  help is not available
     */    
    protected boolean isLocked;
    
   /**
     *  help is not available
     */    
    protected java.util.Date lockedMoment;
    
   /**
     *  help is not available
     */    
    protected java.util.Date expirationDate;
    
   /**
     *  help is not available
     */    
    protected java.util.Date lastLogin;
    
        /**
     *  Is enable
     *
     *  @return boolean
     */
    public boolean isEnabled() {
        return _enable;
    }
            /**
     *  Is enable
     *
     *  @return boolean
     */
    private boolean get_enable() {
        return _enable;
    }
        
    /**
     *  get version
     *
     *  @return version
     */
    public int getVersion() {
        return _version;
    }

    private int get_version() {
        return _version;
    }

    /**
     *  get operator user id
     *
     *  @return user id
     */
    public long getOptUserId() {
        return _optuserid;
    }

    /**
     *  get operator user id
     *
     *  @return user id
     */
    private long get_optuserid() {
        return _optuserid;
    }

    /**
     *  get start time
     *
     *  @return start time
     */
    public java.util.Date getStarttime() {
        return _starttime;
    }

    private java.util.Date get_starttime() {
        return _starttime;
    }

    /**
     *  get endtime
     *
     *  @return endtime
     */
    public java.util.Date getEndtime() {
        return _endtime;
    }

    private java.util.Date get_endtime() {
        return _endtime;
    }


    /**
     *  get _extType
     *
     *  @return _extType
     */
    public String get_extType() {
        return _extType;
    }

    /**
     *  get _extField
     *
     *  @return _extField
     */
    public BEExtensionInfo get_extField() {
        return _extField;
    }
        
    /**
     *  get id
     *
     *  @return id
     */
    public long getId() {
        return id;
    }

    /**
     *  get userName
     *
     *  @return userName
     */
    public java.lang.String getUserName() {
        return userName;
    }

    /**
     *  get password
     *
     *  @return password
     */
    public java.lang.String getPassword() {
        return password;
    }

    /**
     *  get personalId
     *
     *  @return personalId
     */
    public long getPersonalId() {
        return personalId;
    }

    /**
     *  get info
     *
     *  @return info
     */
    public PersonalInfoImpl getInfo() {
        return info;
    }

    /**
     *  get locale
     *
     *  @return locale
     */
    public java.lang.String getLocale() {
        return locale;
    }

    /**
     *  get attempt
     *
     *  @return attempt
     */
    public int getAttempt() {
        return attempt;
    }

    /**
     *  get isLocked
     *
     *  @return isLocked
     */
    public boolean getIsLocked() {
        return isLocked;
    }

    /**
     *  get lockedMoment
     *
     *  @return lockedMoment
     */
    public java.util.Date getLockedMoment() {
        return lockedMoment;
    }

    /**
     *  get expirationDate
     *
     *  @return expirationDate
     */
    public java.util.Date getExpirationDate() {
        return expirationDate;
    }

    /**
     *  get lastLogin
     *
     *  @return lastLogin
     */
    public java.util.Date getLastLogin() {
        return lastLogin;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    public void setEnabled(boolean enable) {
        _enable = enable;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    private void set_enable(boolean enable) {
        _enable = enable;
    }

    
    /**
     *  set version
     */
    public void setVersion(int version) {
        _version = version;
    }

    private void set_version(int version) {
        _version = version;
    }

    /**
     *  set operator user id
     *  @parameter user id.
     */
    public void setOptUserId(long optUserId) {
        _optuserid = optUserId;
    }

    /**
     *  set operator user id
     *  @parameter user id.
     */
    private void set_optuserid(long optUserId) {
        _optuserid = optUserId;
    }

    /**
     *  set start time
     *  @parameter start time which is the start time of object.
     */
    public void setStarttime(java.util.Date starttime) {
        _starttime = starttime;
    }

    private void set_starttime(java.util.Date starttime) {
        _starttime = starttime;
    }

    /**
     *  set endtime
     *  @parameter endtime which is the end time of object.
     */
    public void setEndtime(java.util.Date endtime) {
        _endtime = endtime;
    }

    private void set_endtime(java.util.Date endtime) {
        _endtime = endtime;
    }

/**
     *  set _extType
     *  @param _extType which is the extension type of be object.
     */
    public void set_extType(java.lang.String _extType) {
        this._extType = _extType;
    }
        
    /**
     *  set id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     *  set userName
     */
    public void setUserName(java.lang.String userName) {
        this.userName = userName;
    }

    /**
     *  set password
     */
    public void setPassword(java.lang.String password) {
        this.password = password;
    }

    /**
     *  set personalId
     */
    public void setPersonalId(long personalId) {
        this.personalId = personalId;
    }

    /**
     *  set info
     */
    public void setInfo(PersonalInfoImpl info) {
        this.info = info;
    }

    /**
     *  set locale
     */
    public void setLocale(java.lang.String locale) {
        this.locale = locale;
    }

    /**
     *  set attempt
     */
    public void setAttempt(int attempt) {
        this.attempt = attempt;
    }

    /**
     *  set isLocked
     */
    public void setIsLocked(boolean isLocked) {
        this.isLocked = isLocked;
    }

    /**
     *  set lockedMoment
     */
    public void setLockedMoment(java.util.Date lockedMoment) {
        this.lockedMoment = lockedMoment;
    }

    /**
     *  set expirationDate
     */
    public void setExpirationDate(java.util.Date expirationDate) {
        this.expirationDate = expirationDate;
    }

    /**
     *  set lastLogin
     */
    public void setLastLogin(java.util.Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    
    /**
     * Check different according to primary key.
     */
    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof org.shaolin.vogerp.commonmodel.be.PersonalAccountImpl))
            return false;
        org.shaolin.vogerp.commonmodel.be.PersonalAccountImpl o = (org.shaolin.vogerp.commonmodel.be.PersonalAccountImpl)obj;
        
        boolean result = super.equals(obj);

        boolean eq = true;
        
        return result;
    }

    /**
     * Generate hashCode according to primary key.
     */
    public int hashCode() {
        
        int result = super.hashCode();

        return result;
    }
        
    
     /**
     * Gets the String format of the business entity.
     *
     * @return String the business entity in String format.
     */
    public  String  toString() {
        StringBuffer aBuf = new StringBuffer();
        aBuf.append("org.shaolin.vogerp.commonmodel.be.PersonalAccount");
    
        aBuf.append(" : ");
        
        aBuf.append("enable=").append(_enable).append(", ");
        
        aBuf.append("id");
        aBuf.append("=");
        aBuf.append(id);
        aBuf.append(", ");
        
        aBuf.append("userName");
        aBuf.append("=");
        aBuf.append(userName);
        aBuf.append(", ");
        
        aBuf.append("password");
        aBuf.append("=");
        aBuf.append(password);
        aBuf.append(", ");
        
        aBuf.append("personalId");
        aBuf.append("=");
        aBuf.append(personalId);
        aBuf.append(", ");
        
        aBuf.append("info");
        aBuf.append("=");
        aBuf.append(info==null? "" : info.toString());
        aBuf.append(", ");
        
        aBuf.append("locale");
        aBuf.append("=");
        aBuf.append(locale);
        aBuf.append(", ");
        
        aBuf.append("attempt");
        aBuf.append("=");
        aBuf.append(attempt);
        aBuf.append(", ");
        
        aBuf.append("isLocked");
        aBuf.append("=");
        aBuf.append(isLocked);
        aBuf.append(", ");
        
        aBuf.append("lockedMoment");
        aBuf.append("=");
        aBuf.append(lockedMoment);
        aBuf.append(", ");
        
        aBuf.append("expirationDate");
        aBuf.append("=");
        aBuf.append(expirationDate);
        aBuf.append(", ");
        
        aBuf.append("lastLogin");
        aBuf.append("=");
        aBuf.append(lastLogin);
        aBuf.append(", ");
        
        return aBuf.toString();
    }
    
    
     /**
     * Gets list of MemberType.
     *
     * @return List     the list of MemberType.
     */
    public List<MemberType> getMemberList() {
        List<MemberType> memberTypeList = new ArrayList<MemberType>();
        
        MemberType member = null;
        
        org.shaolin.bmdp.datamodel.bediagram.LongType idBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for id
        member = new MemberType();
        member.setName("id");
        member.setDescription("null");
        member.setType(idBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType userNameBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for userName
        member = new MemberType();
        member.setName("userName");
        member.setDescription("null");
        member.setType(userNameBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType passwordBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for password
        member = new MemberType();
        member.setName("password");
        member.setDescription("null");
        member.setType(passwordBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.LongType personalIdBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for personalId
        member = new MemberType();
        member.setName("personalId");
        member.setDescription("null");
        member.setType(personalIdBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.BEObjRefType infoBEType = new org.shaolin.bmdp.datamodel.bediagram.BEObjRefType();
    
        TargetEntityType infoTargetEntity = new TargetEntityType();
        infoTargetEntity.setEntityName("org.shaolin.vogerp.commonmodel.be.PersonalInfo");
        infoBEType.setTargetEntity(infoTargetEntity);
            
        //MemberType Define for info
        member = new MemberType();
        member.setName("info");
        member.setDescription("null");
        member.setType(infoBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType localeBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for locale
        member = new MemberType();
        member.setName("locale");
        member.setDescription("null");
        member.setType(localeBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.IntType attemptBEType = new org.shaolin.bmdp.datamodel.bediagram.IntType();
    
        //MemberType Define for attempt
        member = new MemberType();
        member.setName("attempt");
        member.setDescription("null");
        member.setType(attemptBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.BooleanType isLockedBEType = new org.shaolin.bmdp.datamodel.bediagram.BooleanType();
    
        //MemberType Define for isLocked
        member = new MemberType();
        member.setName("isLocked");
        member.setDescription("null");
        member.setType(isLockedBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.DateTimeType lockedMomentBEType = new org.shaolin.bmdp.datamodel.bediagram.DateTimeType();
    
        //MemberType Define for lockedMoment
        member = new MemberType();
        member.setName("lockedMoment");
        member.setDescription("null");
        member.setType(lockedMomentBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.DateTimeType expirationDateBEType = new org.shaolin.bmdp.datamodel.bediagram.DateTimeType();
    
        //MemberType Define for expirationDate
        member = new MemberType();
        member.setName("expirationDate");
        member.setDescription("null");
        member.setType(expirationDateBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.DateTimeType lastLoginBEType = new org.shaolin.bmdp.datamodel.bediagram.DateTimeType();
    
        //MemberType Define for lastLogin
        member = new MemberType();
        member.setName("lastLogin");
        member.setDescription("null");
        member.setType(lastLoginBEType);
        memberTypeList.add(member);
            
        return memberTypeList;
    }
    
    public IPersonalAccount createEntity ()
    {
        return new PersonalAccountImpl();
    }
    
}

        

