/*
 *
 * This file is automatically generated on Thu Jul 23 13:15:10 CST 2015
 */

    
package org.shaolin.vogerp.commonmodel.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;

import org.shaolin.vogerp.commonmodel.ce.*;


/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public class UIDyanimcItemImpl  implements org.shaolin.vogerp.commonmodel.be.IUIDyanimcItem
{
    private static final long serialVersionUID = 0x90B1123CE87B50FFL;

    private final IConstantService ceService = AppContext.get().getConstantService();

    protected String getBusinessEntityName()
    {
        return "org.shaolin.vogerp.commonmodel.be.UIDyanimcItem";
    }

    public UIDyanimcItemImpl()
    {
        
        _extField = new BEExtensionInfo();
        
    }
    
    
        /**
     * Enable record
     */
    private boolean _enable = true;


    /**
     *  BEExtension _extType
     */
    protected String _extType;

    /**
     *  BEExtension _extField
     */
    protected BEExtensionInfo _extField;
        
   /**
     *  help is not available
     */    
    protected long id;
    
   /**
     *  help is not available
     */    
    protected java.lang.String uiEntityName;
    
   /**
     *  help is not available
     */    
    protected java.lang.String uipanel;
    
   /**
     *  help is not available
     */    
    protected java.lang.String filter;
    
   /**
     *  help is not available
     */    
    protected java.lang.String labelName;
    
   /**
     *  help is not available
     */    
    protected java.lang.String ceName;
    
   /**
     *  help is not available
     */    
    protected CESelectModeType ceSelectMode = CESelectModeType.NOT_SPECIFIED;
    
    protected int ceSelectModeInt = CESelectModeType.NOT_SPECIFIED.getIntValue();
    
        /**
     *  Is enable
     *
     *  @return boolean
     */
    public boolean isEnabled() {
        return _enable;
    }
            /**
     *  Is enable
     *
     *  @return boolean
     */
    private boolean get_enable() {
        return _enable;
    }
        
    /**
     *  get _extType
     *
     *  @return _extType
     */
    public String get_extType() {
        return _extType;
    }

    /**
     *  get _extField
     *
     *  @return _extField
     */
    public BEExtensionInfo get_extField() {
        return _extField;
    }
        
    /**
     *  get id
     *
     *  @return id
     */
    public long getId() {
        return id;
    }

    /**
     *  get uiEntityName
     *
     *  @return uiEntityName
     */
    public java.lang.String getUiEntityName() {
        return uiEntityName;
    }

    /**
     *  get uipanel
     *
     *  @return uipanel
     */
    public java.lang.String getUipanel() {
        return uipanel;
    }

    /**
     *  get filter
     *
     *  @return filter
     */
    public java.lang.String getFilter() {
        return filter;
    }

    /**
     *  get labelName
     *
     *  @return labelName
     */
    public java.lang.String getLabelName() {
        return labelName;
    }

    /**
     *  get ceName
     *
     *  @return ceName
     */
    public java.lang.String getCeName() {
        return ceName;
    }

    /**
     *  get ceSelectMode
     *
     *  @return ceSelectMode
     */
    public CESelectModeType getCeSelectMode() {
        return ceSelectMode;
    }

    /**
     *  get ceSelectModeInt
     *
     *  @return ceSelectModeInt
     */
    private int getCeSelectModeInt() {
        return ceSelectModeInt;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    public void setEnabled(boolean enable) {
        _enable = enable;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    private void set_enable(boolean enable) {
        _enable = enable;
    }

    /**
     *  set _extType
     *  @param _extType which is the extension type of be object.
     */
    public void set_extType(java.lang.String _extType) {
        this._extType = _extType;
    }
        
    /**
     *  set id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     *  set uiEntityName
     */
    public void setUiEntityName(java.lang.String uiEntityName) {
        this.uiEntityName = uiEntityName;
    }

    /**
     *  set uipanel
     */
    public void setUipanel(java.lang.String uipanel) {
        this.uipanel = uipanel;
    }

    /**
     *  set filter
     */
    public void setFilter(java.lang.String filter) {
        this.filter = filter;
    }

    /**
     *  set labelName
     */
    public void setLabelName(java.lang.String labelName) {
        this.labelName = labelName;
    }

    /**
     *  set ceName
     */
    public void setCeName(java.lang.String ceName) {
        this.ceName = ceName;
    }

    /**
     *  set ceSelectMode
     */
    public void setCeSelectMode(CESelectModeType ceSelectMode) {
        this.ceSelectMode = ceSelectMode;
    if (ceSelectModeInt != ceSelectMode.getIntValue()) {
            ceSelectModeInt = ceSelectMode.getIntValue();
        }
    }

    /**
     *  set int ceSelectMode
     */
    private void setCeSelectModeInt(int intValue) {
        this.ceSelectModeInt = intValue;
        if (ceSelectModeInt != ceSelectMode.getIntValue()) {
            ceSelectMode = (CESelectModeType)ceService.getConstantEntity(CESelectModeType.ENTITY_NAME).getByIntValue(ceSelectModeInt);
        }
    }

    
    /**
     * Check different according to primary key.
     */
    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof org.shaolin.vogerp.commonmodel.be.UIDyanimcItemImpl))
            return false;
        org.shaolin.vogerp.commonmodel.be.UIDyanimcItemImpl o = (org.shaolin.vogerp.commonmodel.be.UIDyanimcItemImpl)obj;
        
        boolean result = super.equals(obj);

        boolean eq = true;
        
        return result;
    }

    /**
     * Generate hashCode according to primary key.
     */
    public int hashCode() {
        
        int result = super.hashCode();

        return result;
    }
        
    
     /**
     * Gets the String format of the business entity.
     *
     * @return String the business entity in String format.
     */
    public  String  toString() {
        StringBuffer aBuf = new StringBuffer();
        aBuf.append("org.shaolin.vogerp.commonmodel.be.UIDyanimcItem");
    
        aBuf.append(" : ");
        
        aBuf.append("enable=").append(_enable).append(", ");
        
        aBuf.append("id");
        aBuf.append("=");
        aBuf.append(id);
        aBuf.append(", ");
        
        aBuf.append("uiEntityName");
        aBuf.append("=");
        aBuf.append(uiEntityName);
        aBuf.append(", ");
        
        aBuf.append("uipanel");
        aBuf.append("=");
        aBuf.append(uipanel);
        aBuf.append(", ");
        
        aBuf.append("filter");
        aBuf.append("=");
        aBuf.append(filter);
        aBuf.append(", ");
        
        aBuf.append("labelName");
        aBuf.append("=");
        aBuf.append(labelName);
        aBuf.append(", ");
        
        aBuf.append("ceName");
        aBuf.append("=");
        aBuf.append(ceName);
        aBuf.append(", ");
        
        aBuf.append("ceSelectMode");
        aBuf.append("=");
        aBuf.append(ceSelectMode);
        aBuf.append(", ");
        
        return aBuf.toString();
    }
    
    
     /**
     * Gets list of MemberType.
     *
     * @return List     the list of MemberType.
     */
    public List<MemberType> getMemberList() {
        List<MemberType> memberTypeList = new ArrayList<MemberType>();
        
        MemberType member = null;
        
        org.shaolin.bmdp.datamodel.bediagram.LongType idBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for id
        member = new MemberType();
        member.setName("id");
        member.setDescription("null");
        member.setType(idBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType uiEntityNameBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for uiEntityName
        member = new MemberType();
        member.setName("uiEntityName");
        member.setDescription("null");
        member.setType(uiEntityNameBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType uipanelBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for uipanel
        member = new MemberType();
        member.setName("uipanel");
        member.setDescription("null");
        member.setType(uipanelBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType filterBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for filter
        member = new MemberType();
        member.setName("filter");
        member.setDescription("null");
        member.setType(filterBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType labelNameBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for labelName
        member = new MemberType();
        member.setName("labelName");
        member.setDescription("null");
        member.setType(labelNameBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType ceNameBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for ceName
        member = new MemberType();
        member.setName("ceName");
        member.setDescription("null");
        member.setType(ceNameBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.CEObjRefType ceSelectModeBEType = new org.shaolin.bmdp.datamodel.bediagram.CEObjRefType();
    
        TargetEntityType ceSelectModeTargetEntity = new TargetEntityType();
        ceSelectModeBEType.setTargetEntity(ceSelectModeTargetEntity);
        ceSelectModeTargetEntity.setEntityName("org.shaolin.vogerp.commonmodel.ce.CESelectModeType");
            
        //MemberType Define for ceSelectMode
        member = new MemberType();
        member.setName("ceSelectMode");
        member.setDescription("null");
        member.setType(ceSelectModeBEType);
        memberTypeList.add(member);
            
        return memberTypeList;
    }
    
    public IUIDyanimcItem createEntity ()
    {
        return new UIDyanimcItemImpl();
    }
    
}

        

