/*
 *
 * This file is automatically generated on Thu Jul 23 13:15:10 CST 2015
 */

    
package org.shaolin.vogerp.commonmodel.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;



/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public class UIDyanimcPageLinkImpl  implements org.shaolin.vogerp.commonmodel.be.IUIDyanimcPageLink
{
    private static final long serialVersionUID = 0x90B1123CE87B50FFL;

    private final IConstantService ceService = AppContext.get().getConstantService();

    protected String getBusinessEntityName()
    {
        return "org.shaolin.vogerp.commonmodel.be.UIDyanimcPageLink";
    }

    public UIDyanimcPageLinkImpl()
    {
        
        _extField = new BEExtensionInfo();
        
    }
    
    
        /**
     * Enable record
     */
    private boolean _enable = true;


    /**
     *  BEExtension _extType
     */
    protected String _extType;

    /**
     *  BEExtension _extField
     */
    protected BEExtensionInfo _extField;
        
   /**
     *  help is not available
     */    
    protected long id;
    
   /**
     *  help is not available
     */    
    protected java.lang.String srcUIName;
    
   /**
     *  help is not available
     */    
    protected java.lang.String srcUIPanel;
    
   /**
     *  help is not available
     */    
    protected java.lang.String srcUIWidget;
    
   /**
     *  help is not available
     */    
    protected java.lang.String linkComment;
    
   /**
     *  help is not available
     */    
    protected java.lang.String tarUIName;
    
   /**
     *  help is not available
     */    
    protected java.lang.String tarUITab;
    
   /**
     *  help is not available
     */    
    protected java.lang.String tarUIArchor;
    
        /**
     *  Is enable
     *
     *  @return boolean
     */
    public boolean isEnabled() {
        return _enable;
    }
            /**
     *  Is enable
     *
     *  @return boolean
     */
    private boolean get_enable() {
        return _enable;
    }
        
    /**
     *  get _extType
     *
     *  @return _extType
     */
    public String get_extType() {
        return _extType;
    }

    /**
     *  get _extField
     *
     *  @return _extField
     */
    public BEExtensionInfo get_extField() {
        return _extField;
    }
        
    /**
     *  get id
     *
     *  @return id
     */
    public long getId() {
        return id;
    }

    /**
     *  get srcUIName
     *
     *  @return srcUIName
     */
    public java.lang.String getSrcUIName() {
        return srcUIName;
    }

    /**
     *  get srcUIPanel
     *
     *  @return srcUIPanel
     */
    public java.lang.String getSrcUIPanel() {
        return srcUIPanel;
    }

    /**
     *  get srcUIWidget
     *
     *  @return srcUIWidget
     */
    public java.lang.String getSrcUIWidget() {
        return srcUIWidget;
    }

    /**
     *  get linkComment
     *
     *  @return linkComment
     */
    public java.lang.String getLinkComment() {
        return linkComment;
    }

    /**
     *  get tarUIName
     *
     *  @return tarUIName
     */
    public java.lang.String getTarUIName() {
        return tarUIName;
    }

    /**
     *  get tarUITab
     *
     *  @return tarUITab
     */
    public java.lang.String getTarUITab() {
        return tarUITab;
    }

    /**
     *  get tarUIArchor
     *
     *  @return tarUIArchor
     */
    public java.lang.String getTarUIArchor() {
        return tarUIArchor;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    public void setEnabled(boolean enable) {
        _enable = enable;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    private void set_enable(boolean enable) {
        _enable = enable;
    }

    /**
     *  set _extType
     *  @param _extType which is the extension type of be object.
     */
    public void set_extType(java.lang.String _extType) {
        this._extType = _extType;
    }
        
    /**
     *  set id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     *  set srcUIName
     */
    public void setSrcUIName(java.lang.String srcUIName) {
        this.srcUIName = srcUIName;
    }

    /**
     *  set srcUIPanel
     */
    public void setSrcUIPanel(java.lang.String srcUIPanel) {
        this.srcUIPanel = srcUIPanel;
    }

    /**
     *  set srcUIWidget
     */
    public void setSrcUIWidget(java.lang.String srcUIWidget) {
        this.srcUIWidget = srcUIWidget;
    }

    /**
     *  set linkComment
     */
    public void setLinkComment(java.lang.String linkComment) {
        this.linkComment = linkComment;
    }

    /**
     *  set tarUIName
     */
    public void setTarUIName(java.lang.String tarUIName) {
        this.tarUIName = tarUIName;
    }

    /**
     *  set tarUITab
     */
    public void setTarUITab(java.lang.String tarUITab) {
        this.tarUITab = tarUITab;
    }

    /**
     *  set tarUIArchor
     */
    public void setTarUIArchor(java.lang.String tarUIArchor) {
        this.tarUIArchor = tarUIArchor;
    }

    
    /**
     * Check different according to primary key.
     */
    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof org.shaolin.vogerp.commonmodel.be.UIDyanimcPageLinkImpl))
            return false;
        org.shaolin.vogerp.commonmodel.be.UIDyanimcPageLinkImpl o = (org.shaolin.vogerp.commonmodel.be.UIDyanimcPageLinkImpl)obj;
        
        boolean result = super.equals(obj);

        boolean eq = true;
        
        return result;
    }

    /**
     * Generate hashCode according to primary key.
     */
    public int hashCode() {
        
        int result = super.hashCode();

        return result;
    }
        
    
     /**
     * Gets the String format of the business entity.
     *
     * @return String the business entity in String format.
     */
    public  String  toString() {
        StringBuffer aBuf = new StringBuffer();
        aBuf.append("org.shaolin.vogerp.commonmodel.be.UIDyanimcPageLink");
    
        aBuf.append(" : ");
        
        aBuf.append("enable=").append(_enable).append(", ");
        
        aBuf.append("id");
        aBuf.append("=");
        aBuf.append(id);
        aBuf.append(", ");
        
        aBuf.append("srcUIName");
        aBuf.append("=");
        aBuf.append(srcUIName);
        aBuf.append(", ");
        
        aBuf.append("srcUIPanel");
        aBuf.append("=");
        aBuf.append(srcUIPanel);
        aBuf.append(", ");
        
        aBuf.append("srcUIWidget");
        aBuf.append("=");
        aBuf.append(srcUIWidget);
        aBuf.append(", ");
        
        aBuf.append("linkComment");
        aBuf.append("=");
        aBuf.append(linkComment);
        aBuf.append(", ");
        
        aBuf.append("tarUIName");
        aBuf.append("=");
        aBuf.append(tarUIName);
        aBuf.append(", ");
        
        aBuf.append("tarUITab");
        aBuf.append("=");
        aBuf.append(tarUITab);
        aBuf.append(", ");
        
        aBuf.append("tarUIArchor");
        aBuf.append("=");
        aBuf.append(tarUIArchor);
        aBuf.append(", ");
        
        return aBuf.toString();
    }
    
    
     /**
     * Gets list of MemberType.
     *
     * @return List     the list of MemberType.
     */
    public List<MemberType> getMemberList() {
        List<MemberType> memberTypeList = new ArrayList<MemberType>();
        
        MemberType member = null;
        
        org.shaolin.bmdp.datamodel.bediagram.LongType idBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for id
        member = new MemberType();
        member.setName("id");
        member.setDescription("null");
        member.setType(idBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType srcUINameBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for srcUIName
        member = new MemberType();
        member.setName("srcUIName");
        member.setDescription("null");
        member.setType(srcUINameBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType srcUIPanelBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for srcUIPanel
        member = new MemberType();
        member.setName("srcUIPanel");
        member.setDescription("null");
        member.setType(srcUIPanelBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType srcUIWidgetBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for srcUIWidget
        member = new MemberType();
        member.setName("srcUIWidget");
        member.setDescription("null");
        member.setType(srcUIWidgetBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType linkCommentBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for linkComment
        member = new MemberType();
        member.setName("linkComment");
        member.setDescription("null");
        member.setType(linkCommentBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType tarUINameBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for tarUIName
        member = new MemberType();
        member.setName("tarUIName");
        member.setDescription("null");
        member.setType(tarUINameBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType tarUITabBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for tarUITab
        member = new MemberType();
        member.setName("tarUITab");
        member.setDescription("null");
        member.setType(tarUITabBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType tarUIArchorBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for tarUIArchor
        member = new MemberType();
        member.setName("tarUIArchor");
        member.setDescription("null");
        member.setType(tarUIArchorBEType);
        memberTypeList.add(member);
            
        return memberTypeList;
    }
    
    public IUIDyanimcPageLink createEntity ()
    {
        return new UIDyanimcPageLinkImpl();
    }
    
}

        

