/*
 *
 * This file is automatically generated on Thu Jul 23 13:15:09 CST 2015
 */

    
package org.shaolin.vogerp.commonmodel.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;



/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public class UIWidgetPermissionImpl 
    extends PartyPermissionImpl
         implements org.shaolin.vogerp.commonmodel.be.IUIWidgetPermission
{
    private static final long serialVersionUID = 0x90B1123CE87B50FFL;

    private final IConstantService ceService = AppContext.get().getConstantService();

    protected String getBusinessEntityName()
    {
        return "org.shaolin.vogerp.commonmodel.be.UIWidgetPermission";
    }

    public UIWidgetPermissionImpl()
    {
        
        _extField = new BEExtensionInfo();
        
    }
    
    
        /**
     * Enable record
     */
    private boolean _enable = true;


    /**
     *  BEExtension _extType
     */
    protected String _extType;

    /**
     *  BEExtension _extField
     */
    protected BEExtensionInfo _extField;
        
   /**
     *  help is not available
     */    
    protected java.lang.String pageName;
    
   /**
     *  help is not available
     */    
    protected java.lang.String widgetId;
    
   /**
     *  help is not available
     */    
    protected java.lang.String columnId;
    
        /**
     *  Is enable
     *
     *  @return boolean
     */
    public boolean isEnabled() {
        return _enable;
    }
            /**
     *  Is enable
     *
     *  @return boolean
     */
    private boolean get_enable() {
        return _enable;
    }
        
    /**
     *  get _extType
     *
     *  @return _extType
     */
    public String get_extType() {
        return _extType;
    }

    /**
     *  get _extField
     *
     *  @return _extField
     */
    public BEExtensionInfo get_extField() {
        return _extField;
    }
        
    /**
     *  get pageName
     *
     *  @return pageName
     */
    public java.lang.String getPageName() {
        return pageName;
    }

    /**
     *  get widgetId
     *
     *  @return widgetId
     */
    public java.lang.String getWidgetId() {
        return widgetId;
    }

    /**
     *  get columnId
     *
     *  @return columnId
     */
    public java.lang.String getColumnId() {
        return columnId;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    public void setEnabled(boolean enable) {
        _enable = enable;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    private void set_enable(boolean enable) {
        _enable = enable;
    }

    /**
     *  set _extType
     *  @param _extType which is the extension type of be object.
     */
    public void set_extType(java.lang.String _extType) {
        this._extType = _extType;
    }
        
    /**
     *  set pageName
     */
    public void setPageName(java.lang.String pageName) {
        this.pageName = pageName;
    }

    /**
     *  set widgetId
     */
    public void setWidgetId(java.lang.String widgetId) {
        this.widgetId = widgetId;
    }

    /**
     *  set columnId
     */
    public void setColumnId(java.lang.String columnId) {
        this.columnId = columnId;
    }

    
    /**
     * Check different according to primary key.
     */
    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof org.shaolin.vogerp.commonmodel.be.UIWidgetPermissionImpl))
            return false;
        org.shaolin.vogerp.commonmodel.be.UIWidgetPermissionImpl o = (org.shaolin.vogerp.commonmodel.be.UIWidgetPermissionImpl)obj;
        
        boolean result = super.equals(obj);

        boolean eq = true;
        
        return result;
    }

    /**
     * Generate hashCode according to primary key.
     */
    public int hashCode() {
        
        int result = super.hashCode();

        return result;
    }
        
    
     /**
     * Gets the String format of the business entity.
     *
     * @return String the business entity in String format.
     */
    public  String  toString() {
        StringBuffer aBuf = new StringBuffer();
        aBuf.append("org.shaolin.vogerp.commonmodel.be.UIWidgetPermission");
    
        aBuf.append(" extends ");
        aBuf.append(super.toString());
        
        aBuf.append("enable=").append(_enable).append(", ");
        
        aBuf.append("pageName");
        aBuf.append("=");
        aBuf.append(pageName);
        aBuf.append(", ");
        
        aBuf.append("widgetId");
        aBuf.append("=");
        aBuf.append(widgetId);
        aBuf.append(", ");
        
        aBuf.append("columnId");
        aBuf.append("=");
        aBuf.append(columnId);
        aBuf.append(", ");
        
        return aBuf.toString();
    }
    
    
     /**
     * Gets list of MemberType.
     *
     * @return List     the list of MemberType.
     */
    public List<MemberType> getMemberList() {
        List<MemberType> memberTypeList = new ArrayList<MemberType>();
        
        List<MemberType> parentList = super.getMemberList();
        for(int i=0, n=parentList.size(); i<n; i++)
            memberTypeList.add(parentList.get(i));
            
        MemberType member = null;
        
        org.shaolin.bmdp.datamodel.bediagram.StringType pageNameBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for pageName
        member = new MemberType();
        member.setName("pageName");
        member.setDescription("null");
        member.setType(pageNameBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType widgetIdBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for widgetId
        member = new MemberType();
        member.setName("widgetId");
        member.setDescription("null");
        member.setType(widgetIdBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType columnIdBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for columnId
        member = new MemberType();
        member.setName("columnId");
        member.setDescription("null");
        member.setType(columnIdBEType);
        memberTypeList.add(member);
            
        return memberTypeList;
    }
    
    public IUIWidgetPermission createEntity ()
    {
        return new UIWidgetPermissionImpl();
    }
    
}

        

