#---------------------------------------
-- Create SQL Generated               --
--                                    --
-- Please DO NOT modify !!            --
-- Generated on 2015-07-21 11:50:38   --
#---------------------------------------

USE <database name>;

-- PROD_PRODUCT
CREATE TABLE PROD_PRODUCT
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 PARENTID BIGINT(38),
 NAME VARCHAR(255),
 SERIALNUMBER VARCHAR(50),
 ONSALEDATE DATETIME,
 SALEENDDATE DATETIME,
 MAJORFLAG TINYINT(1),
 DESCRIPTION VARCHAR(255),
 PHOTOS VARCHAR(255),
 TYPE VARCHAR(100),
 INTERESTEDPARTYTYPE INT(2),
 _enable INT(2) DEFAULT 1,
 PRIMARY KEY(ID)
);

-- PROD_PRODUCTCODE
CREATE TABLE PROD_PRODUCTCODE
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 PRODUCTID BIGINT(38),
 CODE VARCHAR(255),
 TYPE INT(2),
 _enable INT(2) DEFAULT 1,
 PRIMARY KEY(ID)
);

-- PROD_PRODUCTCHARAC
CREATE TABLE PROD_PRODUCTCHARAC
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 PRODUCTID BIGINT(38),
 CEVALUES VARCHAR(512),
 _enable INT(2) DEFAULT 1,
 PRIMARY KEY(ID)
);

-- PROD_PRODUCTPRICE
CREATE TABLE PROD_PRODUCTPRICE
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 PRODUCTID BIGINT(38),
 PARTYID BIGINT(38),
 PACKAGE VARCHAR(255),
 PRICE DECIMAL,
 EXCEEDAMOUNT INT(10),
 DISCOUNT DECIMAL,
 COMMENTS VARCHAR(255),
 TYPE INT(2),
 _enable INT(2) DEFAULT 1,
 PRIMARY KEY(ID)
);

-- PROD_PRODUCTPCOST
CREATE TABLE PROD_PRODUCTPCOST
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 PRODUCTID BIGINT(38),
 PACKAGE VARCHAR(255),
 PRICE DECIMAL,
 COMMENTS VARCHAR(255),
 TYPE INT(2),
 _enable INT(2) DEFAULT 1,
 PRIMARY KEY(ID)
);

-- PROD_SUPPLIERPRODUCT
CREATE TABLE PROD_SUPPLIERPRODUCT
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 PRODUCTID BIGINT(38),
 DESCRIPTION VARCHAR(255),
 FEASIBLESTARTDATE DATETIME,
 STANDARDDAYS INT(10),
 PRIORITYTYPE INT(2),
 LEVELTYPE INT(2),
 _enable INT(2) DEFAULT 1,
 PRIMARY KEY(ID)
);

-- PROD_WAREHOUSE
CREATE TABLE PROD_WAREHOUSE
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 PARENTID BIGINT(38),
 NAME VARCHAR(255),
 DESCRIPTION VARCHAR(255),
 CONTAINERTYPE INT(2),
 LOCATION VARCHAR(255),
 PHOTOPATH VARCHAR(255),
 _enable INT(2) DEFAULT 1,
 PRIMARY KEY(ID)
);

-- PROD_STORAGEITEM
CREATE TABLE PROD_STORAGEITEM
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 PRODUCTID BIGINT(38),
 WAREHOUSEID BIGINT(38),
 COORDINATE VARCHAR(255),
 ITEMSTATUS INT(2),
 NUMBER INT(10),
 SERIALNUMBER VARCHAR(255),
 _enable INT(2) DEFAULT 1,
 _version INT(2) DEFAULT 0,
 _starttime TIMESTAMP,
 _endtime TIMESTAMP,
 _optuserid BIGINT(38) DEFAULT 0,
 PRIMARY KEY(ID)
);

