#---------------------------------------
-- Create SQL Generated               --
--                                    --
-- Please DO NOT modify !!            --
-- Generated on 2015-07-23 01:15:14   --
#---------------------------------------

USE <database name>;

-- COMM_PARTYRELATIONSHIP
CREATE TABLE COMM_PARTYRELATIONSHIP
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 TYPE INT(2),
 SRCPARTYID BIGINT(38),
 TARPARTYID BIGINT(38),
 _enable INT(2) DEFAULT 1,
 _version INT(2) DEFAULT 0,
 _starttime TIMESTAMP,
 _endtime TIMESTAMP,
 _optuserid BIGINT(38) DEFAULT 0,
 PRIMARY KEY(ID)
);

-- COMM_PARTYEVENT
CREATE TABLE COMM_PARTYEVENT
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 SRCPARTYID BIGINT(38),
 TARPARTYID BIGINT(38),
 EVENTRECORD VARCHAR(255),
 PAGEINFO VARCHAR(255),
 EVENTTYPE INT(2),
 EVENTSTATE INT(2),
 _enable INT(2) DEFAULT 1,
 _version INT(2) DEFAULT 0,
 _starttime TIMESTAMP,
 _endtime TIMESTAMP,
 _optuserid BIGINT(38) DEFAULT 0,
 PRIMARY KEY(ID)
);

-- COMM_ORGANIZATION
CREATE TABLE COMM_ORGANIZATION
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 PARENTID BIGINT(38),
 ORGCODE VARCHAR(38),
 NAME VARCHAR(255),
 DESCRIPTION VARCHAR(255),
 TYPE VARCHAR(100) DEFAULT -1,
 _enable INT(2) DEFAULT 1,
 PRIMARY KEY(ID)
);

-- COMM_LEGALORGANIZATIONINFO
CREATE TABLE COMM_LEGALORGANIZATIONINFO
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 ORGID BIGINT(38),
 LEGALPERSON VARCHAR(255),
 TRADELICENSENUMBER VARCHAR(255),
 BUSILICENSENUMBER VARCHAR(255),
 BUSILICENSEDATE DATETIME,
 TAXREGISTRATIONNUMBER VARCHAR(255),
 TAXREGISTRATIONDATE DATETIME,
 LOCALTAXREGISTRATIONNUMBER VARCHAR(255),
 LOCALTAXREGISTRATIONDATE DATETIME,
 ENTERPRISECODE VARCHAR(255),
 BANKACCOUNT VARCHAR(255),
 BANKTYPE INT(2) DEFAULT -1,
 _enable INT(2) DEFAULT 1,
 PRIMARY KEY(ID)
);

-- COMM_ORGANIZATION_CONTRACT
CREATE TABLE COMM_ORGANIZATION_CONTRACT
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 ORGID BIGINT(38),
 TYPE INT(2) DEFAULT -1,
 TERMS VARCHAR(255),
 EXPIRATIONDATE DATETIME,
 _enable INT(2) DEFAULT 1,
 PRIMARY KEY(ID)
);

-- COMM_PERSONINFO
CREATE TABLE COMM_PERSONINFO
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 FIRSTNAME VARCHAR(20),
 LASTNAME VARCHAR(50),
 GENDER INT(2),
 MARRIED TINYINT(1),
 IDENTITYCARDID VARCHAR(255),
 DISCRIPTION VARCHAR(255),
 BIRTHDAY DATETIME,
 LANGUAGE INT(2),
 EDUCATION INT(2),
 MAJOR VARCHAR(255),
 COMMENT VARCHAR(255),
 TYPE VARCHAR(100) DEFAULT -1,
 _enable INT(2) DEFAULT 1,
 PRIMARY KEY(ID)
);

-- COMM_PERSONALACCOUNT
CREATE TABLE COMM_PERSONALACCOUNT
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 PERSONALID BIGINT(38),
 USERNAME VARCHAR(50),
 PASSWORD VARCHAR(50),
 LOCALE VARCHAR(10),
 ATTEMPT INT(2),
 ISLOCKED TINYINT(1),
 LOCKEDMOMENT DATETIME,
 EXPIRATIONDATE DATETIME,
 LASTLOGIN DATETIME,
 _enable INT(2) DEFAULT 1,
 _version INT(2) DEFAULT 0,
 _starttime TIMESTAMP,
 _endtime TIMESTAMP,
 _optuserid BIGINT(38) DEFAULT 0,
 PRIMARY KEY(ID)
);

-- COMM_ADDRESSINFO
CREATE TABLE COMM_ADDRESSINFO
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 COUNTRY VARCHAR(255),
 CITY VARCHAR(255),
 STREET VARCHAR(255),
 BLOCK VARCHAR(255),
 ZIPCODE VARCHAR(255),
 DESCRIPTION VARCHAR(255),
 _enable INT(2) DEFAULT 1,
 PRIMARY KEY(ID)
);

-- COMM_CONTACTINFO
CREATE TABLE COMM_CONTACTINFO
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 TELEPHONE VARCHAR(255),
 MOBILE VARCHAR(255),
 EMAIL VARCHAR(255),
 HOMEPAGE VARCHAR(255),
 REMARK VARCHAR(255),
 _enable INT(2) DEFAULT 1,
 PRIMARY KEY(ID)
);

-- COMM_MODELPERMISSION
CREATE TABLE COMM_MODELPERMISSION
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 MODULEID BIGINT(38),
 PARTYTYPE VARCHAR(100) DEFAULT -1,
 _enable INT(2) DEFAULT 1,
 PRIMARY KEY(ID)
);

-- COMM_UIWIDGETPERMISSION
CREATE TABLE COMM_UIWIDGETPERMISSION
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 PAGENAME VARCHAR(255),
 WIDGETID VARCHAR(255),
 PARTYTYPE VARCHAR(100) DEFAULT -1,
 _enable INT(2) DEFAULT 1,
 PRIMARY KEY(ID)
);

-- COMM_BEPERMISSION
CREATE TABLE COMM_BEPERMISSION
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 BENAME VARCHAR(255),
 FIELD VARCHAR(255),
 PARTYTYPE VARCHAR(100) DEFAULT -1,
 _enable INT(2) DEFAULT 1,
 PRIMARY KEY(ID)
);

-- COMM_MODULEGROUP
CREATE TABLE COMM_MODULEGROUP
(GROUPID BIGINT(38) NOT NULL AUTO_INCREMENT,
 PARENTID BIGINT(38),
 NAME VARCHAR(255),
 DESCRIPTION VARCHAR(255),
 SMALLICON VARCHAR(255),
 BIGICON VARCHAR(255),
 ACCESSURL VARCHAR(255),
 _enable INT(2),
 PRIMARY KEY(GROUPID)
);

-- COMM_CEENTITYINFO
CREATE TABLE COMM_CEENTITYINFO
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 CENAME VARCHAR(255),
 I18NKEY VARCHAR(255),
 DESCRIPTION VARCHAR(255),
 ICON VARCHAR(255),
 _enable INT(2) DEFAULT 1,
 PRIMARY KEY(ID)
);

-- COMM_CEEXTENSION
CREATE TABLE COMM_CEEXTENSION
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 CENAME VARCHAR(255),
 INTVALUE INT(10),
 STRINGVALUE VARCHAR(255),
 I18NKEY VARCHAR(255),
 DESCRIPTION VARCHAR(255),
 ICON VARCHAR(255),
 _enable INT(2) DEFAULT 1,
 PRIMARY KEY(ID)
);

-- COMM_CEHIERARCHY
CREATE TABLE COMM_CEHIERARCHY
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 parentCeName VARCHAR(255),
 parentCeItem INT(2),
 CENAME VARCHAR(255),
 _enable INT(2) DEFAULT 1,
 PRIMARY KEY(ID)
);

-- COMM_UIDYANICITEM
CREATE TABLE COMM_UIDYANICITEM
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 uiEntityName VARCHAR(255),
 uipanel VARCHAR(255),
 labelName INT(10),
 ceName VARCHAR(255),
 ceSelectMode INT(2),
 filter INT(10),
 _enable INT(2) DEFAULT 1,
 PRIMARY KEY(ID)
);

-- COMM_UIDYANICPAGELINK
CREATE TABLE COMM_UIDYANICPAGELINK
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 SRCUIName VARCHAR(255),
 SRCUIPanel VARCHAR(255),
 SRCUIWidget VARCHAR(255),
 LinkComment VARCHAR(255),
 TARUIName VARCHAR(255),
 _enable INT(2) DEFAULT 1,
 PRIMARY KEY(ID)
);

-- Join table COMM_PERSONINFOADDRESSINFO_JT
CREATE TABLE COMM_PERSONINFOADDRESSINFO_JT
(ID BIGINT(38),
 ELT BIGINT(38),
 _index INT(5));

-- Join table COMM_PERSONINFOCONTACTINFO_JT
CREATE TABLE COMM_PERSONINFOCONTACTINFO_JT
(ID BIGINT(38),
 ELT BIGINT(38),
 _index INT(5));

