#---------------------------------------
-- Drop SQL Generated         --
--                                    --
-- Please DO NOT modify !!            --
-- Generated on 2015-07-23 01:15:14   --
#---------------------------------------

USE <database name>;

DROP TABLE COMM_PARTYRELATIONSHIP CASCADE;

DROP TABLE COMM_PARTYEVENT CASCADE;

DROP TABLE COMM_ORGANIZATION CASCADE;

DROP TABLE COMM_LEGALORGANIZATIONINFO CASCADE;

DROP TABLE COMM_ORGANIZATION_CONTRACT CASCADE;

DROP TABLE COMM_PERSONINFO CASCADE;

DROP TABLE COMM_PERSONALACCOUNT CASCADE;

DROP TABLE COMM_ADDRESSINFO CASCADE;

DROP TABLE COMM_CONTACTINFO CASCADE;

DROP TABLE COMM_MODELPERMISSION CASCADE;

DROP TABLE COMM_UIWIDGETPERMISSION CASCADE;

DROP TABLE COMM_BEPERMISSION CASCADE;

DROP TABLE COMM_MODULEGROUP CASCADE;

DROP TABLE COMM_CEENTITYINFO CASCADE;

DROP TABLE COMM_CEEXTENSION CASCADE;

DROP TABLE COMM_CEHIERARCHY CASCADE;

DROP TABLE COMM_UIDYANICITEM CASCADE;

DROP TABLE COMM_UIDYANICPAGELINK CASCADE;

DROP TABLE COMM_PERSONINFOADDRESSINFO_JT CASCADE;

DROP TABLE COMM_PERSONINFOCONTACTINFO_JT CASCADE;

