#---------------------------------------
-- Drop SQL Generated         --
--                                    --
-- Please DO NOT modify !!            --
-- Generated on 2015-07-19 11:56:36   --
#---------------------------------------

USE <database name>;

DROP TABLE INVOICE CASCADE;

DROP TABLE INVOICEITEM CASCADE;

DROP TABLE INVOICEITEMWITHSHIPMENT CASCADE;

DROP TABLE INVOICEITEMWITHORDER CASCADE;

DROP TABLE INVOICEPAYMENT CASCADE;

DROP TABLE TRANSACTION CASCADE;

DROP TABLE DOUBLEENTRY CASCADE;

DROP TABLE BUDGET CASCADE;

DROP TABLE BUDGETITEM CASCADE;

DROP TABLE INBALANCESHEET CASCADE;

DROP TABLE PROFITSHEET CASCADE;

DROP TABLE CASHFLOWSHEET CASCADE;

