#---------------------------------------
-- Create SQL Generated               --
--                                    --
-- Please DO NOT modify !!            --
-- Generated on 2015-07-19 11:56:36   --
#---------------------------------------

USE <database name>;

-- INVOICE
CREATE TABLE INVOICE
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 SERIALNUMBER VARCHAR(255),
 CUSTOMERINFO VARCHAR(255),
 DESCRIPTION VARCHAR(255),
 CREATEDATE DATETIME,
 ROLE INT(2),
 STATUS INT(2),
 PAYMENTPARTYID BIGINT(38),
 SOURCE VARCHAR(255),
 TARGETPARTYID BIGINT(38),
 DESTINATION VARCHAR(255),
 _enable INT(2) DEFAULT 1,
 _version INT(2) DEFAULT 0,
 _starttime TIMESTAMP,
 _endtime TIMESTAMP,
 _optuserid BIGINT(38) DEFAULT 0);

-- INVOICEITEM
CREATE TABLE INVOICEITEM
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 INVOICEID BIGINT(38),
 PRODUCTID BIGINT(38),
 AMOUNT INT(10),
 UNITPRICE DECIMAL,
 TYPE INT(2),
 ISADJUSTED TINYINT(1),
 STATEMENT VARCHAR(255),
 _enable INT(2) DEFAULT 1);

-- INVOICEITEMWITHSHIPMENT
CREATE TABLE INVOICEITEMWITHSHIPMENT
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 INVOICEID BIGINT(38),
 INVOICEITEMID BIGINT(38),
 SHIPMENTID BIGINT(38),
 SHIPMENTITEMID BIGINT(38),
 AMOUNT INT(10),
 _enable INT(2) DEFAULT 1);

-- INVOICEITEMWITHORDER
CREATE TABLE INVOICEITEMWITHORDER
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 INVOICEID BIGINT(38),
 INVOICEITEMID BIGINT(38),
 INVOICEAMOUNT INT(10),
 ORDERID BIGINT(38),
 ORDERITEMID BIGINT(38),
 ORDERAMOUNT INT(10),
 ORDERUNITPRICET DECIMAL,
 _enable INT(2) DEFAULT 1);

-- INVOICEPAYMENT
CREATE TABLE INVOICEPAYMENT
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 SERIALNUMBER VARCHAR(255),
 INVOICEID BIGINT(38),
 PAYAMOUNT DECIMAL,
 TYPE INT(2),
 _enable INT(2) DEFAULT 1);

-- TRANSACTION
CREATE TABLE TRANSACTION
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 PARTYID BIGINT(38),
 INVOICEID BIGINT(38),
 AMOUNT DECIMAL,
 PLUSTAX DECIMAL,
 COMMENTS VARCHAR(255),
 TYPE INT(2),
 _enable INT(2) DEFAULT 1,
 _version INT(2) DEFAULT 0,
 _starttime TIMESTAMP,
 _endtime TIMESTAMP,
 _optuserid BIGINT(38) DEFAULT 0);

-- DOUBLEENTRY
CREATE TABLE DOUBLEENTRY
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 RELATEDTRANSID BIGINT(38),
 ISLENDED TINYINT(1),
 AMOUNT DECIMAL,
 COMMENTS VARCHAR(255),
 TYPE INT(2),
 _enable INT(2) DEFAULT 1);

-- BUDGET
CREATE TABLE BUDGET
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 DATETYPE INT(2),
 STARTDATE DATETIME,
 ENDDATE DATETIME,
 PARTYTYPE VARCHAR(255),
 ISROLLING TINYINT(1),
 TYPE INT(2),
 STATE INT(2),
 COMMENTS VARCHAR(255),
 _enable INT(2) DEFAULT 1);

-- BUDGETITEM
CREATE TABLE BUDGETITEM
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 AMOUNT DECIMAL,
 REASON VARCHAR(255),
 _enable INT(2) DEFAULT 1);

-- INBALANCESHEET
CREATE TABLE INBALANCESHEET
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 TRANSID BIGINT(38),
 _enable INT(2) DEFAULT 1,
 _version INT(2) DEFAULT 0,
 _starttime TIMESTAMP,
 _endtime TIMESTAMP,
 _optuserid BIGINT(38) DEFAULT 0);

-- PROFITSHEET
CREATE TABLE PROFITSHEET
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 TRANSID BIGINT(38),
 _enable INT(2) DEFAULT 1,
 _version INT(2) DEFAULT 0,
 _starttime TIMESTAMP,
 _endtime TIMESTAMP,
 _optuserid BIGINT(38) DEFAULT 0);

-- CASHFLOWSHEET
CREATE TABLE CASHFLOWSHEET
(ID BIGINT(38) NOT NULL AUTO_INCREMENT,
 TRANSID BIGINT(38),
 _enable INT(2) DEFAULT 1,
 _version INT(2) DEFAULT 0,
 _starttime TIMESTAMP,
 _endtime TIMESTAMP,
 _optuserid BIGINT(38) DEFAULT 0);

