/*
 *
 * This file is automatically generated on Sun Jul 19 23:56:26 CST 2015
 */

    
package org.shaolin.vogerp.accounting.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;

import org.shaolin.vogerp.accounting.ce.*;


/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public class BudgetImpl  implements org.shaolin.vogerp.accounting.be.IBudget
{
    private static final long serialVersionUID = 0x90B1123CE87B50FFL;

    private final IConstantService ceService = AppContext.get().getConstantService();

    protected String getBusinessEntityName()
    {
        return "org.shaolin.vogerp.accounting.be.Budget";
    }

    public BudgetImpl()
    {
        
        items = new java.util.ArrayList<IBudgetItem>();
            
        _extField = new BEExtensionInfo();
        
    }
    
    
        /**
     * Enable record
     */
    private boolean _enable = true;


    /**
     *  BEExtension _extType
     */
    protected String _extType;

    /**
     *  BEExtension _extField
     */
    protected BEExtensionInfo _extField;
        
   /**
     *  help is not available
     */    
    protected long id;
    
   /**
     *  help is not available
     */    
    protected BudgetDateType dateType = BudgetDateType.NOT_SPECIFIED;
    
    protected int dateTypeInt = BudgetDateType.NOT_SPECIFIED.getIntValue();
    
   /**
     *  help is not available
     */    
    protected java.util.Date startDate;
    
   /**
     *  help is not available
     */    
    protected java.util.Date endDate;
    
   /**
     *  help is not available
     */    
    protected java.lang.String partyType;
    
   /**
     *  help is not available
     */    
    protected boolean isRolling;
    
   /**
     *  help is not available
     */    
    protected ClassifyOfAccounts type = ClassifyOfAccounts.NOT_SPECIFIED;
    
    protected int typeInt = ClassifyOfAccounts.NOT_SPECIFIED.getIntValue();
    
   /**
     *  help is not available
     */    
    protected BudgetStatusType state = BudgetStatusType.NOT_SPECIFIED;
    
    protected int stateInt = BudgetStatusType.NOT_SPECIFIED.getIntValue();
    
   /**
     *  help is not available
     */    
    protected java.util.List<IBudgetItem> items;
    
   /**
     *  help is not available
     */    
    protected java.lang.String comments;
    
        /**
     *  Is enable
     *
     *  @return boolean
     */
    public boolean isEnabled() {
        return _enable;
    }
            /**
     *  Is enable
     *
     *  @return boolean
     */
    private boolean get_enable() {
        return _enable;
    }
        
    /**
     *  get _extType
     *
     *  @return _extType
     */
    public String get_extType() {
        return _extType;
    }

    /**
     *  get _extField
     *
     *  @return _extField
     */
    public BEExtensionInfo get_extField() {
        return _extField;
    }
        
    /**
     *  get id
     *
     *  @return id
     */
    public long getId() {
        return id;
    }

    /**
     *  get dateType
     *
     *  @return dateType
     */
    public BudgetDateType getDateType() {
        return dateType;
    }

    /**
     *  get dateTypeInt
     *
     *  @return dateTypeInt
     */
    private int getDateTypeInt() {
        return dateTypeInt;
    }

    /**
     *  get startDate
     *
     *  @return startDate
     */
    public java.util.Date getStartDate() {
        return startDate;
    }

    /**
     *  get endDate
     *
     *  @return endDate
     */
    public java.util.Date getEndDate() {
        return endDate;
    }

    /**
     *  get partyType
     *
     *  @return partyType
     */
    public java.lang.String getPartyType() {
        return partyType;
    }

    /**
     *  get isRolling
     *
     *  @return isRolling
     */
    public boolean getIsRolling() {
        return isRolling;
    }

    /**
     *  get type
     *
     *  @return type
     */
    public ClassifyOfAccounts getType() {
        return type;
    }

    /**
     *  get typeInt
     *
     *  @return typeInt
     */
    private int getTypeInt() {
        return typeInt;
    }

    /**
     *  get state
     *
     *  @return state
     */
    public BudgetStatusType getState() {
        return state;
    }

    /**
     *  get stateInt
     *
     *  @return stateInt
     */
    private int getStateInt() {
        return stateInt;
    }

    /**
     *  get items
     *
     *  @return items
     */
    public java.util.List<IBudgetItem> getItems() {
        return items;
    }

    /**
     *  get comments
     *
     *  @return comments
     */
    public java.lang.String getComments() {
        return comments;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    public void setEnabled(boolean enable) {
        _enable = enable;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    private void set_enable(boolean enable) {
        _enable = enable;
    }

    /**
     *  set _extType
     *  @param _extType which is the extension type of be object.
     */
    public void set_extType(java.lang.String _extType) {
        this._extType = _extType;
    }
        
    /**
     *  set id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     *  set dateType
     */
    public void setDateType(BudgetDateType dateType) {
        this.dateType = dateType;
    if (dateTypeInt != dateType.getIntValue()) {
            dateTypeInt = dateType.getIntValue();
        }
    }

    /**
     *  set int dateType
     */
    private void setDateTypeInt(int intValue) {
        this.dateTypeInt = intValue;
        if (dateTypeInt != dateType.getIntValue()) {
            dateType = (BudgetDateType)ceService.getConstantEntity(BudgetDateType.ENTITY_NAME).getByIntValue(dateTypeInt);
        }
    }

    /**
     *  set startDate
     */
    public void setStartDate(java.util.Date startDate) {
        this.startDate = startDate;
    }

    /**
     *  set endDate
     */
    public void setEndDate(java.util.Date endDate) {
        this.endDate = endDate;
    }

    /**
     *  set partyType
     */
    public void setPartyType(java.lang.String partyType) {
        this.partyType = partyType;
    }

    /**
     *  set isRolling
     */
    public void setIsRolling(boolean isRolling) {
        this.isRolling = isRolling;
    }

    /**
     *  set type
     */
    public void setType(ClassifyOfAccounts type) {
        this.type = type;
    if (typeInt != type.getIntValue()) {
            typeInt = type.getIntValue();
        }
    }

    /**
     *  set int type
     */
    private void setTypeInt(int intValue) {
        this.typeInt = intValue;
        if (typeInt != type.getIntValue()) {
            type = (ClassifyOfAccounts)ceService.getConstantEntity(ClassifyOfAccounts.ENTITY_NAME).getByIntValue(typeInt);
        }
    }

    /**
     *  set state
     */
    public void setState(BudgetStatusType state) {
        this.state = state;
    if (stateInt != state.getIntValue()) {
            stateInt = state.getIntValue();
        }
    }

    /**
     *  set int state
     */
    private void setStateInt(int intValue) {
        this.stateInt = intValue;
        if (stateInt != state.getIntValue()) {
            state = (BudgetStatusType)ceService.getConstantEntity(BudgetStatusType.ENTITY_NAME).getByIntValue(stateInt);
        }
    }

    /**
     *  set items
     */
    public void setItems(java.util.List<IBudgetItem> items) {
        this.items = items;
    }

    /**
     *  set comments
     */
    public void setComments(java.lang.String comments) {
        this.comments = comments;
    }

    
    /**
     * Check different according to primary key.
     */
    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof org.shaolin.vogerp.accounting.be.BudgetImpl))
            return false;
        org.shaolin.vogerp.accounting.be.BudgetImpl o = (org.shaolin.vogerp.accounting.be.BudgetImpl)obj;
        
        boolean result = super.equals(obj);

        boolean eq = true;
        
        return result;
    }

    /**
     * Generate hashCode according to primary key.
     */
    public int hashCode() {
        
        int result = super.hashCode();

        return result;
    }
        
    
     /**
     * Gets the String format of the business entity.
     *
     * @return String the business entity in String format.
     */
    public  String  toString() {
        StringBuffer aBuf = new StringBuffer();
        aBuf.append("org.shaolin.vogerp.accounting.be.Budget");
    
        aBuf.append(" : ");
        
        aBuf.append("enable=").append(_enable).append(", ");
        
        aBuf.append("id");
        aBuf.append("=");
        aBuf.append(id);
        aBuf.append(", ");
        
        aBuf.append("dateType");
        aBuf.append("=");
        aBuf.append(dateType);
        aBuf.append(", ");
        
        aBuf.append("startDate");
        aBuf.append("=");
        aBuf.append(startDate);
        aBuf.append(", ");
        
        aBuf.append("endDate");
        aBuf.append("=");
        aBuf.append(endDate);
        aBuf.append(", ");
        
        aBuf.append("partyType");
        aBuf.append("=");
        aBuf.append(partyType);
        aBuf.append(", ");
        
        aBuf.append("isRolling");
        aBuf.append("=");
        aBuf.append(isRolling);
        aBuf.append(", ");
        
        aBuf.append("type");
        aBuf.append("=");
        aBuf.append(type);
        aBuf.append(", ");
        
        aBuf.append("state");
        aBuf.append("=");
        aBuf.append(state);
        aBuf.append(", ");
        
        aBuf.append("comments");
        aBuf.append("=");
        aBuf.append(comments);
        aBuf.append(", ");
        
        return aBuf.toString();
    }
    
    
     /**
     * Gets list of MemberType.
     *
     * @return List     the list of MemberType.
     */
    public List<MemberType> getMemberList() {
        List<MemberType> memberTypeList = new ArrayList<MemberType>();
        
        MemberType member = null;
        
        org.shaolin.bmdp.datamodel.bediagram.LongType idBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for id
        member = new MemberType();
        member.setName("id");
        member.setDescription("null");
        member.setType(idBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.CEObjRefType dateTypeBEType = new org.shaolin.bmdp.datamodel.bediagram.CEObjRefType();
    
        TargetEntityType dateTypeTargetEntity = new TargetEntityType();
        dateTypeBEType.setTargetEntity(dateTypeTargetEntity);
        dateTypeTargetEntity.setEntityName("org.shaolin.vogerp.accounting.ce.BudgetDateType");
            
        //MemberType Define for dateType
        member = new MemberType();
        member.setName("dateType");
        member.setDescription("null");
        member.setType(dateTypeBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.DateTimeType startDateBEType = new org.shaolin.bmdp.datamodel.bediagram.DateTimeType();
    
        //MemberType Define for startDate
        member = new MemberType();
        member.setName("startDate");
        member.setDescription("null");
        member.setType(startDateBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.DateTimeType endDateBEType = new org.shaolin.bmdp.datamodel.bediagram.DateTimeType();
    
        //MemberType Define for endDate
        member = new MemberType();
        member.setName("endDate");
        member.setDescription("null");
        member.setType(endDateBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType partyTypeBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for partyType
        member = new MemberType();
        member.setName("partyType");
        member.setDescription("null");
        member.setType(partyTypeBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.BooleanType isRollingBEType = new org.shaolin.bmdp.datamodel.bediagram.BooleanType();
    
        //MemberType Define for isRolling
        member = new MemberType();
        member.setName("isRolling");
        member.setDescription("null");
        member.setType(isRollingBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.CEObjRefType typeBEType = new org.shaolin.bmdp.datamodel.bediagram.CEObjRefType();
    
        TargetEntityType typeTargetEntity = new TargetEntityType();
        typeBEType.setTargetEntity(typeTargetEntity);
        typeTargetEntity.setEntityName("org.shaolin.vogerp.accounting.ce.ClassifyOfAccounts");
            
        //MemberType Define for type
        member = new MemberType();
        member.setName("type");
        member.setDescription("null");
        member.setType(typeBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.CEObjRefType stateBEType = new org.shaolin.bmdp.datamodel.bediagram.CEObjRefType();
    
        TargetEntityType stateTargetEntity = new TargetEntityType();
        stateBEType.setTargetEntity(stateTargetEntity);
        stateTargetEntity.setEntityName("org.shaolin.vogerp.accounting.ce.BudgetStatusType");
            
        //MemberType Define for state
        member = new MemberType();
        member.setName("state");
        member.setDescription("null");
        member.setType(stateBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.BEListType itemsBEType = new org.shaolin.bmdp.datamodel.bediagram.BEListType();
    
        org.shaolin.bmdp.datamodel.bediagram.BEObjRefType itemsElementBEType = new org.shaolin.bmdp.datamodel.bediagram.BEObjRefType();
    
        TargetEntityType itemsElementTargetEntity = new TargetEntityType();
        itemsElementTargetEntity.setEntityName("org.shaolin.vogerp.accounting.be.BudgetItem");
        itemsElementBEType.setTargetEntity(itemsElementTargetEntity);
            
        itemsBEType.setElementType(itemsElementBEType);
            
        //MemberType Define for items
        member = new MemberType();
        member.setName("items");
        member.setDescription("null");
        member.setType(itemsBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType commentsBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for comments
        member = new MemberType();
        member.setName("comments");
        member.setDescription("null");
        member.setType(commentsBEType);
        memberTypeList.add(member);
            
        return memberTypeList;
    }
    
    public IBudget createEntity ()
    {
        return new BudgetImpl();
    }
    
}

        

