/*
 *
 * This file is automatically generated on Sun Jul 19 23:56:26 CST 2015
 */

    
package org.shaolin.vogerp.accounting.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;

import org.shaolin.vogerp.accounting.ce.*;


/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public interface IBudget 
    extends IPersistentEntity, IExtensibleEntity
{
    public final static String ENTITY_NAME = "org.shaolin.vogerp.accounting.be.Budget";
    
 
    /**
     *  get id
     *
     *  @return id
     */
    public long getId();

    /**
     *  get dateType
     *
     *  @return dateType
     */
    public BudgetDateType getDateType();

    /**
     *  get startDate
     *
     *  @return startDate
     */
    public java.util.Date getStartDate();

    /**
     *  get endDate
     *
     *  @return endDate
     */
    public java.util.Date getEndDate();

    /**
     *  get partyType
     *
     *  @return partyType
     */
    public java.lang.String getPartyType();

    /**
     *  get isRolling
     *
     *  @return isRolling
     */
    public boolean getIsRolling();

    /**
     *  get type
     *
     *  @return type
     */
    public ClassifyOfAccounts getType();

    /**
     *  get state
     *
     *  @return state
     */
    public BudgetStatusType getState();

    /**
     *  get items
     *
     *  @return items
     */
    public java.util.List<IBudgetItem> getItems();

    /**
     *  get comments
     *
     *  @return comments
     */
    public java.lang.String getComments();

    /**
     *  set id
     */
    public void setId(long id);

    /**
     *  set dateType
     */
    public void setDateType(BudgetDateType dateType);

    /**
     *  set startDate
     */
    public void setStartDate(java.util.Date startDate);

    /**
     *  set endDate
     */
    public void setEndDate(java.util.Date endDate);

    /**
     *  set partyType
     */
    public void setPartyType(java.lang.String partyType);

    /**
     *  set isRolling
     */
    public void setIsRolling(boolean isRolling);

    /**
     *  set type
     */
    public void setType(ClassifyOfAccounts type);

    /**
     *  set state
     */
    public void setState(BudgetStatusType state);

    /**
     *  set items
     */
    public void setItems(java.util.List<IBudgetItem> items);

    /**
     *  set comments
     */
    public void setComments(java.lang.String comments);


}

        