/*
 *
 * This file is automatically generated on Sun Jul 19 23:56:30 CST 2015
 */

    
package org.shaolin.vogerp.accounting.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;

import org.shaolin.vogerp.accounting.ce.*;


/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public interface IInvoicePayment 
    extends IPersistentEntity, IExtensibleEntity
{
    public final static String ENTITY_NAME = "org.shaolin.vogerp.accounting.be.InvoicePayment";
    
 
    /**
     *  get id
     *
     *  @return id
     */
    public long getId();

    /**
     *  get serialNumber
     *
     *  @return serialNumber
     */
    public java.lang.String getSerialNumber();

    /**
     *  get invoiceId
     *
     *  @return invoiceId
     */
    public long getInvoiceId();

    /**
     *  get payAmount
     *
     *  @return payAmount
     */
    public double getPayAmount();

    /**
     *  get type
     *
     *  @return type
     */
    public PaymentMethodsType getType();

    /**
     *  set id
     */
    public void setId(long id);

    /**
     *  set serialNumber
     */
    public void setSerialNumber(java.lang.String serialNumber);

    /**
     *  set invoiceId
     */
    public void setInvoiceId(long invoiceId);

    /**
     *  set payAmount
     */
    public void setPayAmount(double payAmount);

    /**
     *  set type
     */
    public void setType(PaymentMethodsType type);


}

        