/*
 *
 * This file is automatically generated on Sun Jul 19 23:56:29 CST 2015
 */

    
package org.shaolin.vogerp.accounting.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;

import org.shaolin.vogerp.accounting.ce.*;


/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public interface IInvoiceItem 
    extends IPersistentEntity, IExtensibleEntity
{
    public final static String ENTITY_NAME = "org.shaolin.vogerp.accounting.be.InvoiceItem";
    
 
    /**
     *  get id
     *
     *  @return id
     */
    public long getId();

    /**
     *  get invoiceId
     *
     *  @return invoiceId
     */
    public long getInvoiceId();

    /**
     *  get productId
     *
     *  @return productId
     */
    public long getProductId();

    /**
     *  get amount
     *
     *  @return amount
     */
    public int getAmount();

    /**
     *  get unitPrice
     *
     *  @return unitPrice
     */
    public double getUnitPrice();

    /**
     *  get type
     *
     *  @return type
     */
    public InvoiceItemType getType();

    /**
     *  get isAdjusted
     *
     *  @return isAdjusted
     */
    public boolean getIsAdjusted();

    /**
     *  get statement
     *
     *  @return statement
     */
    public java.lang.String getStatement();

    /**
     *  set id
     */
    public void setId(long id);

    /**
     *  set invoiceId
     */
    public void setInvoiceId(long invoiceId);

    /**
     *  set productId
     */
    public void setProductId(long productId);

    /**
     *  set amount
     */
    public void setAmount(int amount);

    /**
     *  set unitPrice
     */
    public void setUnitPrice(double unitPrice);

    /**
     *  set type
     */
    public void setType(InvoiceItemType type);

    /**
     *  set isAdjusted
     */
    public void setIsAdjusted(boolean isAdjusted);

    /**
     *  set statement
     */
    public void setStatement(java.lang.String statement);


}

        