/*
 *
 * This file is automatically generated on Sun Jul 19 23:56:30 CST 2015
 */

    
package org.shaolin.vogerp.accounting.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;

import org.shaolin.vogerp.accounting.ce.*;


/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public class InvoicePaymentImpl  implements org.shaolin.vogerp.accounting.be.IInvoicePayment
{
    private static final long serialVersionUID = 0x90B1123CE87B50FFL;

    private final IConstantService ceService = AppContext.get().getConstantService();

    protected String getBusinessEntityName()
    {
        return "org.shaolin.vogerp.accounting.be.InvoicePayment";
    }

    public InvoicePaymentImpl()
    {
        
        _extField = new BEExtensionInfo();
        
    }
    
    
        /**
     * Enable record
     */
    private boolean _enable = true;


    /**
     *  BEExtension _extType
     */
    protected String _extType;

    /**
     *  BEExtension _extField
     */
    protected BEExtensionInfo _extField;
        
   /**
     *  help is not available
     */    
    protected long id;
    
   /**
     *  help is not available
     */    
    protected java.lang.String serialNumber;
    
   /**
     *  help is not available
     */    
    protected long invoiceId;
    
   /**
     *  help is not available
     */    
    protected double payAmount;
    
   /**
     *  help is not available
     */    
    protected PaymentMethodsType type = PaymentMethodsType.NOT_SPECIFIED;
    
    protected int typeInt = PaymentMethodsType.NOT_SPECIFIED.getIntValue();
    
        /**
     *  Is enable
     *
     *  @return boolean
     */
    public boolean isEnabled() {
        return _enable;
    }
            /**
     *  Is enable
     *
     *  @return boolean
     */
    private boolean get_enable() {
        return _enable;
    }
        
    /**
     *  get _extType
     *
     *  @return _extType
     */
    public String get_extType() {
        return _extType;
    }

    /**
     *  get _extField
     *
     *  @return _extField
     */
    public BEExtensionInfo get_extField() {
        return _extField;
    }
        
    /**
     *  get id
     *
     *  @return id
     */
    public long getId() {
        return id;
    }

    /**
     *  get serialNumber
     *
     *  @return serialNumber
     */
    public java.lang.String getSerialNumber() {
        return serialNumber;
    }

    /**
     *  get invoiceId
     *
     *  @return invoiceId
     */
    public long getInvoiceId() {
        return invoiceId;
    }

    /**
     *  get payAmount
     *
     *  @return payAmount
     */
    public double getPayAmount() {
        return payAmount;
    }

    /**
     *  get type
     *
     *  @return type
     */
    public PaymentMethodsType getType() {
        return type;
    }

    /**
     *  get typeInt
     *
     *  @return typeInt
     */
    private int getTypeInt() {
        return typeInt;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    public void setEnabled(boolean enable) {
        _enable = enable;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    private void set_enable(boolean enable) {
        _enable = enable;
    }

    /**
     *  set _extType
     *  @param _extType which is the extension type of be object.
     */
    public void set_extType(java.lang.String _extType) {
        this._extType = _extType;
    }
        
    /**
     *  set id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     *  set serialNumber
     */
    public void setSerialNumber(java.lang.String serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     *  set invoiceId
     */
    public void setInvoiceId(long invoiceId) {
        this.invoiceId = invoiceId;
    }

    /**
     *  set payAmount
     */
    public void setPayAmount(double payAmount) {
        this.payAmount = payAmount;
    }

    /**
     *  set type
     */
    public void setType(PaymentMethodsType type) {
        this.type = type;
    if (typeInt != type.getIntValue()) {
            typeInt = type.getIntValue();
        }
    }

    /**
     *  set int type
     */
    private void setTypeInt(int intValue) {
        this.typeInt = intValue;
        if (typeInt != type.getIntValue()) {
            type = (PaymentMethodsType)ceService.getConstantEntity(PaymentMethodsType.ENTITY_NAME).getByIntValue(typeInt);
        }
    }

    
    /**
     * Check different according to primary key.
     */
    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof org.shaolin.vogerp.accounting.be.InvoicePaymentImpl))
            return false;
        org.shaolin.vogerp.accounting.be.InvoicePaymentImpl o = (org.shaolin.vogerp.accounting.be.InvoicePaymentImpl)obj;
        
        boolean result = super.equals(obj);

        boolean eq = true;
        
        return result;
    }

    /**
     * Generate hashCode according to primary key.
     */
    public int hashCode() {
        
        int result = super.hashCode();

        return result;
    }
        
    
     /**
     * Gets the String format of the business entity.
     *
     * @return String the business entity in String format.
     */
    public  String  toString() {
        StringBuffer aBuf = new StringBuffer();
        aBuf.append("org.shaolin.vogerp.accounting.be.InvoicePayment");
    
        aBuf.append(" : ");
        
        aBuf.append("enable=").append(_enable).append(", ");
        
        aBuf.append("id");
        aBuf.append("=");
        aBuf.append(id);
        aBuf.append(", ");
        
        aBuf.append("serialNumber");
        aBuf.append("=");
        aBuf.append(serialNumber);
        aBuf.append(", ");
        
        aBuf.append("invoiceId");
        aBuf.append("=");
        aBuf.append(invoiceId);
        aBuf.append(", ");
        
        aBuf.append("payAmount");
        aBuf.append("=");
        aBuf.append(payAmount);
        aBuf.append(", ");
        
        aBuf.append("type");
        aBuf.append("=");
        aBuf.append(type);
        aBuf.append(", ");
        
        return aBuf.toString();
    }
    
    
     /**
     * Gets list of MemberType.
     *
     * @return List     the list of MemberType.
     */
    public List<MemberType> getMemberList() {
        List<MemberType> memberTypeList = new ArrayList<MemberType>();
        
        MemberType member = null;
        
        org.shaolin.bmdp.datamodel.bediagram.LongType idBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for id
        member = new MemberType();
        member.setName("id");
        member.setDescription("null");
        member.setType(idBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType serialNumberBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for serialNumber
        member = new MemberType();
        member.setName("serialNumber");
        member.setDescription("null");
        member.setType(serialNumberBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.LongType invoiceIdBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for invoiceId
        member = new MemberType();
        member.setName("invoiceId");
        member.setDescription("null");
        member.setType(invoiceIdBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.DoubleType payAmountBEType = new org.shaolin.bmdp.datamodel.bediagram.DoubleType();
    
        //MemberType Define for payAmount
        member = new MemberType();
        member.setName("payAmount");
        member.setDescription("null");
        member.setType(payAmountBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.CEObjRefType typeBEType = new org.shaolin.bmdp.datamodel.bediagram.CEObjRefType();
    
        TargetEntityType typeTargetEntity = new TargetEntityType();
        typeBEType.setTargetEntity(typeTargetEntity);
        typeTargetEntity.setEntityName("org.shaolin.vogerp.accounting.ce.PaymentMethodsType");
            
        //MemberType Define for type
        member = new MemberType();
        member.setName("type");
        member.setDescription("null");
        member.setType(typeBEType);
        memberTypeList.add(member);
            
        return memberTypeList;
    }
    
    public IInvoicePayment createEntity ()
    {
        return new InvoicePaymentImpl();
    }
    
}

        

