/*
 *
 * This file is automatically generated on Sun Jul 19 23:56:29 CST 2015
 */

    
package org.shaolin.vogerp.accounting.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;

import org.shaolin.vogerp.accounting.ce.*;


/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public class InvoiceImpl  implements org.shaolin.vogerp.accounting.be.IInvoice
{
    private static final long serialVersionUID = 0x90B1123CE87B50FFL;

    private final IConstantService ceService = AppContext.get().getConstantService();

    protected String getBusinessEntityName()
    {
        return "org.shaolin.vogerp.accounting.be.Invoice";
    }

    public InvoiceImpl()
    {
        
        _extField = new BEExtensionInfo();
        
    }
    
    
        /**
     * Enable record
     */
    private boolean _enable = true;


    /**
     * History version
     */
    protected int _version = 0;

    /**
     * History starttime
     */
    private java.util.Date _starttime = new java.util.Date();

    /**
     * History endtime
     */
    private java.util.Date _endtime = null;

    /**
     * History _optuserid
     */
    private long _optuserid = 0L;


    /**
     *  BEExtension _extType
     */
    protected String _extType;

    /**
     *  BEExtension _extField
     */
    protected BEExtensionInfo _extField;
        
   /**
     *  help is not available
     */    
    protected long id;
    
   /**
     *  help is not available
     */    
    protected java.lang.String serialNumber;
    
   /**
     *  help is not available
     */    
    protected java.lang.String customerInfo;
    
   /**
     *  help is not available
     */    
    protected java.lang.String description;
    
   /**
     *  help is not available
     */    
    protected java.util.Date createDate;
    
   /**
     *  help is not available
     */    
    protected InvoiceRoleType role = InvoiceRoleType.NOT_SPECIFIED;
    
    protected int roleInt = InvoiceRoleType.NOT_SPECIFIED.getIntValue();
    
   /**
     *  help is not available
     */    
    protected InvoiceStatusType status = InvoiceStatusType.NOT_SPECIFIED;
    
    protected int statusInt = InvoiceStatusType.NOT_SPECIFIED.getIntValue();
    
   /**
     *  help is not available
     */    
    protected long paymentPartyId;
    
   /**
     *  help is not available
     */    
    protected java.lang.String source;
    
   /**
     *  help is not available
     */    
    protected long targetPartyId;
    
   /**
     *  help is not available
     */    
    protected java.lang.String destination;
    
        /**
     *  Is enable
     *
     *  @return boolean
     */
    public boolean isEnabled() {
        return _enable;
    }
            /**
     *  Is enable
     *
     *  @return boolean
     */
    private boolean get_enable() {
        return _enable;
    }
        
    /**
     *  get version
     *
     *  @return version
     */
    public int getVersion() {
        return _version;
    }

    private int get_version() {
        return _version;
    }

    /**
     *  get operator user id
     *
     *  @return user id
     */
    public long getOptUserId() {
        return _optuserid;
    }

    /**
     *  get operator user id
     *
     *  @return user id
     */
    private long get_optuserid() {
        return _optuserid;
    }

    /**
     *  get start time
     *
     *  @return start time
     */
    public java.util.Date getStarttime() {
        return _starttime;
    }

    private java.util.Date get_starttime() {
        return _starttime;
    }

    /**
     *  get endtime
     *
     *  @return endtime
     */
    public java.util.Date getEndtime() {
        return _endtime;
    }

    private java.util.Date get_endtime() {
        return _endtime;
    }


    /**
     *  get _extType
     *
     *  @return _extType
     */
    public String get_extType() {
        return _extType;
    }

    /**
     *  get _extField
     *
     *  @return _extField
     */
    public BEExtensionInfo get_extField() {
        return _extField;
    }
        
    /**
     *  get id
     *
     *  @return id
     */
    public long getId() {
        return id;
    }

    /**
     *  get serialNumber
     *
     *  @return serialNumber
     */
    public java.lang.String getSerialNumber() {
        return serialNumber;
    }

    /**
     *  get customerInfo
     *
     *  @return customerInfo
     */
    public java.lang.String getCustomerInfo() {
        return customerInfo;
    }

    /**
     *  get description
     *
     *  @return description
     */
    public java.lang.String getDescription() {
        return description;
    }

    /**
     *  get createDate
     *
     *  @return createDate
     */
    public java.util.Date getCreateDate() {
        return createDate;
    }

    /**
     *  get role
     *
     *  @return role
     */
    public InvoiceRoleType getRole() {
        return role;
    }

    /**
     *  get roleInt
     *
     *  @return roleInt
     */
    private int getRoleInt() {
        return roleInt;
    }

    /**
     *  get status
     *
     *  @return status
     */
    public InvoiceStatusType getStatus() {
        return status;
    }

    /**
     *  get statusInt
     *
     *  @return statusInt
     */
    private int getStatusInt() {
        return statusInt;
    }

    /**
     *  get paymentPartyId
     *
     *  @return paymentPartyId
     */
    public long getPaymentPartyId() {
        return paymentPartyId;
    }

    /**
     *  get source
     *
     *  @return source
     */
    public java.lang.String getSource() {
        return source;
    }

    /**
     *  get targetPartyId
     *
     *  @return targetPartyId
     */
    public long getTargetPartyId() {
        return targetPartyId;
    }

    /**
     *  get destination
     *
     *  @return destination
     */
    public java.lang.String getDestination() {
        return destination;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    public void setEnabled(boolean enable) {
        _enable = enable;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    private void set_enable(boolean enable) {
        _enable = enable;
    }

    
    /**
     *  set version
     */
    public void setVersion(int version) {
        _version = version;
    }

    private void set_version(int version) {
        _version = version;
    }

    /**
     *  set operator user id
     *  @parameter user id.
     */
    public void setOptUserId(long optUserId) {
        _optuserid = optUserId;
    }

    /**
     *  set operator user id
     *  @parameter user id.
     */
    private void set_optuserid(long optUserId) {
        _optuserid = optUserId;
    }

    /**
     *  set start time
     *  @parameter start time which is the start time of object.
     */
    public void setStarttime(java.util.Date starttime) {
        _starttime = starttime;
    }

    private void set_starttime(java.util.Date starttime) {
        _starttime = starttime;
    }

    /**
     *  set endtime
     *  @parameter endtime which is the end time of object.
     */
    public void setEndtime(java.util.Date endtime) {
        _endtime = endtime;
    }

    private void set_endtime(java.util.Date endtime) {
        _endtime = endtime;
    }

/**
     *  set _extType
     *  @param _extType which is the extension type of be object.
     */
    public void set_extType(java.lang.String _extType) {
        this._extType = _extType;
    }
        
    /**
     *  set id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     *  set serialNumber
     */
    public void setSerialNumber(java.lang.String serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     *  set customerInfo
     */
    public void setCustomerInfo(java.lang.String customerInfo) {
        this.customerInfo = customerInfo;
    }

    /**
     *  set description
     */
    public void setDescription(java.lang.String description) {
        this.description = description;
    }

    /**
     *  set createDate
     */
    public void setCreateDate(java.util.Date createDate) {
        this.createDate = createDate;
    }

    /**
     *  set role
     */
    public void setRole(InvoiceRoleType role) {
        this.role = role;
    if (roleInt != role.getIntValue()) {
            roleInt = role.getIntValue();
        }
    }

    /**
     *  set int role
     */
    private void setRoleInt(int intValue) {
        this.roleInt = intValue;
        if (roleInt != role.getIntValue()) {
            role = (InvoiceRoleType)ceService.getConstantEntity(InvoiceRoleType.ENTITY_NAME).getByIntValue(roleInt);
        }
    }

    /**
     *  set status
     */
    public void setStatus(InvoiceStatusType status) {
        this.status = status;
    if (statusInt != status.getIntValue()) {
            statusInt = status.getIntValue();
        }
    }

    /**
     *  set int status
     */
    private void setStatusInt(int intValue) {
        this.statusInt = intValue;
        if (statusInt != status.getIntValue()) {
            status = (InvoiceStatusType)ceService.getConstantEntity(InvoiceStatusType.ENTITY_NAME).getByIntValue(statusInt);
        }
    }

    /**
     *  set paymentPartyId
     */
    public void setPaymentPartyId(long paymentPartyId) {
        this.paymentPartyId = paymentPartyId;
    }

    /**
     *  set source
     */
    public void setSource(java.lang.String source) {
        this.source = source;
    }

    /**
     *  set targetPartyId
     */
    public void setTargetPartyId(long targetPartyId) {
        this.targetPartyId = targetPartyId;
    }

    /**
     *  set destination
     */
    public void setDestination(java.lang.String destination) {
        this.destination = destination;
    }

    
    /**
     * Check different according to primary key.
     */
    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof org.shaolin.vogerp.accounting.be.InvoiceImpl))
            return false;
        org.shaolin.vogerp.accounting.be.InvoiceImpl o = (org.shaolin.vogerp.accounting.be.InvoiceImpl)obj;
        
        boolean result = super.equals(obj);

        boolean eq = true;
        
        return result;
    }

    /**
     * Generate hashCode according to primary key.
     */
    public int hashCode() {
        
        int result = super.hashCode();

        return result;
    }
        
    
     /**
     * Gets the String format of the business entity.
     *
     * @return String the business entity in String format.
     */
    public  String  toString() {
        StringBuffer aBuf = new StringBuffer();
        aBuf.append("org.shaolin.vogerp.accounting.be.Invoice");
    
        aBuf.append(" : ");
        
        aBuf.append("enable=").append(_enable).append(", ");
        
        aBuf.append("id");
        aBuf.append("=");
        aBuf.append(id);
        aBuf.append(", ");
        
        aBuf.append("serialNumber");
        aBuf.append("=");
        aBuf.append(serialNumber);
        aBuf.append(", ");
        
        aBuf.append("customerInfo");
        aBuf.append("=");
        aBuf.append(customerInfo);
        aBuf.append(", ");
        
        aBuf.append("description");
        aBuf.append("=");
        aBuf.append(description);
        aBuf.append(", ");
        
        aBuf.append("createDate");
        aBuf.append("=");
        aBuf.append(createDate);
        aBuf.append(", ");
        
        aBuf.append("role");
        aBuf.append("=");
        aBuf.append(role);
        aBuf.append(", ");
        
        aBuf.append("status");
        aBuf.append("=");
        aBuf.append(status);
        aBuf.append(", ");
        
        aBuf.append("paymentPartyId");
        aBuf.append("=");
        aBuf.append(paymentPartyId);
        aBuf.append(", ");
        
        aBuf.append("source");
        aBuf.append("=");
        aBuf.append(source);
        aBuf.append(", ");
        
        aBuf.append("targetPartyId");
        aBuf.append("=");
        aBuf.append(targetPartyId);
        aBuf.append(", ");
        
        aBuf.append("destination");
        aBuf.append("=");
        aBuf.append(destination);
        aBuf.append(", ");
        
        return aBuf.toString();
    }
    
    
     /**
     * Gets list of MemberType.
     *
     * @return List     the list of MemberType.
     */
    public List<MemberType> getMemberList() {
        List<MemberType> memberTypeList = new ArrayList<MemberType>();
        
        MemberType member = null;
        
        org.shaolin.bmdp.datamodel.bediagram.LongType idBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for id
        member = new MemberType();
        member.setName("id");
        member.setDescription("null");
        member.setType(idBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType serialNumberBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for serialNumber
        member = new MemberType();
        member.setName("serialNumber");
        member.setDescription("null");
        member.setType(serialNumberBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType customerInfoBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for customerInfo
        member = new MemberType();
        member.setName("customerInfo");
        member.setDescription("null");
        member.setType(customerInfoBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType descriptionBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for description
        member = new MemberType();
        member.setName("description");
        member.setDescription("null");
        member.setType(descriptionBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.DateTimeType createDateBEType = new org.shaolin.bmdp.datamodel.bediagram.DateTimeType();
    
        //MemberType Define for createDate
        member = new MemberType();
        member.setName("createDate");
        member.setDescription("null");
        member.setType(createDateBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.CEObjRefType roleBEType = new org.shaolin.bmdp.datamodel.bediagram.CEObjRefType();
    
        TargetEntityType roleTargetEntity = new TargetEntityType();
        roleBEType.setTargetEntity(roleTargetEntity);
        roleTargetEntity.setEntityName("org.shaolin.vogerp.accounting.ce.InvoiceRoleType");
            
        //MemberType Define for role
        member = new MemberType();
        member.setName("role");
        member.setDescription("null");
        member.setType(roleBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.CEObjRefType statusBEType = new org.shaolin.bmdp.datamodel.bediagram.CEObjRefType();
    
        TargetEntityType statusTargetEntity = new TargetEntityType();
        statusBEType.setTargetEntity(statusTargetEntity);
        statusTargetEntity.setEntityName("org.shaolin.vogerp.accounting.ce.InvoiceStatusType");
            
        //MemberType Define for status
        member = new MemberType();
        member.setName("status");
        member.setDescription("null");
        member.setType(statusBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.LongType paymentPartyIdBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for paymentPartyId
        member = new MemberType();
        member.setName("paymentPartyId");
        member.setDescription("null");
        member.setType(paymentPartyIdBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType sourceBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for source
        member = new MemberType();
        member.setName("source");
        member.setDescription("null");
        member.setType(sourceBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.LongType targetPartyIdBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for targetPartyId
        member = new MemberType();
        member.setName("targetPartyId");
        member.setDescription("null");
        member.setType(targetPartyIdBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType destinationBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for destination
        member = new MemberType();
        member.setName("destination");
        member.setDescription("null");
        member.setType(destinationBEType);
        memberTypeList.add(member);
            
        return memberTypeList;
    }
    
    public IInvoice createEntity ()
    {
        return new InvoiceImpl();
    }
    
}

        

