/*
 *
 * This file is automatically generated on Sun Jul 19 23:56:30 CST 2015
 */

    
package org.shaolin.vogerp.accounting.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;



/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public class InvoiceItemWithShipmentImpl  implements org.shaolin.vogerp.accounting.be.IInvoiceItemWithShipment
{
    private static final long serialVersionUID = 0x90B1123CE87B50FFL;

    private final IConstantService ceService = AppContext.get().getConstantService();

    protected String getBusinessEntityName()
    {
        return "org.shaolin.vogerp.accounting.be.InvoiceItemWithShipment";
    }

    public InvoiceItemWithShipmentImpl()
    {
        
        _extField = new BEExtensionInfo();
        
    }
    
    
        /**
     * Enable record
     */
    private boolean _enable = true;


    /**
     *  BEExtension _extType
     */
    protected String _extType;

    /**
     *  BEExtension _extField
     */
    protected BEExtensionInfo _extField;
        
   /**
     *  help is not available
     */    
    protected long id;
    
   /**
     *  help is not available
     */    
    protected long invoiceId;
    
   /**
     *  help is not available
     */    
    protected long invoiceItemId;
    
   /**
     *  help is not available
     */    
    protected long shipmentId;
    
   /**
     *  help is not available
     */    
    protected long shipmentItemId;
    
   /**
     *  help is not available
     */    
    protected int amount;
    
        /**
     *  Is enable
     *
     *  @return boolean
     */
    public boolean isEnabled() {
        return _enable;
    }
            /**
     *  Is enable
     *
     *  @return boolean
     */
    private boolean get_enable() {
        return _enable;
    }
        
    /**
     *  get _extType
     *
     *  @return _extType
     */
    public String get_extType() {
        return _extType;
    }

    /**
     *  get _extField
     *
     *  @return _extField
     */
    public BEExtensionInfo get_extField() {
        return _extField;
    }
        
    /**
     *  get id
     *
     *  @return id
     */
    public long getId() {
        return id;
    }

    /**
     *  get invoiceId
     *
     *  @return invoiceId
     */
    public long getInvoiceId() {
        return invoiceId;
    }

    /**
     *  get invoiceItemId
     *
     *  @return invoiceItemId
     */
    public long getInvoiceItemId() {
        return invoiceItemId;
    }

    /**
     *  get shipmentId
     *
     *  @return shipmentId
     */
    public long getShipmentId() {
        return shipmentId;
    }

    /**
     *  get shipmentItemId
     *
     *  @return shipmentItemId
     */
    public long getShipmentItemId() {
        return shipmentItemId;
    }

    /**
     *  get amount
     *
     *  @return amount
     */
    public int getAmount() {
        return amount;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    public void setEnabled(boolean enable) {
        _enable = enable;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    private void set_enable(boolean enable) {
        _enable = enable;
    }

    /**
     *  set _extType
     *  @param _extType which is the extension type of be object.
     */
    public void set_extType(java.lang.String _extType) {
        this._extType = _extType;
    }
        
    /**
     *  set id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     *  set invoiceId
     */
    public void setInvoiceId(long invoiceId) {
        this.invoiceId = invoiceId;
    }

    /**
     *  set invoiceItemId
     */
    public void setInvoiceItemId(long invoiceItemId) {
        this.invoiceItemId = invoiceItemId;
    }

    /**
     *  set shipmentId
     */
    public void setShipmentId(long shipmentId) {
        this.shipmentId = shipmentId;
    }

    /**
     *  set shipmentItemId
     */
    public void setShipmentItemId(long shipmentItemId) {
        this.shipmentItemId = shipmentItemId;
    }

    /**
     *  set amount
     */
    public void setAmount(int amount) {
        this.amount = amount;
    }

    
    /**
     * Check different according to primary key.
     */
    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof org.shaolin.vogerp.accounting.be.InvoiceItemWithShipmentImpl))
            return false;
        org.shaolin.vogerp.accounting.be.InvoiceItemWithShipmentImpl o = (org.shaolin.vogerp.accounting.be.InvoiceItemWithShipmentImpl)obj;
        
        boolean result = super.equals(obj);

        boolean eq = true;
        
        return result;
    }

    /**
     * Generate hashCode according to primary key.
     */
    public int hashCode() {
        
        int result = super.hashCode();

        return result;
    }
        
    
     /**
     * Gets the String format of the business entity.
     *
     * @return String the business entity in String format.
     */
    public  String  toString() {
        StringBuffer aBuf = new StringBuffer();
        aBuf.append("org.shaolin.vogerp.accounting.be.InvoiceItemWithShipment");
    
        aBuf.append(" : ");
        
        aBuf.append("enable=").append(_enable).append(", ");
        
        aBuf.append("id");
        aBuf.append("=");
        aBuf.append(id);
        aBuf.append(", ");
        
        aBuf.append("invoiceId");
        aBuf.append("=");
        aBuf.append(invoiceId);
        aBuf.append(", ");
        
        aBuf.append("invoiceItemId");
        aBuf.append("=");
        aBuf.append(invoiceItemId);
        aBuf.append(", ");
        
        aBuf.append("shipmentId");
        aBuf.append("=");
        aBuf.append(shipmentId);
        aBuf.append(", ");
        
        aBuf.append("shipmentItemId");
        aBuf.append("=");
        aBuf.append(shipmentItemId);
        aBuf.append(", ");
        
        aBuf.append("amount");
        aBuf.append("=");
        aBuf.append(amount);
        aBuf.append(", ");
        
        return aBuf.toString();
    }
    
    
     /**
     * Gets list of MemberType.
     *
     * @return List     the list of MemberType.
     */
    public List<MemberType> getMemberList() {
        List<MemberType> memberTypeList = new ArrayList<MemberType>();
        
        MemberType member = null;
        
        org.shaolin.bmdp.datamodel.bediagram.LongType idBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for id
        member = new MemberType();
        member.setName("id");
        member.setDescription("null");
        member.setType(idBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.LongType invoiceIdBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for invoiceId
        member = new MemberType();
        member.setName("invoiceId");
        member.setDescription("null");
        member.setType(invoiceIdBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.LongType invoiceItemIdBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for invoiceItemId
        member = new MemberType();
        member.setName("invoiceItemId");
        member.setDescription("null");
        member.setType(invoiceItemIdBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.LongType shipmentIdBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for shipmentId
        member = new MemberType();
        member.setName("shipmentId");
        member.setDescription("null");
        member.setType(shipmentIdBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.LongType shipmentItemIdBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for shipmentItemId
        member = new MemberType();
        member.setName("shipmentItemId");
        member.setDescription("null");
        member.setType(shipmentItemIdBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.IntType amountBEType = new org.shaolin.bmdp.datamodel.bediagram.IntType();
    
        //MemberType Define for amount
        member = new MemberType();
        member.setName("amount");
        member.setDescription("null");
        member.setType(amountBEType);
        memberTypeList.add(member);
            
        return memberTypeList;
    }
    
    public IInvoiceItemWithShipment createEntity ()
    {
        return new InvoiceItemWithShipmentImpl();
    }
    
}

        

