/*
 *
 * This file is automatically generated on Sun Jul 19 23:56:24 CST 2015
 */

    
package org.shaolin.vogerp.accounting.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;

import org.shaolin.vogerp.accounting.ce.*;


/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public interface ITransaction 
    extends IPersistentEntity, IExtensibleEntity
{
    public final static String ENTITY_NAME = "org.shaolin.vogerp.accounting.be.Transaction";
    
 
    /**
     *  get id
     *
     *  @return id
     */
    public long getId();

    /**
     *  get partyId
     *
     *  @return partyId
     */
    public long getPartyId();

    /**
     *  get invoiceId
     *
     *  @return invoiceId
     */
    public long getInvoiceId();

    /**
     *  get amount
     *
     *  @return amount
     */
    public double getAmount();

    /**
     *  get plusTax
     *
     *  @return plusTax
     */
    public double getPlusTax();

    /**
     *  get comments
     *
     *  @return comments
     */
    public java.lang.String getComments();

    /**
     *  get type
     *
     *  @return type
     */
    public ClassifyOfAccounts getType();

    /**
     *  get doubleEnties
     *
     *  @return doubleEnties
     */
    public java.util.List<IDoubleEntry> getDoubleEnties();

    /**
     *  set id
     */
    public void setId(long id);

    /**
     *  set partyId
     */
    public void setPartyId(long partyId);

    /**
     *  set invoiceId
     */
    public void setInvoiceId(long invoiceId);

    /**
     *  set amount
     */
    public void setAmount(double amount);

    /**
     *  set plusTax
     */
    public void setPlusTax(double plusTax);

    /**
     *  set comments
     */
    public void setComments(java.lang.String comments);

    /**
     *  set type
     */
    public void setType(ClassifyOfAccounts type);

    /**
     *  set doubleEnties
     */
    public void setDoubleEnties(java.util.List<IDoubleEntry> doubleEnties);


}

        