/*
 *
 * This file is automatically generated on Sun Jul 19 23:56:24 CST 2015
 */

    
package org.shaolin.vogerp.accounting.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;

import org.shaolin.vogerp.accounting.ce.*;


/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public class TransactionImpl  implements org.shaolin.vogerp.accounting.be.ITransaction
{
    private static final long serialVersionUID = 0x90B1123CE87B50FFL;

    private final IConstantService ceService = AppContext.get().getConstantService();

    protected String getBusinessEntityName()
    {
        return "org.shaolin.vogerp.accounting.be.Transaction";
    }

    public TransactionImpl()
    {
        
        doubleEnties = new java.util.ArrayList<IDoubleEntry>();
            
        _extField = new BEExtensionInfo();
        
    }
    
    
        /**
     * Enable record
     */
    private boolean _enable = true;


    /**
     * History version
     */
    protected int _version = 0;

    /**
     * History starttime
     */
    private java.util.Date _starttime = new java.util.Date();

    /**
     * History endtime
     */
    private java.util.Date _endtime = null;

    /**
     * History _optuserid
     */
    private long _optuserid = 0L;


    /**
     *  BEExtension _extType
     */
    protected String _extType;

    /**
     *  BEExtension _extField
     */
    protected BEExtensionInfo _extField;
        
   /**
     *  help is not available
     */    
    protected long id;
    
   /**
     *  help is not available
     */    
    protected long partyId;
    
   /**
     *  help is not available
     */    
    protected long invoiceId;
    
   /**
     *  help is not available
     */    
    protected double amount;
    
   /**
     *  help is not available
     */    
    protected double plusTax;
    
   /**
     *  help is not available
     */    
    protected java.lang.String comments;
    
   /**
     *  help is not available
     */    
    protected ClassifyOfAccounts type = ClassifyOfAccounts.NOT_SPECIFIED;
    
    protected int typeInt = ClassifyOfAccounts.NOT_SPECIFIED.getIntValue();
    
   /**
     *  help is not available
     */    
    protected java.util.List<IDoubleEntry> doubleEnties;
    
        /**
     *  Is enable
     *
     *  @return boolean
     */
    public boolean isEnabled() {
        return _enable;
    }
            /**
     *  Is enable
     *
     *  @return boolean
     */
    private boolean get_enable() {
        return _enable;
    }
        
    /**
     *  get version
     *
     *  @return version
     */
    public int getVersion() {
        return _version;
    }

    private int get_version() {
        return _version;
    }

    /**
     *  get operator user id
     *
     *  @return user id
     */
    public long getOptUserId() {
        return _optuserid;
    }

    /**
     *  get operator user id
     *
     *  @return user id
     */
    private long get_optuserid() {
        return _optuserid;
    }

    /**
     *  get start time
     *
     *  @return start time
     */
    public java.util.Date getStarttime() {
        return _starttime;
    }

    private java.util.Date get_starttime() {
        return _starttime;
    }

    /**
     *  get endtime
     *
     *  @return endtime
     */
    public java.util.Date getEndtime() {
        return _endtime;
    }

    private java.util.Date get_endtime() {
        return _endtime;
    }


    /**
     *  get _extType
     *
     *  @return _extType
     */
    public String get_extType() {
        return _extType;
    }

    /**
     *  get _extField
     *
     *  @return _extField
     */
    public BEExtensionInfo get_extField() {
        return _extField;
    }
        
    /**
     *  get id
     *
     *  @return id
     */
    public long getId() {
        return id;
    }

    /**
     *  get partyId
     *
     *  @return partyId
     */
    public long getPartyId() {
        return partyId;
    }

    /**
     *  get invoiceId
     *
     *  @return invoiceId
     */
    public long getInvoiceId() {
        return invoiceId;
    }

    /**
     *  get amount
     *
     *  @return amount
     */
    public double getAmount() {
        return amount;
    }

    /**
     *  get plusTax
     *
     *  @return plusTax
     */
    public double getPlusTax() {
        return plusTax;
    }

    /**
     *  get comments
     *
     *  @return comments
     */
    public java.lang.String getComments() {
        return comments;
    }

    /**
     *  get type
     *
     *  @return type
     */
    public ClassifyOfAccounts getType() {
        return type;
    }

    /**
     *  get typeInt
     *
     *  @return typeInt
     */
    private int getTypeInt() {
        return typeInt;
    }

    /**
     *  get doubleEnties
     *
     *  @return doubleEnties
     */
    public java.util.List<IDoubleEntry> getDoubleEnties() {
        return doubleEnties;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    public void setEnabled(boolean enable) {
        _enable = enable;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    private void set_enable(boolean enable) {
        _enable = enable;
    }

    
    /**
     *  set version
     */
    public void setVersion(int version) {
        _version = version;
    }

    private void set_version(int version) {
        _version = version;
    }

    /**
     *  set operator user id
     *  @parameter user id.
     */
    public void setOptUserId(long optUserId) {
        _optuserid = optUserId;
    }

    /**
     *  set operator user id
     *  @parameter user id.
     */
    private void set_optuserid(long optUserId) {
        _optuserid = optUserId;
    }

    /**
     *  set start time
     *  @parameter start time which is the start time of object.
     */
    public void setStarttime(java.util.Date starttime) {
        _starttime = starttime;
    }

    private void set_starttime(java.util.Date starttime) {
        _starttime = starttime;
    }

    /**
     *  set endtime
     *  @parameter endtime which is the end time of object.
     */
    public void setEndtime(java.util.Date endtime) {
        _endtime = endtime;
    }

    private void set_endtime(java.util.Date endtime) {
        _endtime = endtime;
    }

/**
     *  set _extType
     *  @param _extType which is the extension type of be object.
     */
    public void set_extType(java.lang.String _extType) {
        this._extType = _extType;
    }
        
    /**
     *  set id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     *  set partyId
     */
    public void setPartyId(long partyId) {
        this.partyId = partyId;
    }

    /**
     *  set invoiceId
     */
    public void setInvoiceId(long invoiceId) {
        this.invoiceId = invoiceId;
    }

    /**
     *  set amount
     */
    public void setAmount(double amount) {
        this.amount = amount;
    }

    /**
     *  set plusTax
     */
    public void setPlusTax(double plusTax) {
        this.plusTax = plusTax;
    }

    /**
     *  set comments
     */
    public void setComments(java.lang.String comments) {
        this.comments = comments;
    }

    /**
     *  set type
     */
    public void setType(ClassifyOfAccounts type) {
        this.type = type;
    if (typeInt != type.getIntValue()) {
            typeInt = type.getIntValue();
        }
    }

    /**
     *  set int type
     */
    private void setTypeInt(int intValue) {
        this.typeInt = intValue;
        if (typeInt != type.getIntValue()) {
            type = (ClassifyOfAccounts)ceService.getConstantEntity(ClassifyOfAccounts.ENTITY_NAME).getByIntValue(typeInt);
        }
    }

    /**
     *  set doubleEnties
     */
    public void setDoubleEnties(java.util.List<IDoubleEntry> doubleEnties) {
        this.doubleEnties = doubleEnties;
    }

    
    /**
     * Check different according to primary key.
     */
    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof org.shaolin.vogerp.accounting.be.TransactionImpl))
            return false;
        org.shaolin.vogerp.accounting.be.TransactionImpl o = (org.shaolin.vogerp.accounting.be.TransactionImpl)obj;
        
        boolean result = super.equals(obj);

        boolean eq = true;
        
        return result;
    }

    /**
     * Generate hashCode according to primary key.
     */
    public int hashCode() {
        
        int result = super.hashCode();

        return result;
    }
        
    
     /**
     * Gets the String format of the business entity.
     *
     * @return String the business entity in String format.
     */
    public  String  toString() {
        StringBuffer aBuf = new StringBuffer();
        aBuf.append("org.shaolin.vogerp.accounting.be.Transaction");
    
        aBuf.append(" : ");
        
        aBuf.append("enable=").append(_enable).append(", ");
        
        aBuf.append("id");
        aBuf.append("=");
        aBuf.append(id);
        aBuf.append(", ");
        
        aBuf.append("partyId");
        aBuf.append("=");
        aBuf.append(partyId);
        aBuf.append(", ");
        
        aBuf.append("invoiceId");
        aBuf.append("=");
        aBuf.append(invoiceId);
        aBuf.append(", ");
        
        aBuf.append("amount");
        aBuf.append("=");
        aBuf.append(amount);
        aBuf.append(", ");
        
        aBuf.append("plusTax");
        aBuf.append("=");
        aBuf.append(plusTax);
        aBuf.append(", ");
        
        aBuf.append("comments");
        aBuf.append("=");
        aBuf.append(comments);
        aBuf.append(", ");
        
        aBuf.append("type");
        aBuf.append("=");
        aBuf.append(type);
        aBuf.append(", ");
        
        return aBuf.toString();
    }
    
    
     /**
     * Gets list of MemberType.
     *
     * @return List     the list of MemberType.
     */
    public List<MemberType> getMemberList() {
        List<MemberType> memberTypeList = new ArrayList<MemberType>();
        
        MemberType member = null;
        
        org.shaolin.bmdp.datamodel.bediagram.LongType idBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for id
        member = new MemberType();
        member.setName("id");
        member.setDescription("null");
        member.setType(idBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.LongType partyIdBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for partyId
        member = new MemberType();
        member.setName("partyId");
        member.setDescription("null");
        member.setType(partyIdBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.LongType invoiceIdBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for invoiceId
        member = new MemberType();
        member.setName("invoiceId");
        member.setDescription("null");
        member.setType(invoiceIdBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.DoubleType amountBEType = new org.shaolin.bmdp.datamodel.bediagram.DoubleType();
    
        //MemberType Define for amount
        member = new MemberType();
        member.setName("amount");
        member.setDescription("null");
        member.setType(amountBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.DoubleType plusTaxBEType = new org.shaolin.bmdp.datamodel.bediagram.DoubleType();
    
        //MemberType Define for plusTax
        member = new MemberType();
        member.setName("plusTax");
        member.setDescription("null");
        member.setType(plusTaxBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType commentsBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for comments
        member = new MemberType();
        member.setName("comments");
        member.setDescription("null");
        member.setType(commentsBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.CEObjRefType typeBEType = new org.shaolin.bmdp.datamodel.bediagram.CEObjRefType();
    
        TargetEntityType typeTargetEntity = new TargetEntityType();
        typeBEType.setTargetEntity(typeTargetEntity);
        typeTargetEntity.setEntityName("org.shaolin.vogerp.accounting.ce.ClassifyOfAccounts");
            
        //MemberType Define for type
        member = new MemberType();
        member.setName("type");
        member.setDescription("null");
        member.setType(typeBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.BEListType doubleEntiesBEType = new org.shaolin.bmdp.datamodel.bediagram.BEListType();
    
        org.shaolin.bmdp.datamodel.bediagram.BEObjRefType doubleEntiesElementBEType = new org.shaolin.bmdp.datamodel.bediagram.BEObjRefType();
    
        TargetEntityType doubleEntiesElementTargetEntity = new TargetEntityType();
        doubleEntiesElementTargetEntity.setEntityName("org.shaolin.vogerp.accounting.be.DoubleEntry");
        doubleEntiesElementBEType.setTargetEntity(doubleEntiesElementTargetEntity);
            
        doubleEntiesBEType.setElementType(doubleEntiesElementBEType);
            
        //MemberType Define for doubleEnties
        member = new MemberType();
        member.setName("doubleEnties");
        member.setDescription("null");
        member.setType(doubleEntiesBEType);
        memberTypeList.add(member);
            
        return memberTypeList;
    }
    
    public ITransaction createEntity ()
    {
        return new TransactionImpl();
    }
    
}

        

