/*
 *
 * This file is automatically generated on Tue Jul 21 23:50:34 CST 2015
 */

    
package org.shaolin.vogerp.productmodel.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;

import org.shaolin.vogerp.productmodel.ce.*;


/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public interface IStorageItem 
    extends IPersistentEntity, IExtensibleEntity
{
    public final static String ENTITY_NAME = "org.shaolin.vogerp.productmodel.be.StorageItem";
    
 
    /**
     *  get id
     *
     *  @return id
     */
    public long getId();

    /**
     *  get productId
     *
     *  @return productId
     */
    public long getProductId();

    /**
     *  get warehouseId
     *
     *  @return warehouseId
     */
    public long getWarehouseId();

    /**
     *  get warehouse
     *
     *  @return warehouse
     */
    public WarehouseImpl getWarehouse();

    /**
     *  get product
     *
     *  @return product
     */
    public ProductImpl getProduct();

    /**
     *  get coordinate
     *
     *  @return coordinate
     */
    public java.lang.String getCoordinate();

    /**
     *  get itemStatus
     *
     *  @return itemStatus
     */
    public StorageItemStatusType getItemStatus();

    /**
     *  get number
     *
     *  @return number
     */
    public int getNumber();

    /**
     *  get serialNumber
     *
     *  @return serialNumber
     */
    public java.lang.String getSerialNumber();

    /**
     *  set id
     */
    public void setId(long id);

    /**
     *  set productId
     */
    public void setProductId(long productId);

    /**
     *  set warehouseId
     */
    public void setWarehouseId(long warehouseId);

    /**
     *  set warehouse
     */
    public void setWarehouse(WarehouseImpl warehouse);

    /**
     *  set product
     */
    public void setProduct(ProductImpl product);

    /**
     *  set coordinate
     */
    public void setCoordinate(java.lang.String coordinate);

    /**
     *  set itemStatus
     */
    public void setItemStatus(StorageItemStatusType itemStatus);

    /**
     *  set number
     */
    public void setNumber(int number);

    /**
     *  set serialNumber
     */
    public void setSerialNumber(java.lang.String serialNumber);


}

        