/*
 *
 * This file is automatically generated on Tue Jul 21 23:50:34 CST 2015
 */

    
package org.shaolin.vogerp.productmodel.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;

import org.shaolin.vogerp.productmodel.ce.*;


/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public class ProductImpl  implements org.shaolin.vogerp.productmodel.be.IProduct
{
    private static final long serialVersionUID = 0x90B1123CE87B50FFL;

    private final IConstantService ceService = AppContext.get().getConstantService();

    protected String getBusinessEntityName()
    {
        return "org.shaolin.vogerp.productmodel.be.Product";
    }

    public ProductImpl()
    {
        
        _extField = new BEExtensionInfo();
        
    }
    
    
        /**
     * Enable record
     */
    private boolean _enable = true;


    /**
     *  BEExtension _extType
     */
    protected String _extType;

    /**
     *  BEExtension _extField
     */
    protected BEExtensionInfo _extField;
        
   /**
     *  help is not available
     */    
    protected long id;
    
   /**
     *  help is not available
     */    
    protected long parentId;
    
   /**
     *  help is not available
     */    
    protected java.lang.String name;
    
   /**
     *  help is not available
     */    
    protected java.lang.String serialNumber;
    
   /**
     *  help is not available
     */    
    protected java.util.Date onSaleDate;
    
   /**
     *  help is not available
     */    
    protected java.util.Date onSaleDateStart;
    
   /**
     *  help is not available
     */    
    protected java.util.Date onSaleDateEnd;
    
   /**
     *  help is not available
     */    
    protected java.util.Date saleEndDate;
    
   /**
     *  help is not available
     */    
    protected java.util.Date saleEndDateStart;
    
   /**
     *  help is not available
     */    
    protected java.util.Date saleEndDateEnd;
    
   /**
     *  help is not available
     */    
    protected java.lang.String description;
    
   /**
     *  help is not available
     */    
    protected java.lang.String icon;
    
   /**
     *  help is not available
     */    
    protected java.lang.String photos;
    
   /**
     *  help is not available
     */    
    protected java.lang.String type;
    
   /**
     *  help is not available
     */    
    protected org.shaolin.vogerp.commonmodel.ce.PartyType interestedPartyType = org.shaolin.vogerp.commonmodel.ce.PartyType.NOT_SPECIFIED;
    
    protected int interestedPartyTypeInt = org.shaolin.vogerp.commonmodel.ce.PartyType.NOT_SPECIFIED.getIntValue();
    
        /**
     *  Is enable
     *
     *  @return boolean
     */
    public boolean isEnabled() {
        return _enable;
    }
            /**
     *  Is enable
     *
     *  @return boolean
     */
    private boolean get_enable() {
        return _enable;
    }
        
    /**
     *  get _extType
     *
     *  @return _extType
     */
    public String get_extType() {
        return _extType;
    }

    /**
     *  get _extField
     *
     *  @return _extField
     */
    public BEExtensionInfo get_extField() {
        return _extField;
    }
        
    /**
     *  get id
     *
     *  @return id
     */
    public long getId() {
        return id;
    }

    /**
     *  get parentId
     *
     *  @return parentId
     */
    public long getParentId() {
        return parentId;
    }

    /**
     *  get name
     *
     *  @return name
     */
    public java.lang.String getName() {
        return name;
    }

    /**
     *  get serialNumber
     *
     *  @return serialNumber
     */
    public java.lang.String getSerialNumber() {
        return serialNumber;
    }

    /**
     *  get onSaleDate
     *
     *  @return onSaleDate
     */
    public java.util.Date getOnSaleDate() {
        return onSaleDate;
    }

    /**
     *  get onSaleDateStart
     *
     *  @return onSaleDateStart
     */
    public java.util.Date getOnSaleDateStart() {
        return onSaleDateStart;
    }

    /**
     *  get onSaleDateEnd
     *
     *  @return onSaleDateEnd
     */
    public java.util.Date getOnSaleDateEnd() {
        return onSaleDateEnd;
    }

    /**
     *  get saleEndDate
     *
     *  @return saleEndDate
     */
    public java.util.Date getSaleEndDate() {
        return saleEndDate;
    }

    /**
     *  get saleEndDateStart
     *
     *  @return saleEndDateStart
     */
    public java.util.Date getSaleEndDateStart() {
        return saleEndDateStart;
    }

    /**
     *  get saleEndDateEnd
     *
     *  @return saleEndDateEnd
     */
    public java.util.Date getSaleEndDateEnd() {
        return saleEndDateEnd;
    }

    /**
     *  get description
     *
     *  @return description
     */
    public java.lang.String getDescription() {
        return description;
    }

    /**
     *  get icon
     *
     *  @return icon
     */
    public java.lang.String getIcon() {
        return icon;
    }

    /**
     *  get photos
     *
     *  @return photos
     */
    public java.lang.String getPhotos() {
        return photos;
    }

    /**
     *  get type
     *
     *  @return type
     */
    public java.lang.String getType() {
        return type;
    }

    /**
     *  get interestedPartyType
     *
     *  @return interestedPartyType
     */
    public org.shaolin.vogerp.commonmodel.ce.PartyType getInterestedPartyType() {
        return interestedPartyType;
    }

    /**
     *  get interestedPartyTypeInt
     *
     *  @return interestedPartyTypeInt
     */
    private int getInterestedPartyTypeInt() {
        return interestedPartyTypeInt;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    public void setEnabled(boolean enable) {
        _enable = enable;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    private void set_enable(boolean enable) {
        _enable = enable;
    }

    /**
     *  set _extType
     *  @param _extType which is the extension type of be object.
     */
    public void set_extType(java.lang.String _extType) {
        this._extType = _extType;
    }
        
    /**
     *  set id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     *  set parentId
     */
    public void setParentId(long parentId) {
        this.parentId = parentId;
    }

    /**
     *  set name
     */
    public void setName(java.lang.String name) {
        this.name = name;
    }

    /**
     *  set serialNumber
     */
    public void setSerialNumber(java.lang.String serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     *  set onSaleDate
     */
    public void setOnSaleDate(java.util.Date onSaleDate) {
        this.onSaleDate = onSaleDate;
    }

    /**
     *  set onSaleDateStart
     */
    public void setOnSaleDateStart(java.util.Date onSaleDateStart) {
        this.onSaleDateStart = onSaleDateStart;
    }

    /**
     *  set onSaleDateEnd
     */
    public void setOnSaleDateEnd(java.util.Date onSaleDateEnd) {
        this.onSaleDateEnd = onSaleDateEnd;
    }

    /**
     *  set saleEndDate
     */
    public void setSaleEndDate(java.util.Date saleEndDate) {
        this.saleEndDate = saleEndDate;
    }

    /**
     *  set saleEndDateStart
     */
    public void setSaleEndDateStart(java.util.Date saleEndDateStart) {
        this.saleEndDateStart = saleEndDateStart;
    }

    /**
     *  set saleEndDateEnd
     */
    public void setSaleEndDateEnd(java.util.Date saleEndDateEnd) {
        this.saleEndDateEnd = saleEndDateEnd;
    }

    /**
     *  set description
     */
    public void setDescription(java.lang.String description) {
        this.description = description;
    }

    /**
     *  set icon
     */
    public void setIcon(java.lang.String icon) {
        this.icon = icon;
    }

    /**
     *  set photos
     */
    public void setPhotos(java.lang.String photos) {
        this.photos = photos;
    }

    /**
     *  set type
     */
    public void setType(java.lang.String type) {
        this.type = type;
    }

    /**
     *  set interestedPartyType
     */
    public void setInterestedPartyType(org.shaolin.vogerp.commonmodel.ce.PartyType interestedPartyType) {
        this.interestedPartyType = interestedPartyType;
    if (interestedPartyTypeInt != interestedPartyType.getIntValue()) {
            interestedPartyTypeInt = interestedPartyType.getIntValue();
        }
    }

    /**
     *  set int interestedPartyType
     */
    private void setInterestedPartyTypeInt(int intValue) {
        this.interestedPartyTypeInt = intValue;
        if (interestedPartyTypeInt != interestedPartyType.getIntValue()) {
            interestedPartyType = (org.shaolin.vogerp.commonmodel.ce.PartyType)ceService.getConstantEntity(org.shaolin.vogerp.commonmodel.ce.PartyType.ENTITY_NAME).getByIntValue(interestedPartyTypeInt);
        }
    }

    
    /**
     * Check different according to primary key.
     */
    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof org.shaolin.vogerp.productmodel.be.ProductImpl))
            return false;
        org.shaolin.vogerp.productmodel.be.ProductImpl o = (org.shaolin.vogerp.productmodel.be.ProductImpl)obj;
        
        boolean result = super.equals(obj);

        boolean eq = true;
        
        return result;
    }

    /**
     * Generate hashCode according to primary key.
     */
    public int hashCode() {
        
        int result = super.hashCode();

        return result;
    }
        
    
     /**
     * Gets the String format of the business entity.
     *
     * @return String the business entity in String format.
     */
    public  String  toString() {
        StringBuffer aBuf = new StringBuffer();
        aBuf.append("org.shaolin.vogerp.productmodel.be.Product");
    
        aBuf.append(" : ");
        
        aBuf.append("enable=").append(_enable).append(", ");
        
        aBuf.append("id");
        aBuf.append("=");
        aBuf.append(id);
        aBuf.append(", ");
        
        aBuf.append("parentId");
        aBuf.append("=");
        aBuf.append(parentId);
        aBuf.append(", ");
        
        aBuf.append("name");
        aBuf.append("=");
        aBuf.append(name);
        aBuf.append(", ");
        
        aBuf.append("serialNumber");
        aBuf.append("=");
        aBuf.append(serialNumber);
        aBuf.append(", ");
        
        aBuf.append("onSaleDate");
        aBuf.append("=");
        aBuf.append(onSaleDate);
        aBuf.append(", ");
        
        aBuf.append("onSaleDateStart");
        aBuf.append("=");
        aBuf.append(onSaleDateStart);
        aBuf.append(", ");
        
        aBuf.append("onSaleDateEnd");
        aBuf.append("=");
        aBuf.append(onSaleDateEnd);
        aBuf.append(", ");
        
        aBuf.append("saleEndDate");
        aBuf.append("=");
        aBuf.append(saleEndDate);
        aBuf.append(", ");
        
        aBuf.append("saleEndDateStart");
        aBuf.append("=");
        aBuf.append(saleEndDateStart);
        aBuf.append(", ");
        
        aBuf.append("saleEndDateEnd");
        aBuf.append("=");
        aBuf.append(saleEndDateEnd);
        aBuf.append(", ");
        
        aBuf.append("description");
        aBuf.append("=");
        aBuf.append(description);
        aBuf.append(", ");
        
        aBuf.append("icon");
        aBuf.append("=");
        aBuf.append(icon);
        aBuf.append(", ");
        
        aBuf.append("photos");
        aBuf.append("=");
        aBuf.append(photos);
        aBuf.append(", ");
        
        aBuf.append("type");
        aBuf.append("=");
        aBuf.append(type);
        aBuf.append(", ");
        
        aBuf.append("interestedPartyType");
        aBuf.append("=");
        aBuf.append(interestedPartyType);
        aBuf.append(", ");
        
        return aBuf.toString();
    }
    
    
     /**
     * Gets list of MemberType.
     *
     * @return List     the list of MemberType.
     */
    public List<MemberType> getMemberList() {
        List<MemberType> memberTypeList = new ArrayList<MemberType>();
        
        MemberType member = null;
        
        org.shaolin.bmdp.datamodel.bediagram.LongType idBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for id
        member = new MemberType();
        member.setName("id");
        member.setDescription("null");
        member.setType(idBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.LongType parentIdBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for parentId
        member = new MemberType();
        member.setName("parentId");
        member.setDescription("null");
        member.setType(parentIdBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType nameBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for name
        member = new MemberType();
        member.setName("name");
        member.setDescription("null");
        member.setType(nameBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType serialNumberBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for serialNumber
        member = new MemberType();
        member.setName("serialNumber");
        member.setDescription("null");
        member.setType(serialNumberBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.DateTimeType onSaleDateBEType = new org.shaolin.bmdp.datamodel.bediagram.DateTimeType();
    
        //MemberType Define for onSaleDate
        member = new MemberType();
        member.setName("onSaleDate");
        member.setDescription("null");
        member.setType(onSaleDateBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.DateTimeType onSaleDateStartBEType = new org.shaolin.bmdp.datamodel.bediagram.DateTimeType();
    
        //MemberType Define for onSaleDateStart
        member = new MemberType();
        member.setName("onSaleDateStart");
        member.setDescription("null");
        member.setType(onSaleDateStartBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.DateTimeType onSaleDateEndBEType = new org.shaolin.bmdp.datamodel.bediagram.DateTimeType();
    
        //MemberType Define for onSaleDateEnd
        member = new MemberType();
        member.setName("onSaleDateEnd");
        member.setDescription("null");
        member.setType(onSaleDateEndBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.DateTimeType saleEndDateBEType = new org.shaolin.bmdp.datamodel.bediagram.DateTimeType();
    
        //MemberType Define for saleEndDate
        member = new MemberType();
        member.setName("saleEndDate");
        member.setDescription("null");
        member.setType(saleEndDateBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.DateTimeType saleEndDateStartBEType = new org.shaolin.bmdp.datamodel.bediagram.DateTimeType();
    
        //MemberType Define for saleEndDateStart
        member = new MemberType();
        member.setName("saleEndDateStart");
        member.setDescription("null");
        member.setType(saleEndDateStartBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.DateTimeType saleEndDateEndBEType = new org.shaolin.bmdp.datamodel.bediagram.DateTimeType();
    
        //MemberType Define for saleEndDateEnd
        member = new MemberType();
        member.setName("saleEndDateEnd");
        member.setDescription("null");
        member.setType(saleEndDateEndBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType descriptionBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for description
        member = new MemberType();
        member.setName("description");
        member.setDescription("null");
        member.setType(descriptionBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType iconBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for icon
        member = new MemberType();
        member.setName("icon");
        member.setDescription("null");
        member.setType(iconBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType photosBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for photos
        member = new MemberType();
        member.setName("photos");
        member.setDescription("null");
        member.setType(photosBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType typeBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for type
        member = new MemberType();
        member.setName("type");
        member.setDescription("null");
        member.setType(typeBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.CEObjRefType interestedPartyTypeBEType = new org.shaolin.bmdp.datamodel.bediagram.CEObjRefType();
    
        TargetEntityType interestedPartyTypeTargetEntity = new TargetEntityType();
        interestedPartyTypeBEType.setTargetEntity(interestedPartyTypeTargetEntity);
        interestedPartyTypeTargetEntity.setEntityName("org.shaolin.vogerp.commonmodel.ce.PartyType");
            
        //MemberType Define for interestedPartyType
        member = new MemberType();
        member.setName("interestedPartyType");
        member.setDescription("null");
        member.setType(interestedPartyTypeBEType);
        memberTypeList.add(member);
            
        return memberTypeList;
    }
    
    public IProduct createEntity ()
    {
        return new ProductImpl();
    }
    
}

        

