/*
 *
 * This file is automatically generated on Tue Jul 21 23:50:34 CST 2015
 */

    
package org.shaolin.vogerp.productmodel.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;



/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public class ProductCharacteristicImpl  implements org.shaolin.vogerp.productmodel.be.IProductCharacteristic
{
    private static final long serialVersionUID = 0x90B1123CE87B50FFL;

    private final IConstantService ceService = AppContext.get().getConstantService();

    protected String getBusinessEntityName()
    {
        return "org.shaolin.vogerp.productmodel.be.ProductCharacteristic";
    }

    public ProductCharacteristicImpl()
    {
        
        _extField = new BEExtensionInfo();
        
    }
    
    
        /**
     * Enable record
     */
    private boolean _enable = true;


    /**
     *  BEExtension _extType
     */
    protected String _extType;

    /**
     *  BEExtension _extField
     */
    protected BEExtensionInfo _extField;
        
   /**
     *  help is not available
     */    
    protected long id;
    
   /**
     *  help is not available
     */    
    protected long productId;
    
   /**
     *  help is not available
     */    
    protected org.shaolin.vogerp.productmodel.be.ProductImpl product;
    
   /**
     *  help is not available
     */    
    protected java.lang.String ceValues;
    
        /**
     *  Is enable
     *
     *  @return boolean
     */
    public boolean isEnabled() {
        return _enable;
    }
            /**
     *  Is enable
     *
     *  @return boolean
     */
    private boolean get_enable() {
        return _enable;
    }
        
    /**
     *  get _extType
     *
     *  @return _extType
     */
    public String get_extType() {
        return _extType;
    }

    /**
     *  get _extField
     *
     *  @return _extField
     */
    public BEExtensionInfo get_extField() {
        return _extField;
    }
        
    /**
     *  get id
     *
     *  @return id
     */
    public long getId() {
        return id;
    }

    /**
     *  get productId
     *
     *  @return productId
     */
    public long getProductId() {
        return productId;
    }

    /**
     *  get product
     *
     *  @return product
     */
    public org.shaolin.vogerp.productmodel.be.ProductImpl getProduct() {
        return product;
    }

    /**
     *  get ceValues
     *
     *  @return ceValues
     */
    public java.lang.String getCeValues() {
        return ceValues;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    public void setEnabled(boolean enable) {
        _enable = enable;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    private void set_enable(boolean enable) {
        _enable = enable;
    }

    /**
     *  set _extType
     *  @param _extType which is the extension type of be object.
     */
    public void set_extType(java.lang.String _extType) {
        this._extType = _extType;
    }
        
    /**
     *  set id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     *  set productId
     */
    public void setProductId(long productId) {
        this.productId = productId;
    }

    /**
     *  set product
     */
    public void setProduct(org.shaolin.vogerp.productmodel.be.ProductImpl product) {
        this.product = product;
    }

    /**
     *  set ceValues
     */
    public void setCeValues(java.lang.String ceValues) {
        this.ceValues = ceValues;
    }

    
    /**
     * Check different according to primary key.
     */
    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof org.shaolin.vogerp.productmodel.be.ProductCharacteristicImpl))
            return false;
        org.shaolin.vogerp.productmodel.be.ProductCharacteristicImpl o = (org.shaolin.vogerp.productmodel.be.ProductCharacteristicImpl)obj;
        
        boolean result = super.equals(obj);

        boolean eq = true;
        
        return result;
    }

    /**
     * Generate hashCode according to primary key.
     */
    public int hashCode() {
        
        int result = super.hashCode();

        return result;
    }
        
    
     /**
     * Gets the String format of the business entity.
     *
     * @return String the business entity in String format.
     */
    public  String  toString() {
        StringBuffer aBuf = new StringBuffer();
        aBuf.append("org.shaolin.vogerp.productmodel.be.ProductCharacteristic");
    
        aBuf.append(" : ");
        
        aBuf.append("enable=").append(_enable).append(", ");
        
        aBuf.append("id");
        aBuf.append("=");
        aBuf.append(id);
        aBuf.append(", ");
        
        aBuf.append("productId");
        aBuf.append("=");
        aBuf.append(productId);
        aBuf.append(", ");
        
        aBuf.append("product");
        aBuf.append("=");
        aBuf.append(product==null? "" : product.toString());
        aBuf.append(", ");
        
        aBuf.append("ceValues");
        aBuf.append("=");
        aBuf.append(ceValues);
        aBuf.append(", ");
        
        return aBuf.toString();
    }
    
    
     /**
     * Gets list of MemberType.
     *
     * @return List     the list of MemberType.
     */
    public List<MemberType> getMemberList() {
        List<MemberType> memberTypeList = new ArrayList<MemberType>();
        
        MemberType member = null;
        
        org.shaolin.bmdp.datamodel.bediagram.LongType idBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for id
        member = new MemberType();
        member.setName("id");
        member.setDescription("null");
        member.setType(idBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.LongType productIdBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for productId
        member = new MemberType();
        member.setName("productId");
        member.setDescription("null");
        member.setType(productIdBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.BEObjRefType productBEType = new org.shaolin.bmdp.datamodel.bediagram.BEObjRefType();
    
        TargetEntityType productTargetEntity = new TargetEntityType();
        productTargetEntity.setEntityName("org.shaolin.vogerp.productmodel.be.Product");
        productBEType.setTargetEntity(productTargetEntity);
            
        //MemberType Define for product
        member = new MemberType();
        member.setName("product");
        member.setDescription("null");
        member.setType(productBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType ceValuesBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for ceValues
        member = new MemberType();
        member.setName("ceValues");
        member.setDescription("null");
        member.setType(ceValuesBEType);
        memberTypeList.add(member);
            
        return memberTypeList;
    }
    
    public IProductCharacteristic createEntity ()
    {
        return new ProductCharacteristicImpl();
    }
    
}

        

