/*
 *
 * This file is automatically generated on Tue Jul 21 23:50:34 CST 2015
 */

    
package org.shaolin.vogerp.productmodel.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;

import org.shaolin.vogerp.productmodel.ce.*;


/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public class WarehouseImpl  implements org.shaolin.vogerp.productmodel.be.IWarehouse
{
    private static final long serialVersionUID = 0x90B1123CE87B50FFL;

    private final IConstantService ceService = AppContext.get().getConstantService();

    protected String getBusinessEntityName()
    {
        return "org.shaolin.vogerp.productmodel.be.Warehouse";
    }

    public WarehouseImpl()
    {
        
        _extField = new BEExtensionInfo();
        
    }
    
    
        /**
     * Enable record
     */
    private boolean _enable = true;


    /**
     * History version
     */
    protected int _version = 0;

    /**
     * History starttime
     */
    private java.util.Date _starttime = new java.util.Date();

    /**
     * History endtime
     */
    private java.util.Date _endtime = null;

    /**
     * History _optuserid
     */
    private long _optuserid = 0L;


    /**
     *  BEExtension _extType
     */
    protected String _extType;

    /**
     *  BEExtension _extField
     */
    protected BEExtensionInfo _extField;
        
   /**
     *  help is not available
     */    
    protected long id;
    
   /**
     *  help is not available
     */    
    protected long parentId;
    
   /**
     *  help is not available
     */    
    protected java.lang.String name;
    
   /**
     *  help is not available
     */    
    protected java.lang.String description;
    
   /**
     *  help is not available
     */    
    protected java.lang.String photoPath;
    
   /**
     *  help is not available
     */    
    protected java.lang.String location;
    
   /**
     *  help is not available
     */    
    protected StorageContainerType containerType = StorageContainerType.NOT_SPECIFIED;
    
    protected int containerTypeInt = StorageContainerType.NOT_SPECIFIED.getIntValue();
    
        /**
     *  Is enable
     *
     *  @return boolean
     */
    public boolean isEnabled() {
        return _enable;
    }
            /**
     *  Is enable
     *
     *  @return boolean
     */
    private boolean get_enable() {
        return _enable;
    }
        
    /**
     *  get version
     *
     *  @return version
     */
    public int getVersion() {
        return _version;
    }

    private int get_version() {
        return _version;
    }

    /**
     *  get operator user id
     *
     *  @return user id
     */
    public long getOptUserId() {
        return _optuserid;
    }

    /**
     *  get operator user id
     *
     *  @return user id
     */
    private long get_optuserid() {
        return _optuserid;
    }

    /**
     *  get start time
     *
     *  @return start time
     */
    public java.util.Date getStarttime() {
        return _starttime;
    }

    private java.util.Date get_starttime() {
        return _starttime;
    }

    /**
     *  get endtime
     *
     *  @return endtime
     */
    public java.util.Date getEndtime() {
        return _endtime;
    }

    private java.util.Date get_endtime() {
        return _endtime;
    }


    /**
     *  get _extType
     *
     *  @return _extType
     */
    public String get_extType() {
        return _extType;
    }

    /**
     *  get _extField
     *
     *  @return _extField
     */
    public BEExtensionInfo get_extField() {
        return _extField;
    }
        
    /**
     *  get id
     *
     *  @return id
     */
    public long getId() {
        return id;
    }

    /**
     *  get parentId
     *
     *  @return parentId
     */
    public long getParentId() {
        return parentId;
    }

    /**
     *  get name
     *
     *  @return name
     */
    public java.lang.String getName() {
        return name;
    }

    /**
     *  get description
     *
     *  @return description
     */
    public java.lang.String getDescription() {
        return description;
    }

    /**
     *  get photoPath
     *
     *  @return photoPath
     */
    public java.lang.String getPhotoPath() {
        return photoPath;
    }

    /**
     *  get location
     *
     *  @return location
     */
    public java.lang.String getLocation() {
        return location;
    }

    /**
     *  get containerType
     *
     *  @return containerType
     */
    public StorageContainerType getContainerType() {
        return containerType;
    }

    /**
     *  get containerTypeInt
     *
     *  @return containerTypeInt
     */
    private int getContainerTypeInt() {
        return containerTypeInt;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    public void setEnabled(boolean enable) {
        _enable = enable;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    private void set_enable(boolean enable) {
        _enable = enable;
    }

    
    /**
     *  set version
     */
    public void setVersion(int version) {
        _version = version;
    }

    private void set_version(int version) {
        _version = version;
    }

    /**
     *  set operator user id
     *  @parameter user id.
     */
    public void setOptUserId(long optUserId) {
        _optuserid = optUserId;
    }

    /**
     *  set operator user id
     *  @parameter user id.
     */
    private void set_optuserid(long optUserId) {
        _optuserid = optUserId;
    }

    /**
     *  set start time
     *  @parameter start time which is the start time of object.
     */
    public void setStarttime(java.util.Date starttime) {
        _starttime = starttime;
    }

    private void set_starttime(java.util.Date starttime) {
        _starttime = starttime;
    }

    /**
     *  set endtime
     *  @parameter endtime which is the end time of object.
     */
    public void setEndtime(java.util.Date endtime) {
        _endtime = endtime;
    }

    private void set_endtime(java.util.Date endtime) {
        _endtime = endtime;
    }

/**
     *  set _extType
     *  @param _extType which is the extension type of be object.
     */
    public void set_extType(java.lang.String _extType) {
        this._extType = _extType;
    }
        
    /**
     *  set id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     *  set parentId
     */
    public void setParentId(long parentId) {
        this.parentId = parentId;
    }

    /**
     *  set name
     */
    public void setName(java.lang.String name) {
        this.name = name;
    }

    /**
     *  set description
     */
    public void setDescription(java.lang.String description) {
        this.description = description;
    }

    /**
     *  set photoPath
     */
    public void setPhotoPath(java.lang.String photoPath) {
        this.photoPath = photoPath;
    }

    /**
     *  set location
     */
    public void setLocation(java.lang.String location) {
        this.location = location;
    }

    /**
     *  set containerType
     */
    public void setContainerType(StorageContainerType containerType) {
        this.containerType = containerType;
    if (containerTypeInt != containerType.getIntValue()) {
            containerTypeInt = containerType.getIntValue();
        }
    }

    /**
     *  set int containerType
     */
    private void setContainerTypeInt(int intValue) {
        this.containerTypeInt = intValue;
        if (containerTypeInt != containerType.getIntValue()) {
            containerType = (StorageContainerType)ceService.getConstantEntity(StorageContainerType.ENTITY_NAME).getByIntValue(containerTypeInt);
        }
    }

    
    /**
     * Check different according to primary key.
     */
    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof org.shaolin.vogerp.productmodel.be.WarehouseImpl))
            return false;
        org.shaolin.vogerp.productmodel.be.WarehouseImpl o = (org.shaolin.vogerp.productmodel.be.WarehouseImpl)obj;
        
        boolean result = super.equals(obj);

        boolean eq = true;
        
        return result;
    }

    /**
     * Generate hashCode according to primary key.
     */
    public int hashCode() {
        
        int result = super.hashCode();

        return result;
    }
        
    
     /**
     * Gets the String format of the business entity.
     *
     * @return String the business entity in String format.
     */
    public  String  toString() {
        StringBuffer aBuf = new StringBuffer();
        aBuf.append("org.shaolin.vogerp.productmodel.be.Warehouse");
    
        aBuf.append(" : ");
        
        aBuf.append("enable=").append(_enable).append(", ");
        
        aBuf.append("id");
        aBuf.append("=");
        aBuf.append(id);
        aBuf.append(", ");
        
        aBuf.append("parentId");
        aBuf.append("=");
        aBuf.append(parentId);
        aBuf.append(", ");
        
        aBuf.append("name");
        aBuf.append("=");
        aBuf.append(name);
        aBuf.append(", ");
        
        aBuf.append("description");
        aBuf.append("=");
        aBuf.append(description);
        aBuf.append(", ");
        
        aBuf.append("photoPath");
        aBuf.append("=");
        aBuf.append(photoPath);
        aBuf.append(", ");
        
        aBuf.append("location");
        aBuf.append("=");
        aBuf.append(location);
        aBuf.append(", ");
        
        aBuf.append("containerType");
        aBuf.append("=");
        aBuf.append(containerType);
        aBuf.append(", ");
        
        return aBuf.toString();
    }
    
    
     /**
     * Gets list of MemberType.
     *
     * @return List     the list of MemberType.
     */
    public List<MemberType> getMemberList() {
        List<MemberType> memberTypeList = new ArrayList<MemberType>();
        
        MemberType member = null;
        
        org.shaolin.bmdp.datamodel.bediagram.LongType idBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for id
        member = new MemberType();
        member.setName("id");
        member.setDescription("null");
        member.setType(idBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.LongType parentIdBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for parentId
        member = new MemberType();
        member.setName("parentId");
        member.setDescription("null");
        member.setType(parentIdBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType nameBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for name
        member = new MemberType();
        member.setName("name");
        member.setDescription("null");
        member.setType(nameBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType descriptionBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for description
        member = new MemberType();
        member.setName("description");
        member.setDescription("null");
        member.setType(descriptionBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType photoPathBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for photoPath
        member = new MemberType();
        member.setName("photoPath");
        member.setDescription("null");
        member.setType(photoPathBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType locationBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for location
        member = new MemberType();
        member.setName("location");
        member.setDescription("null");
        member.setType(locationBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.CEObjRefType containerTypeBEType = new org.shaolin.bmdp.datamodel.bediagram.CEObjRefType();
    
        TargetEntityType containerTypeTargetEntity = new TargetEntityType();
        containerTypeBEType.setTargetEntity(containerTypeTargetEntity);
        containerTypeTargetEntity.setEntityName("org.shaolin.vogerp.productmodel.ce.StorageContainerType");
            
        //MemberType Define for containerType
        member = new MemberType();
        member.setName("containerType");
        member.setDescription("null");
        member.setType(containerTypeBEType);
        memberTypeList.add(member);
            
        return memberTypeList;
    }
    
    public IWarehouse createEntity ()
    {
        return new WarehouseImpl();
    }
    
}

        

