bootdo:
server:
   # context-path: /myboot
   session-timeout: 1800
   tomcat:
       max-threads: 64
       min-spare-threads: 16
   port: 80
   uri-encoding: utf-8
   ipcongestion:
       enable: false
security:
    basic:
      enabled: false
logging:
  level:
    com.bootdo: info
spring:
  thymeleaf:
      mode: LEGACYHTML5
      cache: false
  jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
  http:
      multipart:
            max-file-size: 30Mb
            max-request-size: 30Mb
  devtools:
      restart:
        enabled: true
aliyun:
     msg:
       accessKeyId: LTAIU0fQuhxg949f
       accessKeySecret: 6o0Xz5e9KnE62TM5GLHWNEBXquNvJ5
       signName: 哈什社区
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.bootdo.**.domain




